### ISSUE TITLE
CommandPost fails to open in macOS 10.11.6

### ISSUE THREAD

**Issue by JTRidaura** [fcpxhacks/fcpxhacks#1007]
I try open app but dont opens

OSX El CAPITAN 10,11,6

**Comment by latenitefilms** [comment]
@JTRidaura - Can you provide some more information? Are you downloading the latest beta (currently beta 21) from the website - [commandpost.io](http://commandpost.io)? What happens when you run the CommandPost app? If there's any error messages, please take a screenshot and add to this issue.

**Comment by latenitefilms** [comment]
I'm going to close this issue as we haven't heard back from @JTRidaura and other users on macOS 10.11.6 haven't reported any problems.
