### ISSUE TITLE
Check plugins.finalcutpro.setup.unsupportedversion

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1008]
`mod.notifiedVersion` doesn't seem to be stored, so I'm assuming this setup panel will open every time CommandPost opens.

**Comment by randomeizer** [comment]
Does it actually run every time CommandPost opens now?

**Comment by latenitefilms** [comment]
Not sure, I've never tried running CommandPost on a computer without FCPX.

**Comment by randomeizer** [comment]
I did a while back, and fixed most of the issues at that point. Haven't
tried it lately...

**Comment by latenitefilms** [comment]
Actually, scrap that, this feature seems to work as intended. My bad!
