### ISSUE TITLE
Huge memory consumption during prolonged session

### ISSUE THREAD

**Issue by g4nym3de** [fcpxhacks/fcpxhacks#1013]
Usually my fcpx opens over night, and every one or two days when I check the activity monitor, it would take up 25gb of my total 32gb memory and make my mac completely useless. I suspect that it was due to  the watch folder I set up but I can't find proof. It didn't behave like this prior to beta 15 or something.

**Comment by latenitefilms** [comment]
Are you able to share a screenshot of the Activity Monitor when this is happening?

Is Final Cut Pro taking up all your memory, or CommandPost?

**Comment by g4nym3de** [comment]
Unfortunately I don't have a screenshot at hand. It is commandpost that's taking 18-20 gb of memory when it happens. I've just updated my hammerspoon (haven't been updated for about half a year) to the latest version and it seems commandpost is doing well at the time. Will update you with the screenshot should it happen again.

 cheers!

**Comment by g4nym3de** [comment]
<img width="802" alt="screen shot 2018-02-13 at 3 59 07 pm" src="https://user-images.githubusercontent.com/24290465/36139078-1b08a646-10d7-11e8-8024-6628f2cfdc38.png">
**update**
After leaving commandpost&fcpx open over the weekend, it now swallows 18gb of my memory ;).
macOS Version:                  10.12.6
CommandPost Locale:             en
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.4
Final Cut Pro Language:         en
Developer Mode:                 false

**Comment by latenitefilms** [comment]
Haha - well that's less than ideal @g4nym3de !

Do you happen to still have it running? Are you able to copy your entire error log?

Do you have Touch Bar, Tangent, Stream Deck or MIDI enabled in CommandPost?

The next beta will have lots of changes behind the scenes, so HOPEFULLY we've fixed this issue.

Interestingly though, CommandPost is only using 1.34GB of "real" memory in your screenshot - so this shouldn't have any impact on your performance. It's definitely leaking memory somehow though, that we need to solve.

**Comment by g4nym3de** [comment]
Sry for the late reply. I've browsed through the error log but forgot to make a copy, it didn't seem to be out of ordinary to my untrained eyes. All 4 component were left disabled at the time it happened. Real memory consumption seems low but it is still capable of making my machine hang.

Thanks for your patience and looking forward to the next update!

**Comment by g4nym3de** [comment]
The main suspect I can think of is the watch folder function. It was doing ok (rarely memory leak or so infrequent as I can't remember any) before I set up 2 watch folders for my AE renders and some still photos

**Comment by latenitefilms** [comment]
No worries - thanks heaps @g4nym3de !

We'll do some testing around watch folders.

**Comment by latenitefilms** [comment]
@g4nym3de - Are you still having this issue using the latest beta? If so, please re-open this issue and we'll investigate again.
