### ISSUE TITLE
Improve Color Board Functionality

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#102]
Currently the only way I've worked out how to reliably select the Color Board Pucks is with the mouse. Every attempt I've tried at using GUI Scripting has pretty much failed.

It would be AWESOME to come up with a workaround though, as using the mouse to grab the pucks is a bit of a hack job, and not ideal speed wise. Also, the only way to "move" the pucks reliably is via Final Cut Pro's Nudge shortcuts - which again is not ideal.

Ideally, I've LOVE to build some shortcut keys that when held down, you can use your mouse, touch pad or mouse scroll wheel to adjust the pucks quickly.

Any ideas @randomeizer ?

**Comment by randomeizer** [comment]
I'll see what I can find.
