### ISSUE TITLE
hs.watchable() useful?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#103]
Experiment to see if [hs.watchable](https://github.com/asmagill/hammerspoon_asm/tree/master/watchable) is useful for cross-module communication.

**Comment by latenitefilms** [comment]
@randomeizer - This might be handy for your plugin code?

**Comment by randomeizer** [comment]
Possibly. It's mostly useful for functions which are related to each other. We could possibly use it for storing some values we currently put into 'settings', but I'm not sure which features would make use of it in practice.
