### ISSUE TITLE
Allow batch exporting of multiple selections in a single clip whilst in list mode

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1035]
For example: 

<img width="486" alt="screen shot 2018-02-15 at 9 20 46 am" src="https://user-images.githubusercontent.com/22286696/36231269-8824b624-1231-11e8-96da-76463ae62ed4.png">

**Comment by latenitefilms** [comment]
@randomeizer - Do we already have an API for the timeline in list view?

**Comment by randomeizer** [comment]
The LibrariesList represents that. I'm not sure that it supports accessing
in and out points yet.

**Comment by latenitefilms** [comment]
I was going to tackle this, but I think it needs some fairly big changes to the FCPX API, so I might leave this to you @randomeizer to think about.

Currently the API works great if you need to select an entire clip in the browser, in either list or filmstrip views. However, if you have a clip with multiple ranges selected, then there's no allowance for this.

We basically need a "ranges" API within the "clip" API, then we need to update the Batch Export tool to support this.

I don't think this will be too tricky to implement, because if you have multiple ranges selected, it just means there's more than one `AXLayoutItem` (one for each "range") within the `AXGroup`.

**Comment by latenitefilms** [comment]
Guess we don't need this anymore since we've removed Browser Batch Export.
