### ISSUE TITLE
Customize columns in list view

### ISSUE THREAD

**Issue by econley68** [fcpxhacks/fcpxhacks#1038]
Is there any way to customize the columns in the browser list view.  In PP, you can add any metadata field.  I have metadata from CatDV that I would like to see at a glance instead of viewing in the info tab in the inspector

**Comment by latenitefilms** [comment]
Apologies @econley68 - I missed this message!

Unfortunately there's no way for us to implement this sadly - you'll just have to send in feedback to Apple. I agree - this would be REALLY helpful.
