### ISSUE TITLE
Add individual Color Board Puck Reset Commands

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1045]

**Comment by randomeizer** [comment]
You're talking about keyboard commands? There are methods in the API already, right?

**Comment by latenitefilms** [comment]
Yep, correct. So that you can assign resets to MIDI items, etc.

**Comment by randomeizer** [comment]
Right

**Comment by latenitefilms** [comment]
@randomeizer - I'm not having much luck with this, so might leave to you when you get a chance.

**Comment by latenitefilms** [comment]
@randomeizer - Whilst you're at it... do you want to add keyboard "commands" to all the new Color Inspector API stuff that's not already built-in to FCPX? For example, selecting individual Color Wheels? It'll be useful for things like adding Touch Bar buttons and MIDI controls.
