### ISSUE TITLE
Add New Color Inspector API to Keyboard Actions & MIDI Controls

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1050]
Currently none of the new Color Inspector API functions are exposed via "Commands" (i.e. keyboard shortcuts that you can assign in CommandPost).

**Comment by randomeizer** [comment]
What commands did you have in mind exactly?

**Comment by latenitefilms** [comment]
See: https://github.com/CommandPost/CommandPost/issues/884#issuecomment-352237809

**Comment by latenitefilms** [comment]
@randomeizer - FYI: Feedback from Iain Anderson:

> Up and testing this build. It did work at first, but it seems to have stopped responding. When I move a slider or knob, like a dial I have set to timeline zoom, it pops up the zoom controls but then doesn't do anything.
> Also, the color board is selected but doesn't move a slider.
> The color board controls were working earlier, and the change that seemed to cause the problem editing the preferences to add in the timeline zoom controls.
> So maybe there's something in there that's messed up the preferences.
> Other questions: is it possible to know which MIDI bank is selected?
> Also, I don't think there's a way to control the sat/luma on the color wheels with midi? Not showing up in the search for me.

One thing I think we need to solve is making sure that if we do make a typo or mistake in a MIDI control that it doesn't fail silently and also doesn't take things down. At the moment for example, if you make a mistake in the timeline zoom MIDI control for example, it seems to break the callback.

Thoughts?

**Comment by randomeizer** [comment]
Yeah, I agree there is some silent crashing happening that we need to find.
