### ISSUE TITLE
Update Color Wheels API to better handle moving puck

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1062]
As discussed, I propose we have a fixed value range for the color wheels "move control" API. If the puck is reset, the result should be `0,0`. Moving up should increase `y`, moving down should increase `y`, moving left should decrease `x` and moving right should increase `x`.

The scale should match whatever scale FCPX is using internally when you use the "Color Correction: Nudge Control Up/Down/Left/Right" shortcuts.

@randomeizer - you could probably use something like this to help determine the scale:

```lua
local eventtap = require("hs.eventtap")
local timer = require("hs.timer")
_fcp:launch()
timer.usleep(1000000)
local master = _fcp:inspector():color():colorWheels():master()
for i=1, 300 do
	master:show()
	local ui = master:UI()
	ui:setAttributeValue("AXFocused", true)
	timer.usleep(10000)
	eventtap.keyStroke({"ctrl", "alt", "shift"}, "up")
	timer.usleep(10000)
	local x, y = master:puckPosition().x, master:puckPosition().y
	print(string.format("x: %s, y: %s", x, y))	
end
```

The above code assumes the following shortcut keys:

<img width="1161" alt="screen shot 2018-03-01 at 6 20 39 am" src="https://user-images.githubusercontent.com/22286696/36808277-bbb3290c-1d18-11e8-824a-9258edfa9178.png">

**Comment by latenitefilms** [comment]
And add “shift” functions.

**Comment by latenitefilms** [comment]
We should also make sure the :show() functions for the pucks also make them focussed.

**Comment by randomeizer** [comment]
Well, that's what the :select() function is for. I kept it separate because
in general "show" just makes them visible, it doesn't press buttons, etc.

**Comment by latenitefilms** [comment]
Ah ha! That makes sense - sorry, I missed that.

**Comment by randomeizer** [comment]
Actually, you didn't miss it - they didn't exist! I was thinking of Color Board Pucks. The `select()` method now exists, in the branch.
