### ISSUE TITLE
isPlaying() not working on Event Viewer

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1065]
On a single screen, when in "Loop Playback" mode, this doesn't work for me:

```lua
_fcp:eventViewer().isPlaying:watch(function(value) print(string.format("Event: %s", value)) end)
```

If I turn off "Loop Playback" it works fine.

On a single screen, the normal viewer with looped both on and off works fine with this:

```lua
_fcp:viewer().isPlaying:watch(function(value) print(value) end)
```

All of the above tests are using the following screen setting:

<img width="780" alt="screen shot 2018-03-05 at 2 48 23 pm" src="https://user-images.githubusercontent.com/22286696/36956796-6cd9b91c-2084-11e8-88ea-7b1578c4f138.png">

Changing to "Default for Display" has the same results:

<img width="780" alt="screen shot 2018-03-05 at 2 53 18 pm" src="https://user-images.githubusercontent.com/22286696/36956893-fa2542b4-2084-11e8-9580-df14840b8cca.png">

**Comment by randomeizer** [comment]
Hmm...

**Comment by latenitefilms** [comment]
FYI: It also seems to break when I have Final Cut Pro on my external monitor in this configuration:

![screen shot 2018-03-12 at 12 56 07 pm](https://user-images.githubusercontent.com/22286696/37264590-51d22e8c-2602-11e8-933e-4acbcfb665be.png)

**Comment by randomeizer** [comment]
I think the issue with the Event Viewer is when the split is/isn't a 'half pixel'. If you were to tweak the width of the Event/Main Viewer with the splitter bar between them, you would probably get some variation in which of the two was or wasn't working.

I'll keep playing with it. I'll also push some code so that you can create some 'button snapshots' easily, so I can see exactly what's happening on your screen.

**Comment by randomeizer** [comment]
I've pushed a patch into #1065 that adds a `:snapshot(path)` method on Buttons. Could you create some snapshots of the `eventViewer` and `viewer` play button in Looping (playing and paused) and "Not Looping" (playing and paused) and upload them here please? This can be done like so:

```lua
local play = _fcpx:viewer():playButton()
play:snapshot("~/Desktop/viewer_paused_looping.png")
play:doPress()
play:snapshot("~/Desktop/viewer_playing_looping.png")
```

Tweak it for the 'non-looping' version. Thanks!

**Comment by latenitefilms** [comment]
Legend, thanks @randomeizer !

Here you go:
[Play Frame.zip](https://github.com/CommandPost/CommandPost/files/1804750/Play.Frame.zip)

**Comment by latenitefilms** [comment]
@randomeizer - Maybe we just need difference comparison spots depending on whether it's looped or not?

<img width="502" alt="screen shot 2018-03-17 at 5 44 10 pm" src="https://user-images.githubusercontent.com/22286696/37552507-df77c6e6-2a0a-11e8-92e0-5d554fee9421.png">
<img width="504" alt="screen shot 2018-03-17 at 5 42 27 pm" src="https://user-images.githubusercontent.com/22286696/37552508-dfa7fcbc-2a0a-11e8-8437-45034a574a24.png">

**Comment by randomeizer** [comment]
It doesn't work at low resolution because the black between the pause icon
is slightly whiter than outside

**Comment by latenitefilms** [comment]
Ah, right, gotcha. It would work fine based on the screenshots/snapshots I posted earlier - but in both cases my screens are fairly high-res, and I didn't test by making the screen resolution smaller.

As far as I can tell, there's no way to manipulate a `hs.image` in terms of colour, etc. using `hs.image` or `hs.canvas` currently, so what I'm thinking about doing is building a new Hammerspoon Extension that exposes all the crazy filters and effects you can do with [Core Image](https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_intro/ci_intro.html#//apple_ref/doc/uid/TP30001185-CH1-TPXREF101). That way we could make the snapshot black and white, and increase the contrast so that we have a much cleaner/easier image to analyse. We could also probably build in some native functionality to get the RGB values of an individual pixel in an image. No idea if this is in my skillset or not, but we'll see how we go!

**Comment by latenitefilms** [comment]
Note to self - revised test code:

```lua
local just = require("cp.just")
local fcp = require("cp.apple.finalcutpro")
fcp:launch()
local play = _fcp:viewer():playButton()
just.wait(2)
play:snapshot("~/Desktop/viewer_paused_looping.png")
just.wait(2)
play:press()
just.wait(2)
play:snapshot("~/Desktop/viewer_playing_looping.png")
just.wait(2)
play:press()
print("done")
```

**Comment by randomeizer** [comment]
Still having issues on my non-retina screen.
