### ISSUE TITLE
Automatic Roles and Channel Assignment/Panning

### ISSUE THREAD

**Issue by BenKingIV** [fcpxhacks/fcpxhacks#1088]
I'd like to see "Automatic Roles and Channel Assignment/Panning" based on (for instance) Track number in a multi-track movie file. So taking a file that's say EBU R123:16c and assigning each of the 16 mono tracks correctly to the Stereo and 5.1 channels.

For those that aren familiar with EBU R123:16c (5.1 with Music & Effect) the channel layout is:

Ch 1:	Stereo Left
Ch 2:	Stereo Right
Ch 3:	Stereo M&E Left
Ch 4:	Stereo M&E Right
Ch 5:	5.1 Final Mix Left
Ch 6:	5.1 Final Mix Right
Ch 7:	5.1 Final Mix Centre
Ch 8:	5.1 Final Mix LFE (Sub)
Ch 9:	5.1 Final Mix Left Surround
Ch 10:	5.1 Final Mix Right Surround
Ch 11:	5.1 M&E Left
Ch 12:	5.1 M&E Right
Ch 13:	5.1 M&E Center
Ch 14:	5.1 M&E LFE (Sub)
Ch 15:	5.1 M&E Left Surround
Ch 16:	5.1 M&E Right Surround

**Comment by randomeizer** [comment]
Could you attach some sample audio?

And is this something you can configure manually through the UI currently,
on a clip by blip basis?

**Comment by latenitefilms** [comment]
Possibility related to: #1079

**Comment by BenKingIV** [comment]
So on a single multitrack Quicktime - it's possible to set roles manually on each track - then you have to set the panner on each channel to the appropriate channel direction. I'll export a section of audio shortly with this layout. Note that each mono channel is lined up to -18dBFS 1kHz tone.

**Comment by BenKingIV** [comment]
[Mutlitrack QT Example - EBU R123 16c 5-1 with M&E.mov.zip](https://github.com/CommandPost/CommandPost/files/1825791/Mutlitrack.QT.Example.-.EBU.R123.16c.5-1.with.M.E.mov.zip)
Be aware these are all mono line up tones and so make sure you don't have your volume set high if you play all 16 Channels out one speaker!!!

**Comment by latenitefilms** [comment]
@BenKingIV - You can download a modified XML file here which does what I THINK you want:

https://gist.github.com/latenitefilms/cbc991bb13cee0d9de08ad992c874a6b

You'll need to place this XML file in `/Applications/Final Cut Pro.app/Contents/Frameworks/Flexo.framework/Versions/A/Resources/en.lproj` file (assuming you're using the English version of Final Cut Pro).

<img width="438" alt="screen shot 2018-03-20 at 8 57 20 am" src="https://user-images.githubusercontent.com/22286696/37624655-f6d3e0cc-2c1c-11e8-90a5-33a967dec05a.png">

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as we want to try and avoid manipulating inside the Final Cut Pro application bundle.

**Comment by BenKingIV** [comment]
Sure man

Any hope of achieving the same functionality outside of it?


Ben King

Head of Post Production

email: 	ben@facefilms.com <mailto:ben@facefilms.com>
phone: 	+44 7870 60 50 36
web: 	www.facefilms.com <http://www.facefilms.com/>

   You can't depend on your eyes when your imagination is out of focus.
    ~ Mark Twain
This e-mail message is confidential and may be subject to legal privilege. It may not be disclosed to or used by anyone other than the intended recipient(s). If you have received this e-mail in error please notify the sender immediately then delete it from your system. The contents of this message may contain personal views which are not the views of Face Films, unless specifically stated.  Face Films accepts no responsibility for Trojans or software viruses.  Thank you.

**Comment by latenitefilms** [comment]
Not really... unfortunately I think your best plan of attack is to just constantly send feedback to Apple until they listen. In the meantime, you can manipulate those XML files yourselves, but to keep things simple, we won't be including this functionality in CommandPost - sorry!

**Comment by BenKingIV** [comment]
Thats ok mate - I understand how to do it now so thank you for the help!

Best



Ben King

Head of Post Production

email: 	ben@facefilms.com <mailto:ben@facefilms.com>
phone: 	+44 7870 60 50 36
web: 	www.facefilms.com <http://www.facefilms.com/>

   You can't depend on your eyes when your imagination is out of focus.
    ~ Mark Twain
This e-mail message is confidential and may be subject to legal privilege. It may not be disclosed to or used by anyone other than the intended recipient(s). If you have received this e-mail in error please notify the sender immediately then delete it from your system. The contents of this message may contain personal views which are not the views of Face Films, unless specifically stated.  Face Films accepts no responsibility for Trojans or software viruses.  Thank you.
