### ISSUE TITLE
Incorrect Clipboard Label for Single Clip

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#109]
If I copy a single clip from the timeline, it appears with a **(+1)** in the menubar.

**Comment by latenitefilms** [comment]
I think maybe the code is treating audio and video separately? So if copy a clip with embedded audio it thinks of it as two "objects" rather than one?

For example, if I have a synchronised clip on a timeline which has both storyline audio and connected audio, if I copy it, the it will be listed as **(+3)** in the menubar.

If however I copy a single audio clip from the timeline, it will be listed correctly.

Multicam Clips, Compound Clips and Storylines seems to calculate correctly. It's just single clips on the timeline that seem to give unexpected results.

**Comment by randomeizer** [comment]
It may be something specific to synchronised clips. I have no problem with
video that has embedded audio.

**Comment by latenitefilms** [comment]
@randomeizer - It's not just synchronised clips, if I copy a single H.264 on the timeline (with 2 audio channels), it will appear as **(+1)** in the FCPX Hacks menubar.

**Comment by randomeizer** [comment]
Ok, I'll test it out.

**Comment by latenitefilms** [comment]
I'm not sure what causes this issue, but it's not really a show-stopper, and seems inconsistent between machines, so I'm just going to close this issue for now, and we can re-open it if anyone else brings it up.
