### ISSUE TITLE
Tangent: Add 'NEXT/PREVIOUS ACTIVE MODE' actions

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1103]
This implies that different modes can be 'active'. The idea being that some modes are app-specific, so it doesn't make sense to flip through them in every mode. If in FCPX, only global and FCPX-specific modes should be active.

Along with this, we add a 'NEXT ACTIVE MODE' and 'PREVIOUS INACTIVE MODE' action to Tangent Mapper and this can be used to flip within modes in the current app via Tangent buttons.

**Comment by latenitefilms** [comment]
Now that we only have one default mode, I'm just going to close this issue for now.
