### ISSUE TITLE
Tangent code doesn't properly handle ampersand's in names

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1109]
For example:

```lua
group:action(0x0AC00001, "Test & Test")
    :onPress(function() log.df("Test") end)
```

**Comment by randomeizer** [comment]
Can you post the XML that it's generating? Just the `<Name>...</Name>` element would be fine

**Comment by latenitefilms** [comment]
`<Name>Undo Last Move &amp; Resize</Name>`

...so the XML is valid. It's just Tangent Mapper isn't smart enough to translate the ampersand reference into a ampersand character.

Definitely a bug in Tangent Mapper, but for now, we should just work around it.

**Comment by latenitefilms** [comment]
@randomeizer - I'm not sure of the best way to solve this, so I'll leave this one to you.
