### ISSUE TITLE
hs.chooser colour inconsistencies between systems?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#111]
See: https://github.com/Hammerspoon/hammerspoon/issues/1150

**Comment by latenitefilms** [comment]
Updated `hs.chooser` in FCPX Hacks, so we'll see if that helps.

**Comment by latenitefilms** [comment]
FYI: This issue is caused when a user has **Reduce transparency** ticked in the Display Accessibility System Preferences.

<img width="780" alt="reducetransparancy" src="https://cloud.githubusercontent.com/assets/22286696/21464365/1c59a180-c9cf-11e6-8311-e277763bf51e.png">

**Comment by randomeizer** [comment]
Hmm, interesting. I guess the code isn't taking that into account, and
killing the transparency if it's enabled.

**Comment by latenitefilms** [comment]
Correct. I'm hoping this will just be fixed in `hs.chooser` rather than us having to do anything in FCPX Hacks.

**Comment by randomeizer** [comment]
Yeah, that's where the fix should go.
