### ISSUE TITLE
Trimming Window

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1146]
Laurent Lindebrings writes:

> **What feature would you like to see implemented or improved?**
> Since the begining FCP X we can have a triming window (two views) when it is done by the mouse but we canâ€™t have this triming view when we trim with the keyboard.
> I would like to have this two views (clip out - clip in) triming when using the keyboard.
> 
> Thanks for your work

I'm not sure I completely understand - @randomeizer ?

**Comment by randomeizer** [comment]
When you click and drag the cut with the mouse in Trim mode the viewer
becomes a split view and you see the in and out frame of both sides. With
the keyboard you just see the first frame on the right.

Unfortunately, I don't think there's anything we can do to get it working
with the keyboard - it is something only activated with a mouse drag.

**Comment by latenitefilms** [comment]
Laurent says:

> Sorry if it is not clear but I didn’t have FCPX in English :
> The function discribed is : Show detailed trimming feedback (in Preferences > Editing).
> This function works when triming with the mouse but is not working when we use keyboard shortcuts (on French version it is « , » & « ; »  but in English version it is left & right bracket.).
> That’s really strange that Apple never thought that people don’t always trim with the mouse.
> 
> Thanks

**Comment by latenitefilms** [comment]
I don't think there's anything we can do about this, so closing.
