### ISSUE TITLE
Implement an 'undo queue' for Color Board Mouse Puck

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#120]
Currently, the 'mouse puck' feature destroys the built-in undo queue because every adjustment creates a new item in the queue. That makes it hard to go back to previous colour choices.

Other than finding a way of pausing the built-in undo queue while dragging, a possible feature that could help would be our own undo queue, which could manifest itself as a small popup window, or possibly use the HUD. It would store an entry for each color change and could revert to it when selected.

We could also consider other features we could have related to this, such as saving a set of changes as a preset, etc.

**Comment by latenitefilms** [comment]
This would be so much work for a feature very few people use, so closing for now.
