### ISSUE TITLE
On a clean install, the "Setup" window will be stuck on top of the Accessibility panel

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1202]
Meaning you either have to move or close the Setup panel to enable accessibility.

**Comment by latenitefilms** [comment]
Yeah, this was a dodgy workaround to an issue where lots of people were complaining that the setup screen would disappear and you couldn’t get focus back by CMD+TAB.

However, when you do a fresh install of CommandPost, CMD+TAB should now work initially so we can probably fix this window level issue. We should also probably just allow CMD+TAB (ie enable Show Dock Icon) whenever a Setup panel is visible and disable again once the setup panel is closed.

Another option could be to just disable the CP dock item whenever FCPX is frontmost?

**Comment by randomeizer** [comment]
Do we need to actually disable the dock icon at all any more?

**Comment by latenitefilms** [comment]
I think we do for the fullscreen shortcuts in Final Cut Pro. I'm not 100%, but I also thought there was some weirdness with the Console when we turned the Dock Icon on?

Related: Test turning off Dock Item ONLY when Console or Full Screen Playback is visible #1024

**Comment by randomeizer** [comment]
There was weirdness on your computer with some stuff, but I could never
replicate it.

**Comment by latenitefilms** [comment]
Now that we’re both on High Sierra, hopefully we’ll be able to bug fix a bit easier!

**Comment by randomeizer** [comment]
Until you upgrade to the next version 😉
