### ISSUE TITLE
Internationalise UI text messages

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#121]
We should put our errors/dialogs/etc into plists so we can translate them into other languages more easily.

**Comment by latenitefilms** [comment]
Something [like this](https://github.com/kikito/i18n.lua) might be faster/better than using plists?

**Comment by randomeizer** [comment]
Yeah, could be.

**Comment by latenitefilms** [comment]
All the prep work has been done. Now we just need to do the actual translations.
