### ISSUE TITLE
Work out what we're doing with "commands" vs "actions"

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1217]

**Comment by latenitefilms** [comment]
@randomeizer - If we drop "Hacks Shortcuts" we can probably get rid of commands all together and just add the ability to assign shortcuts to actions?

**Comment by randomeizer** [comment]
Maybe? In general there are actually a few types of 'things' that can be done, some that have input values, some that don't, some that have a fixed range. That's kind of what Tangent has set up with their different input types.

It is worth thinking about though, and maybe if we could come up with some similar categories of 'inputs' or actions or whatever, that might help when we add new device support like for Palette, for example. We don't have to reinvent the wheel every time.

**Comment by latenitefilms** [comment]
I feel like we're too far down the rabbit hole now... we kinda have to keep the existing "commands" and "actions" for now. We can reconsider all this if we ever make a new Swift-based version of CommandPost.
