### ISSUE TITLE
Ability to Customise HUD Buttons Labels

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#122]
Some people have requested having icon buttons instead of text in the HUD, which makes sense and is a great idea, but almost completely impossible, as most of the menu items, effects, transitions, etc. that can be inserted into the HUD don't have icons.

So, instead, we'll add the ability to rename button labels, then, if people want a more "visual" button, they can use emoji's.

**Comment by randomeizer** [comment]
Isn't the HUD an HTML page?

**Comment by latenitefilms** [comment]
Yep - certainly is.

**Comment by randomeizer** [comment]
So why can't we use images exactly?

**Comment by latenitefilms** [comment]
Oh, we can. The problem is, if someone assigns "Modify > Retime > Slow > 50%" - then what icon do we use for this exactly? What Icons do we use for Effects, Transitions, Generators, etc. It just becomes all too hard - so much easier if the user can set the images themselves. We could even offer "custom images" (as opposed to just relying on text emoji's) later down the line.

**Comment by randomeizer** [comment]
I guess. Or we just pick something...

How customisable are you talking about making the button set?

**Comment by latenitefilms** [comment]
In a PEFECT world, it would be great if the HUD was completely resizable, and users could add and re-arrange the buttons in any way they want, rename them, as well as assign them icons (whether built-in or custom). As the HUD is just HTML, this is all technically possible - we just need to pick a good HTML5 UI Framework to build it all. At the moment, the HUD is INCREDIBLY simple - as I'm way too dumb to write complex JavaScript & CSS.

**Comment by latenitefilms** [comment]
Here's an example of some AMAZING HTML5/CSS/JavaScript UI magic:

https://www.synology.com/en-global/dsm/live_demo

**Comment by latenitefilms** [comment]
Closing in favour of #414
