### ISSUE TITLE
Make individual tests in a suite run asynchronously

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1222]
At the moment, all tests get run in a very long-running session, with no gaps via timers, etc. It's probably a good idea to have each test run in a timer, than then triggers the next test when it completes. This lets the computer breathe a little, as well as letting any other `timer` events triggered in the test to execute, which could be important.

**Comment by latenitefilms** [comment]
This could be a good test case for [RxLua](https://github.com/bjornbytes/RxLua)?

**Comment by randomeizer** [comment]
Maybe.

**Comment by randomeizer** [comment]
Look into busted:

http://olivinelabs.com/busted/
