### ISSUE TITLE
Update default control maps for Tangent devices

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1228]
The current 'default' maps are pretty thin. We should integrate what we can from the 'standard' FCPX mappings by Sam Mestman, something that Andy Knox started on with the attached configurations.
[Andy_Config.zip](https://github.com/CommandPost/CommandPost/files/2007933/Andy_Config.zip)

**Comment by latenitefilms** [comment]
**Shortcuts to add:**

**View:**
- [x] Zoom to Fit
- [x] Timeline History Back
- [x] Timeline History Forward
- [x] Show Histogram
- [x] Show Vectorscope
- [x] Show Video Waveform
- [x] Show/Hide Video Scopes

**Color:**
- [x] Color Board
- [x] Color Correction: Reset All Controls
- [x] Color Correction: Reset Current Effect Pane
- [x] Color Correction: Switch Between Inside/Outside Masks
- [x] Color Wheels

**Edit:**
- [x] Undo
- [x] Redo
- [x] Delete

**Clip:**
- [x] Break Apart Clip Items
- [x] Detach Audio
- [x] Expand Audio Components
- [x] Expand Audio/Video
- [x] Select Left Audio Edge
- [x] Select Left Edge
- [x] Select Right Audio Edge
- [x] Select Right Edge

**File:**
- [ ] New Compound Clip…

**Playback:**
- [x] Play Reverse
- [x] Pause

**Shortcuts Added:**
- [x] Next/Previous Frame
- [x] Next/Previous Edit
- [x] Apply Color Correction from Previous Clip
- [x] Apply Color Correction from Three Clips Back
- [x] Apply Color Correction from Two Clips Back
- [x] Blade
- [x] Blade All
- [x] Color Board: Switch to the Color Pane
- [x] Color Board: Switch to the Exposure Pane
- [x] Color Board: Switch to the Saturation Pane
- [x] Match Color…
- [x] Play
- [x] Play From Beginning
- [x] Play Full Screen
- [x] Play Selection
- [x] Toggle Color Correction Effects on/off
- [x] Trim End
- [x] Trim Start
