### ISSUE TITLE
Missing I18N strings for Color Board properties in French/German/Japanese

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1230]
Currently, we are using the `"cb master/shadow/midtone/highlight puck display name"` keys to identify the appropriate properties in the Color Board. This works in several languages, and in the older versions of FCP. In 10.4 however, these don't seem to match up to all the labels used in French, German and Japanese, and there doesn't seem to be any other key which covers them correctly.

Unfortunately, the only place that some of these labels seem to appear are buried inside the `/Contents/Frameworks/Flexo.framework/Resources/<lang>.lproj/FFInlineColorBoardContentView.nib` file, which I believe is the actual interface definition for the color board. In other words, it's hard-coded into the interface in that language, rather than using "strings".

This is rather inconvenient. As such, I'm thinking that our best option may be to create our own supplementary 'strings' files and add the missing labels in each language. We then add that file reference to `cp.apple.finalcutpro.strings`.

The downside is that we are then going to have to update this for different versions of the app. Not fun.

An alternative is to figure out a way of identifying them by location, but this is tough in 10.3 because the rows would disappear or appear alone when the Inspector got too short.

Here is the list of labels that can't be found via our current `strings`:

* French
    * Midtones: ~~Moyenne~~/Intermédiaires
    * Highlights: ~~Hautes~~/Tons clairs
* German
    * Midtones: ~~Mitten~~/Mitteltöne
    * Highlights: ~~Lichter~~/Hervorhebungen
* Japanese
    * Midtones: ~~中間~~/テキスト

**Comment by latenitefilms** [comment]
Haha... soooooooooo annoying!
