### ISSUE TITLE
Investigate using RxLua for asynchronous sequences of events

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#1240]
At its core, dealing with UI is an asynchronous activity. Currently, we are using a lot of `just.doUntil` statements to block the CP thread until something finishes. This is not ideal, but layering timers inside timers is not a fun way to code, or easy to untangle when there are issues.

I came across a library called [RxLua](https://github.com/bjornbytes/RxLua/) which is a Lua implementation of [reactivex.io](http://reactivex.io). Basically, it is a method of chaining together (possibly) asynchronous requests in a more readable and manageable way.

This is more of an exploratory issue currently. I'll play around with some options to see if it's worth implementing on a larger scale.

**Comment by latenitefilms** [comment]
Looks really cool - nice find!

**Comment by latenitefilms** [comment]
Closing, as the experimentation is now taking place in #1278.
