### ISSUE TITLE
Add Preferences Panel for AudioSwift

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1261]

**Comment by randomeizer** [comment]
What is AudioSwift?

**Comment by latenitefilms** [comment]
See: https://audioswiftapp.com

You can technically use the existing CommandPost MIDI tools - but because of the way AudioSwift works, it takes focus away from FCPX/CP, so I think it would be better if it was handled separately.

**Comment by latenitefilms** [comment]
Will address in #2410.
