### ISSUE TITLE
Make Menubar Popup's Dark

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1263]

**Comment by latenitefilms** [comment]
Related Issues:

- [Crash - hs._asm.guitk.menubar](https://github.com/asmagill/hammerspoon_asm/issues/15)
- [hs._asm.guitk.menubar.legacy in dual screens](https://github.com/asmagill/hammerspoon_asm/issues/14)
- [hs._asm.guitk.menubar.legacy `nil` error](https://github.com/asmagill/hammerspoon_asm/issues/13)

**Comment by randomeizer** [comment]
Should we move this to a later beta?

**Comment by latenitefilms** [comment]
Yeah, I've only got it in Beta 30, because I was playing around with it. It can definitely be pushed to a later beta if needed.

We'll only be able to merge it in once some of the issues in `hs._asm.guitk.menubar` are solved. I'm going to try and fix myself over the next few days.
