### ISSUE TITLE
Watch Folders stall when importing clips to Final Cut Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1282]
I don't think the Watch Folders have ever been used or tested by @randomeizer - so when you get a chance David, it might be worth making sure everything is working correctly on your machine?

**Comment by latenitefilms** [comment]
@randomeizer - FYI: I'm getting a new notification every time I reload CommandPost:

<img width="369" alt="screen shot 2018-07-10 at 11 15 13 pm" src="https://user-images.githubusercontent.com/22286696/42512128-27ecd39e-8497-11e8-8c8c-198d6901f848.png">

**Comment by randomeizer** [comment]
I fixed the issue with the file never getting removed from the queue after importing, but I couldn't resolve the situation where you have one or more files 'ready to import'. I'm successfully finding the existing notifcation, but I can't get it to `:withdraw()`. It just seems to ignore the request. Looking at the Objective-C code, I'm not sure what it's doing wrong really.
