### ISSUE TITLE
Allow Final Cut Pro Browser to go full height of Application

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#131]
Allow the Final Cut Pro Browser to go the full height of the application (same as when you double click the Inspector Heading).

**Comment by randomeizer** [comment]
As in, turn off the timeline?

**Comment by latenitefilms** [comment]
No, leave the timeline there, just "push" it to the right a bit (same idea as Inspector going full height).

Will require messing with a `.fcpworkspace` file, but I think it should be possible.

**Comment by randomeizer** [comment]
Ah, I see.

**Comment by latenitefilms** [comment]
I think we avoid messing around with the `.fcpworkspace` internals for now - it's too risky.
