### ISSUE TITLE
Fix "Your system has run out of application memory" bug

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1341]

**Comment by latenitefilms** [comment]
As discussed on Facebook @randomeizer - I THINK this might have something to do with `cp.app.prefs:prop()` watchers triggering repeatedly when nothing has actually changed.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now as it's too broad.

**Comment by latenitefilms** [comment]
Kevin reports:

Before:

![b4](https://user-images.githubusercontent.com/22286696/44029429-a47e9cc6-9f40-11e8-9d58-5088a21d6bf4.png)

After Force Quitting:

![after](https://user-images.githubusercontent.com/22286696/44029440-ad99d53c-9f40-11e8-8835-f2eabdd75540.png)

**Comment by latenitefilms** [comment]
The highlighted values are constantly increasing, even with Final Cut Pro closed:

<img width="1469" alt="screen shot 2018-08-13 at 10 49 21 pm" src="https://user-images.githubusercontent.com/22286696/44032682-3caefc0c-9f4b-11e8-9af8-d1aaaa1ea43f.png">

**Comment by latenitefilms** [comment]
This is what happens when I click the little arrow icon next to the `_NSArrayM` item:

<img width="1469" alt="screen shot 2018-08-13 at 10 51 28 pm" src="https://user-images.githubusercontent.com/22286696/44032788-8933495c-9f4b-11e8-9c36-d6671fc6df10.png">

**Comment by latenitefilms** [comment]
Before opening Final Cut Pro:

<img width="1469" alt="screen shot 2018-08-13 at 10 55 35 pm" src="https://user-images.githubusercontent.com/22286696/44033004-54a4ac34-9f4c-11e8-9557-80d21a41df76.png">

After opening and using Final Cut Pro:

<img width="1469" alt="screen shot 2018-08-13 at 10 57 17 pm" src="https://user-images.githubusercontent.com/22286696/44033013-5d9dd234-9f4c-11e8-8bb2-759a91f34729.png">

**Comment by latenitefilms** [comment]
<img width="1469" alt="screen shot 2018-08-13 at 11 00 14 pm" src="https://user-images.githubusercontent.com/22286696/44033344-708e7e38-9f4d-11e8-8e7e-77433b1ad694.png">
<img width="1469" alt="screen shot 2018-08-13 at 11 03 18 pm" src="https://user-images.githubusercontent.com/22286696/44033347-724b8b3a-9f4d-11e8-8931-691be27df754.png">
<img width="1469" alt="screen shot 2018-08-13 at 11 05 30 pm" src="https://user-images.githubusercontent.com/22286696/44033353-74172e10-9f4d-11e8-84c2-3f898317fc13.png">

**Comment by randomeizer** [comment]
What are you gleaning from this?

**Comment by latenitefilms** [comment]
<img width="1469" alt="screen shot 2018-08-13 at 11 14 53 pm" src="https://user-images.githubusercontent.com/22286696/44033880-1094b2e8-9f4f-11e8-95b4-9e3b5400ee3f.png">
<img width="1469" alt="screen shot 2018-08-13 at 11 16 54 pm" src="https://user-images.githubusercontent.com/22286696/44033890-14b23a3a-9f4f-11e8-9bf4-1dd5f0f9ab21.png">

**Comment by latenitefilms** [comment]
I left my computer running overnight with CommandPost running via the Leaks Instrument in Xcode, and Final Cut Pro playing a timeline on loop whilst also running the following code:

```lua
chaosTimer = hs.timer.doEvery(30, function()
	 _fcp:inspector():show()
	 hs.timer.doAfter(5, function()
	 	_fcp:inspector():hide()
	 end)
end)
```

When I came back to it 04:56:35 later, I was presented with the dreaded "Out of application memory" error - although Activity Monitor looked fine - but Xcode Instruments had stopped because "An error occurred trying to capture Leaks data - Error retrieving leak information".

Here's a photo of what my computer looked like when I came back to it:

![img_1781](https://user-images.githubusercontent.com/22286696/44059720-a2cfff64-9f95-11e8-85d9-471beb4dee6c.JPG)

Here's what Instruments showed:

<img width="1422" alt="screen shot 2018-08-14 at 7 37 39 am" src="https://user-images.githubusercontent.com/22286696/44059774-c9f0e8b0-9f95-11e8-9ad7-7f2f386eb8dd.png">
<img width="1422" alt="screen shot 2018-08-14 at 7 37 14 am" src="https://user-images.githubusercontent.com/22286696/44059775-ca1df756-9f95-11e8-92b9-70159bba2b2a.png">

**Comment by latenitefilms** [comment]
<img width="1453" alt="screen shot 2018-08-14 at 7 49 32 am" src="https://user-images.githubusercontent.com/22286696/44060039-9c7b3a9c-9f96-11e8-9793-ebc2f5bff360.png">

**Comment by latenitefilms** [comment]
Probably not related - but FYI:

<img width="1453" alt="screen shot 2018-08-14 at 8 06 49 am" src="https://user-images.githubusercontent.com/22286696/44060817-3bd68248-9f99-11e8-86d2-5fb03a881bc3.png">
<img width="1453" alt="screen shot 2018-08-14 at 8 06 47 am" src="https://user-images.githubusercontent.com/22286696/44060750-0acfca6a-9f99-11e8-84e6-7f4e95b86915.png">
<img width="1453" alt="screen shot 2018-08-14 at 8 06 45 am" src="https://user-images.githubusercontent.com/22286696/44060751-0aff5e38-9f99-11e8-852c-164efc206a7d.png">

**Comment by latenitefilms** [comment]
Leak from Kevin on 19th June:

<img width="930" alt="untitled" src="https://user-images.githubusercontent.com/22286696/44060905-9c5ed6ec-9f99-11e8-9970-c7775078789a.png">

**Comment by latenitefilms** [comment]
Leak from Kevin on 21st June:

<img width="2560" alt="memory" src="https://user-images.githubusercontent.com/22286696/44060925-a9e8b274-9f99-11e8-899f-20c6b44c6bf8.png">
<img width="2560" alt="quit-commandpost" src="https://user-images.githubusercontent.com/22286696/44060926-aa1c0d7c-9f99-11e8-83f8-4d7b411b55e2.png">

**Comment by latenitefilms** [comment]
Leak from Kevin on 13th July:

<img width="930" alt="commandpost" src="https://user-images.githubusercontent.com/22286696/44061019-06dcd866-9f9a-11e8-99dc-27e3309837f2.png">

**Comment by latenitefilms** [comment]
Leak from Kevin on 13th July:

<img width="2560" alt="commandpost-b4" src="https://user-images.githubusercontent.com/22286696/44061027-161b9d1c-9f9a-11e8-94fc-bb2f1431ff8e.png">
<img width="2560" alt="commandpost-after" src="https://user-images.githubusercontent.com/22286696/44061028-164b0926-9f9a-11e8-8ec9-d54c44df03b1.png">

**Comment by latenitefilms** [comment]
@cmsj - As suggested, I left my computer running overnight with CommandPost running via the Leaks Instrument in Xcode, and Final Cut Pro playing a timeline on loop whilst also running the following code:

```
local timer = require("hs.timer")
local fcp = require("cp.apple.finalcutpro")
chaosTimer = timer.doEvery(30, function()
	fcp:inspector():show()
	timer.doAfter(5, function()
		fcp:inspector():hide()
	end)	 
	local file = io.open("/Users/chrishocking/Desktop/CommandPost.log", "a")
	io.output(file)
	io.write(os.date() .. " - " .. collectgarbage("count") .. "\n")
	io.close(file)
end)
```

For this test, I also disabled the AX cache, by adjusting:

```
function axutils.cache(source, key, finderFn, verifyFn)
    local value = source and source[key]
    if value == nil or not axutils.isValid(value) or verifyFn and not verifyFn(value) then
        value = finderFn()
        if axutils.isValid(value) and source then
            -- Don't cache.
            --source[key] = value
        else
            return nil
        end
    end
    return value
end
```

The log file I was writing to the Desktop ended up as follows:

```
Wed Aug 15 23:35:43 2018 - 34016.487304688
Wed Aug 15 23:36:25 2018 - 46473.979492188
Wed Aug 15 23:37:02 2018 - 51819.454101562
Wed Aug 15 23:37:40 2018 - 40086.653320312
Wed Aug 15 23:39:19 2018 - 56778.796875
Wed Aug 15 23:40:20 2018 - 79220.682617188
Wed Aug 15 23:40:55 2018 - 49283.708007812
Wed Aug 15 23:41:15 2018 - 60838.08203125
Wed Aug 15 23:41:54 2018 - 70667.78125
Wed Aug 15 23:43:35 2018 - 85593.2109375
Wed Aug 15 23:44:52 2018 - 95993.771484375
Wed Aug 15 23:45:13 2018 - 50060.25
Wed Aug 15 23:46:22 2018 - 59470.7890625
Wed Aug 15 23:46:54 2018 - 76264.412109375
Wed Aug 15 23:47:20 2018 - 84014.870117188
Wed Aug 15 23:49:39 2018 - 99457.670898438
Wed Aug 15 23:50:42 2018 - 102134.66503906
Wed Aug 15 23:53:29 2018 - 58178.86328125
Thu Aug 16 00:07:48 2018 - 104832.80957031
Thu Aug 16 00:15:05 2018 - 73225.069335938
Thu Aug 16 00:31:25 2018 - 112716.94628906
Thu Aug 16 00:45:18 2018 - 89645.551757812
Thu Aug 16 01:08:30 2018 - 113587.12792969
Thu Aug 16 01:58:38 2018 - 130937.41699219
Thu Aug 16 02:14:50 2018 - 135066.65136719
Thu Aug 16 02:20:58 2018 - 154472.53222656
Thu Aug 16 02:30:12 2018 - 85716.178710938
```

At the start of the test:

<img width="2560" alt="screen shot 2018-08-15 at 11 41 22 pm" src="https://user-images.githubusercontent.com/22286696/44170097-9cb28680-a119-11e8-8f04-865cc671bb03.png">
<img width="1680" alt="screen shot 2018-08-15 at 11 41 22 pm 2" src="https://user-images.githubusercontent.com/22286696/44170098-9cb28680-a119-11e8-8e57-aebb722726b6.png">

At the end of the test:

<img width="2560" alt="screen shot 2018-08-16 at 5 53 33 am" src="https://user-images.githubusercontent.com/22286696/44170126-b94ebe80-a119-11e8-8c66-ec8be028c670.png">
<img width="1680" alt="screen shot 2018-08-16 at 5 53 33 am 2" src="https://user-images.githubusercontent.com/22286696/44170129-b9e75500-a119-11e8-91b2-dbccea410169.png">
<img width="1763" alt="screen shot 2018-08-16 at 5 54 20 am" src="https://user-images.githubusercontent.com/22286696/44170131-b9e75500-a119-11e8-9eb2-cb6b549a3686.png">
<img width="1763" alt="screen shot 2018-08-16 at 5 54 50 am" src="https://user-images.githubusercontent.com/22286696/44170132-ba7feb80-a119-11e8-9c5d-b54b1748db9e.png">
<img width="1763" alt="screen shot 2018-08-16 at 5 56 20 am" src="https://user-images.githubusercontent.com/22286696/44170134-ba7feb80-a119-11e8-9f0d-73b404d24f27.png">

**Comment by latenitefilms** [comment]
I know @randomeizer is sick of my screenshots, but here's another set.

This is on one of our iMac's.

All of a sudden, the Mac will popup the out of application memory error - notice the memory pressure graph and application memory value:

<img width="2560" alt="screen shot 2018-08-16 at 12 14 40 pm" src="https://user-images.githubusercontent.com/22286696/44183735-81626e00-a14f-11e8-8855-e22d8dddf758.png">

CommandPost is still accessible, so I run some garbage collection commands - it doesn't really help:

<img width="2560" alt="screen shot 2018-08-16 at 12 16 34 pm" src="https://user-images.githubusercontent.com/22286696/44183769-a35bf080-a14f-11e8-96f2-c88cfe556a12.png">

However, when I gracefully quit CommandPost, everything goes back to normal:

<img width="2560" alt="screen shot 2018-08-16 at 12 16 57 pm" src="https://user-images.githubusercontent.com/22286696/44184358-40b82400-a152-11e8-84c4-4c15d70e9d4d.png">

It seems like "kernel_task" is the biggest memory hog - but I'm not sure why or how it's connected.

Before & After:

![before and after](https://user-images.githubusercontent.com/22286696/44185995-31d56f80-a15a-11e8-9f82-86886c36e179.jpeg)

**Comment by latenitefilms** [comment]
Note to self - another test. This time just running CommandPost normally - without Xcode Instruments.

**Before:**

<img width="2560" alt="screen shot 2018-08-17 at 12 16 25 am" src="https://user-images.githubusercontent.com/22286696/44241094-170c0500-a205-11e8-9a18-30624a135acb.png">

**During:**

<img width="2560" alt="screen shot 2018-08-17 at 12 28 27 am" src="https://user-images.githubusercontent.com/22286696/44241097-1e331300-a205-11e8-84d6-7434dc735701.png">

**After:**

<img width="2560" alt="screen shot 2018-08-17 at 6 19 59 am" src="https://user-images.githubusercontent.com/22286696/44241098-20956d00-a205-11e8-83c2-20ddd5fc3892.png">

**Garbage Collection Count values:**
https://gist.github.com/latenitefilms/1ccb2f32fb8de13751a0423c9916906d

**Comment by latenitefilms** [comment]
An earlier test...

**Before:**

<img width="2560" alt="screen shot 2018-08-16 at 10 48 38 pm" src="https://user-images.githubusercontent.com/22286696/44241162-83870400-a205-11e8-9065-83c0d2e95fa1.png">
<img width="1680" alt="screen shot 2018-08-16 at 10 48 38 pm 2" src="https://user-images.githubusercontent.com/22286696/44241163-83870400-a205-11e8-9efa-a713d3bc1e00.png">

**During:**

<img width="2560" alt="screen shot 2018-08-16 at 11 19 58 pm" src="https://user-images.githubusercontent.com/22286696/44241172-900b5c80-a205-11e8-8d26-a7c34b2b31e4.png">
<img width="1680" alt="screen shot 2018-08-16 at 11 19 58 pm 2" src="https://user-images.githubusercontent.com/22286696/44241173-900b5c80-a205-11e8-912b-35bf2021448b.png">

**First Sign of Trouble:**

<img width="2560" alt="screen shot 2018-08-16 at 11 30 08 pm" src="https://user-images.githubusercontent.com/22286696/44241189-a0233c00-a205-11e8-9efc-7cf456764a8a.png">
<img width="1680" alt="screen shot 2018-08-16 at 11 30 08 pm 2" src="https://user-images.githubusercontent.com/22286696/44241190-a0233c00-a205-11e8-8bfa-bdbbc6b9af57.png">

**Just before CommandPost quit:**

<img width="2560" alt="screen shot 2018-08-16 at 11 30 49 pm" src="https://user-images.githubusercontent.com/22286696/44241196-af09ee80-a205-11e8-8e66-b10ed9923922.png">
<img width="1680" alt="screen shot 2018-08-16 at 11 30 49 pm 2" src="https://user-images.githubusercontent.com/22286696/44241197-afa28500-a205-11e8-803b-eb5ae1f5ee9f.png">

**Comment by latenitefilms** [comment]
For comparison, I just left Beta 29 running all night. Unfortunately a few hours after I started it weirdly got a Lua error, which broke my test `hs.timer`:

```lua
> local timer = require("hs.timer")
local fcp = require("cp.apple.finalcutpro")

local file = io.open("/Users/chrishocking/Desktop/CommandPost.log", "a")
io.output(file)
io.write(os.date() .. " - " .. collectgarbage("count") .. "\n")
io.close(file)

chaosTimer = timer.doEvery(10, function()
	fcp:inspector():show()
	timer.doAfter(5, function()
		fcp:inspector():hide()
	end)	 
	local file = io.open("/Users/chrishocking/Desktop/CommandPost.log", "a")
	io.output(file)
	io.write(os.date() .. " - " .. collectgarbage("count") .. "\n")
	io.close(file)
end)

2018-08-18 01:10:56: ********
2018-08-18 01:10:56: 01:10:56 ERROR:   LuaSkin: hs.timer callback error: .../extensions/cp/apple/finalcutpro/inspector/Inspector.lua:283: attempt to index a boolean value
stack traceback:
	.../extensions/cp/apple/finalcutpro/inspector/Inspector.lua:283: in function 'cp.apple.finalcutpro.inspector.Inspector.show'
	[string "local timer = require("hs.timer")..."]:10: in function <[string "local timer = require("hs.timer")..."]:9>
2018-08-18 01:10:56: ********
```

FYI: This bug has already been fixed in Beta 30.

However, that aside, it still ran all night without any "Out of application memory" errors by the morning.

**Before:**

<img width="2560" alt="screen shot 2018-08-17 at 11 07 00 pm" src="https://user-images.githubusercontent.com/22286696/44290667-1afb5e00-a2bd-11e8-865c-a79cf0e10d03.png">

**After:**

<img width="2560" alt="screen shot 2018-08-18 at 7 53 47 am" src="https://user-images.githubusercontent.com/22286696/44290672-1e8ee500-a2bd-11e8-8da7-191854093dba.png">

Here's the garbage collection test results prior to the timer failing:

https://gist.github.com/latenitefilms/37336803ea99ec6b9883f39ef083162d

**Comment by latenitefilms** [comment]
Ok, so I had a minor victory last night. I made the following minor change to latest `develop` branch:

<img width="1759" alt="screen shot 2018-08-19 at 8 41 09 am" src="https://user-images.githubusercontent.com/22286696/44303725-bce97c00-a38b-11e8-889a-d040a3fe7913.png">

With the CommandPost Grid Viewer Overlay enabled, Scrolling Timeline enabled, and Final Cut Pro playing, I then executed the following test code:

```lua
local timer = require("hs.timer")
local fcp = require("cp.apple.finalcutpro")

local file = io.open("/Users/chrishocking/Desktop/CommandPost.log", "a")
io.output(file)
io.write(os.date() .. " - " .. collectgarbage("count") .. "\n")
io.close(file)

chaosTimer = timer.doEvery(10, function()
	fcp:inspector():show()
	timer.doAfter(5, function()
		fcp:inspector():hide()
	end)	 
	local file = io.open("/Users/chrishocking/Desktop/CommandPost.log", "a")
	io.output(file)
	io.write(os.date() .. " - " .. collectgarbage("count") .. "\n")
	io.close(file)
end)
```

Here's the output of the log file:
https://gist.github.com/latenitefilms/987fe5fddb37b6496f79a6dccedea3a3

Here's what everything looked like before I executed that code:

<img width="2560" alt="screen shot 2018-08-19 at 12 20 10 am" src="https://user-images.githubusercontent.com/22286696/44303741-194c9b80-a38c-11e8-8f73-12a3a44c5a02.png">
<img width="1680" alt="screen shot 2018-08-19 at 12 20 10 am 2" src="https://user-images.githubusercontent.com/22286696/44303742-194c9b80-a38c-11e8-95ef-3d3c72434812.png">

Here's what everything looked like when I woke up:

<img width="2560" alt="screen shot 2018-08-19 at 8 23 30 am" src="https://user-images.githubusercontent.com/22286696/44303749-3d0fe180-a38c-11e8-91bf-9914ca6b0e8f.png">
<img width="1680" alt="screen shot 2018-08-19 at 8 23 30 am 2" src="https://user-images.githubusercontent.com/22286696/44303750-3d0fe180-a38c-11e8-97a5-b7ddee669536.png">

The minor victory was, that despite the fact that the memory pressure graph in Activity Monitor was looking very sad, CommandPost was still running and there was no "out of application memory" error - which is the first test this has happened for after running overnight.

I stopped the timer, then checked the garbage collection values:

<img width="2560" alt="screen shot 2018-08-19 at 8 39 07 am" src="https://user-images.githubusercontent.com/22286696/44303755-6df01680-a38c-11e8-8bf6-b1ae977c41b6.png">
<img width="1680" alt="screen shot 2018-08-19 at 8 39 07 am 2" src="https://user-images.githubusercontent.com/22286696/44303756-6df01680-a38c-11e8-9b6f-dbc74037b2a7.png">

What's most interestingly though, is that I then pressed the "Reload" button in the Error Log, and when CommandPost reloaded, the memory pressure graph went back to normal - as did the `kernel_task` real memory usage:

<img width="2560" alt="screen shot 2018-08-19 at 8 40 21 am" src="https://user-images.githubusercontent.com/22286696/44303761-9aa42e00-a38c-11e8-9a4e-ea99f95f75f0.png">
<img width="1680" alt="screen shot 2018-08-19 at 8 40 21 am 2" src="https://user-images.githubusercontent.com/22286696/44303762-9aa42e00-a38c-11e8-8b9a-84dcb7d9da0f.png">

It seems `collectgarbage("count")` isn't what we should be monitoring - it's the `hs.crash.residentSize()` (i.e. an integer containing the amount of RAM in use by Hammerspoon in bytes).

This makes me think that the issue is still that we're creating too many AX objects (or too many AX observer objects?), that aren't being properly destroyed/released - which is why `kernel_task` is using up so much RAM, as I ASSUME the Accessibility Framework uses kernel tasks to do it's thing.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now - in the HOPE that the recent changes have fixed this issue.

Fingers and toes crossed!
