### ISSUE TITLE
Remove cp.app.prefs.watch in favour of cp.app.prefs.prop

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1347]

**Comment by randomeizer** [comment]
Actually, my intention was to remove cp.app.prefs.watch, and use the
cp.app.prefs.prop to track specific properties. What are you watching
currently?

**Comment by latenitefilms** [comment]
Aha - yeah, that makes sense. I'll update the issue title.

**Comment by randomeizer** [comment]
Done.
