### ISSUE TITLE
Custom FCPX Menubar Items not appearing in the Console

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1357]
Alexandru Ionut writes:

> I’m back with a new feedback after using v30. I used to map on my midi console some shortcuts to 4 custom workspaces in FCPX. Now I can’t find this custom workspaces in ComandPost. I see only the 3 default workspaces from FCPX.

I've also found that user share destinations are no longer appearing in the Batch Export Destinations list, which I assume is related. I get the following warnings in the Error Log:

```lua
2018-07-03 08:30:29: 08:30:29 ** Warning:      menu: Unable to match step #3 in { "File", "Share", <function 1> }, a function with a value of function: 0x60c003c33980 with the app in cp.i18n.localeID: English [en]
2018-07-03 08:30:29: 08:30:29 ** Warning:      menu: Unable to match step #3 in { "File", "Share", <function 1> }, a function with a value of function: 0x60c003c33980 with the app in cp.i18n.localeID: English [en]
2018-07-03 08:30:29: 08:30:29 ** Warning:      menu: Unable to match step #3 in { "File", "Share", <function 1> }, a function with a value of function: 0x60c003c33980 with the app in cp.i18n.localeID: English [en]
2018-07-03 08:30:29: 08:30:29 ** Warning:      menu: Unable to match step #3 in { "File", "Share", <function 1> }, a function with a value of function: 0x60c003c33980 with the app in cp.i18n.localeID: English [en]

```

**Comment by randomeizer** [comment]
This seems to be an issue with Batch Export specifically, not with using functions in menu processing? I'll look into it.

**Comment by latenitefilms** [comment]
@randomeizer - Note also that Alexandru reports that his custom workspaces aren't appearing in the Console anymore, which may or may not be related? I wonder if we can get the custom workspaces lists from `plist` anyway, rather than relying on the menubar?

**Comment by randomeizer** [comment]
As far as I can tell, `menu:findMenuUI(...)` and therefore `menu:selectMenuUI(...)` (as well as the Rx `do` versions) all work correctly. Could the original poster provide their code?

**Comment by latenitefilms** [comment]
It must be a bug in the menu bar Console code then? Either way, I can reproduce the fact custom workspaces aren't appearing in the Console:

<img width="644" alt="screen shot 2018-07-17 at 10 33 45 pm" src="https://user-images.githubusercontent.com/22286696/42817470-8f72c7a6-8a11-11e8-88b0-23dcd1098c0b.png">

<img width="814" alt="screen shot 2018-07-17 at 10 33 55 pm" src="https://user-images.githubusercontent.com/22286696/42817496-9f90bc56-8a11-11e8-8e15-ed90031334a7.png">

Custom Share Presets are also not appearing in the Console anymore:

<img width="499" alt="screen shot 2018-07-17 at 10 35 17 pm" src="https://user-images.githubusercontent.com/22286696/42817543-c87ba39c-8a11-11e8-8c4f-26bf6d7d8813.png">

<img width="833" alt="screen shot 2018-07-17 at 10 35 23 pm" src="https://user-images.githubusercontent.com/22286696/42817560-d415b3aa-8a11-11e8-9ce1-aaddb283de83.png">

**Comment by latenitefilms** [comment]
Probably a bug in `plugins.finalcutpro.menu.menuaction`?

**Comment by randomeizer** [comment]
As far as I recall, this are simply read from the app menu, and are
unrelated to the `function` issue.

**Comment by randomeizer** [comment]
I don't think that any menus at all are showing up in the Console currently.
