### ISSUE TITLE
Rx Functions can fail silently

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1362]
I noticed that if there's a mistake in an Rx `Then` function it will fail silently.

**Comment by randomeizer** [comment]
Do you have an example?

**Comment by latenitefilms** [comment]
Not specifically, I noticed it when I added a `log.df()` and nothing was happening, and then later realised I hadn’t setup `local log = ...`.

**Comment by randomeizer** [comment]
By default, it will use the standard `error` function to output an error to the Error Log, but if a function has been provided to the `Now()` method without an error handler, it may have been getting lost in that case. I have put some code in the #1282 branch which will still use the `error` function if none is provided, which should hopefully surface more errors if they occur.

**Comment by latenitefilms** [comment]
@randomeizer - Perfecto - thanks!
