### ISSUE TITLE
Update Tangent Naming

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1368]
Andy Knox suggests via email:

> One comment is that I see that your generated controls.xml file is still using the same default – all uppercase – strings for the Name9 field. You’ll notice that I added in override strings for the default Wave map as (to me at least) it’s more pleasing to have a mix of both uppercase and lowercase letters. Another small point is that the Wave panel allows for 10 character labels for Parameters and Menus and 20 character labels (split over 2 lines) for Actions. Might it be possible for your generated controls.xml to include these longer strings for Wave ? Could I possibly help by editing the file where you associate the FCPX function with the Name field(s) to allow you to generate  the controls.xml file?

**Comment by randomeizer** [comment]
Just the 9+ characters to mixed case? Or the same for 2 or 4 characters?

**Comment by latenitefilms** [comment]
I reckon let's make them all mixed case?
