### ISSUE TITLE
batchExportToCompressor() - Ability to select custom destination

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#137]
Currently `batchExportToCompressor()` uses the Final Cut Pro preferences key `NSNavLastRootDirectory` to determine where it saves the Batch Exports to. However, rather than using this as the default, it would be better if the user could decide on a folder.

For example, this could be achieved with the following AppleScript:

```
choose folder with prompt "Please choose a Folder"
```

**Comment by randomeizer** [comment]
This has been implemented in #110
