### ISSUE TITLE
Final Cut Pro Media Watch Folder Inconsistencies

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1373]
@randomeizer - This still seems a bit weird/buggy.

Steps to reproduce:

- I have a watch folder with a bunch of clips in it. 
- I duplicate one clip in Finder.
- CommandPost throws up a notification saying "One file is ready to import". So far so good.
- I press the Notification Import button for the clip, but it actually pastes twice in Final Cut Pro, so I end up with two new clips in my timeline.
- If I duplicate the clip again at the Finder level, I then get a notification saying "3 files are ready to import" - all with the same filename.
- If I click one of these notification Import buttons, the notification goes away - but it still pastes two clips, not one, in the timeline.

<img width="385" alt="screen shot 2018-07-17 at 10 22 12 pm" src="https://user-images.githubusercontent.com/22286696/42816977-f7b1fe9c-8a0f-11e8-8a0d-66e792d12718.png">

<img width="224" alt="screen shot 2018-07-17 at 10 22 21 pm" src="https://user-images.githubusercontent.com/22286696/42816976-f75bff42-8a0f-11e8-9cfb-3a8940359f17.png">

<img width="385" alt="screen shot 2018-07-17 at 10 24 03 pm" src="https://user-images.githubusercontent.com/22286696/42817041-323ae8b2-8a10-11e8-88a5-d491087d85f6.png">

**Comment by latenitefilms** [comment]
I also still have the issue that each time I restart CommandPost I get another "x files are ready to import" notification.

<img width="1130" alt="screen shot 2018-07-17 at 10 43 43 pm" src="https://user-images.githubusercontent.com/22286696/42817947-f0e3bd32-8a12-11e8-9c66-d7cb0faecafd.png">

**Comment by randomeizer** [comment]
So, there are a couple of issues here. One is that when you duplicate a file in the watch folder, two file events are generated, one for the original file and one for the new one. Unfortunately, the flags for both are identical, so it's impossible to tell if when the original was actually a duplicate source, not a new file.

In the case where the original is still in the queue, I've added a check to ensure it doesn't get added twice. If it's already been processed, it will get added again.

I'm still working on the problem where importing a single file clears the 'ready' queue.

**Comment by randomeizer** [comment]
I believe I've resolved all known issues with the Media Folder implementation. Check out our when you get a chance.

**Comment by latenitefilms** [comment]
We should probably check that a project is actually open, in the RARE case that it's a brand new library. The user should also get an alert if the import fails.
