### ISSUE TITLE
CommandPost Preferences Consoles load very slowly

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1392]
Weirdly, when you activate the Console from Final Cut Pro or the Global Console from Finder it takes a little while to load the first time, but subsequent times are really fast. However, when you click a "Select" button from the Touch Bar, Stream Deck, Tangent or MIDI Preferences tabs, the Console loads slow every time, and I have no idea why. I think it needs some @randomeizer genius to figure out what's slowing things down.

**Comment by randomeizer** [comment]
Not sure about that one. Will require some investigation.
