### ISSUE TITLE
Remove Hacks Shortcuts

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1405]

**Comment by latenitefilms** [comment]
Actually @randomeizer - thinking about it, given no one's really complained about the lack of "Hacks Shortcuts" since 10.4 has come out, maybe we should just scrap this functionality all together? It's probably a lot nicer and cleaner if we manage all CommandPost shortcuts via the CommandPost Preferences anyway?

Thoughts?

**Comment by randomeizer** [comment]
It would make life simpler. It also means there is just one place to specify shortcuts, no matter what app we support in the future.

**Comment by latenitefilms** [comment]
Let's do it then. Time for me to let go.
