### ISSUE TITLE
Remove just.wait() from Spatial Conform Type & Title Alignment Actions

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1415]

**Comment by randomeizer** [comment]
What's the actual goal with this?

**Comment by latenitefilms** [comment]
I added actions for Title Alignment in #1402 and actions for Spatial Conform Types in #1401.

They both work as intended - HOWEVER to get them to work reliably, I had to use a `just.wait()`, which is obviously not ideal. Sadly, I wasn't able to determine what the timing issue was to be able to fix it. I believe the issue is caused by some timing issues in `cp.ui` elements?

The reason for the original issues is because there's no built-in shortcuts for text alignment or Spatial Conform Types, so this allows you to control those things via shortcuts, MIDI, Tangent, etc. It also allows you to change the values of multiple selected clips in one go, which is REALLY handy.
