### ISSUE TITLE
Reduce the amount of repeated JavaScript in Preferences

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1419]
Currently each UI item in Preferences pretty much creates it's own unique JavaScript. It would be much better if we just had a "global" JavaScript function that handles all the elements on the page. This might speed up the Preferences loading too.

**Comment by latenitefilms** [comment]
There's currently 79168 lines of code in the Preferences HTML - yikes!

There's also 92 JavaScript errors all saying:

```
SyntaxError: Unexpected token '{'. Expected a property name after '.'.
```

**Comment by latenitefilms** [comment]
Rather than using Lua to generate individual JavaScript functions for each UI item, we should probably do something like this:

https://www.kirupa.com/html5/handling_events_for_many_elements.htm

Rather than writing the JavaScript in `rows.html`, it should probably just go in `panel.html`.

This should reduce the amount of repeated JavaScript code considerably.

**Comment by latenitefilms** [comment]
Maybe relevant:

https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/README.md

**Comment by randomeizer** [comment]
Yeah, could definitely be useful.

**Comment by latenitefilms** [comment]
One area where we can definitely reduce the amount of repeating JavaScript is:

`plugins.core.preferences.manager.panel:addHandler`

We should only have to define this JavaScript handler once in the head of the HTML, then the individual elements should all trigger the same function.

**Comment by latenitefilms** [comment]
Also, rather than having seperate hidden DIVs for each Touch Bar/Shortcuts/MIDI group, we should probably only have the one set of UI items, and update their contents depending on the selected group.
