### ISSUE TITLE
Only use single hs._asm.axuielement.observer per PID

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1443]

**Comment by latenitefilms** [comment]
@randomeizer - Did you want to review this before I push out Beta 30 sometime this weekend? I THINK it's good to go unless you have any objections?

**Comment by randomeizer** [comment]
It definitely needs review. If I don't get time, push it to beta 31.

**Comment by latenitefilms** [comment]
This should just be a matter of reviewing and tweaking my code changes, so this shouldn’t be too much work to address for 1.0.0.
