### ISSUE TITLE
`nil` Error during Batch Export

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1450]
<img width="2016" alt="screen shot 2018-08-21 at 1 38 41 pm" src="https://user-images.githubusercontent.com/22286696/44379230-4ba2f800-a548-11e8-8a9d-3dcf10cb6803.png">

**Comment by latenitefilms** [comment]
I have no idea about this one @randomeizer ?

**Comment by randomeizer** [comment]
Hmm. Me either...

**Comment by latenitefilms** [comment]
I'm thinking it was a one-off timing bug. Closing issue.
