### ISSUE TITLE
Delay when pressing B (Next Mode) button on Tangent

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1471]
Tangent support seems to grind to a halt when quickly pressing the "B" (Change Mode) button on the Tangent Element. When you press the "B" button a few times quickly, the Tangent seems to lock up, but when you take the focus away from FCPX and go back again, it seems to update the mode and come back to life.

Can you reproduce on the Wave @randomeizer ?

I also saw this error when testing, which I have no idea why it would happen?

```lua
2018-08-26 19:07:08: ********
2018-08-26 19:07:08: 19:07:08 ERROR:   LuaSkin: hs.timer callback error: ...g/Github/CommandPost/src/extensions/cp/ui/MenuButton.lua:98: attempt to call a nil value (method 'value')
stack traceback:
	...g/Github/CommandPost/src/extensions/cp/ui/MenuButton.lua:98: in upvalue 'getFn'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:1001: in field '_get'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:517: in method 'get'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:887: in method 'update'
	...g/Github/CommandPost/src/extensions/cp/ui/MenuButton.lua:323: in function 'cp.ui.MenuButton.selectItemMatching'
	.../cp/apple/finalcutpro/inspector/color/CorrectionsBar.lua:231: in function 'cp.apple.finalcutpro.inspector.color.CorrectionsBar.activate'
	.../cp/apple/finalcutpro/inspector/color/ColorInspector.lua:241: in function 'cp.apple.finalcutpro.inspector.color.ColorInspector.activateCorrection'
	...ions/cp/apple/finalcutpro/inspector/color/ColorBoard.lua:272: in function 'cp.apple.finalcutpro.inspector.color.ColorBoard.show'
	...p/apple/finalcutpro/inspector/color/ColorBoardAspect.lua:131: in function 'cp.apple.finalcutpro.inspector.color.ColorBoardAspect.show'
	...sions/cp/apple/finalcutpro/inspector/color/ColorPuck.lua:269: in function 'cp.apple.finalcutpro.inspector.color.ColorPuck.show'
	...ub/CommandPost/src/plugins/finalcutpro/tangent/color.lua:111: in local 'action'
	...g/Github/CommandPost/src/extensions/cp/deferred/init.lua:69: in function <...g/Github/CommandPost/src/extensions/cp/deferred/init.lua:67>
2018-08-26 19:07:08: ********
```

**Comment by latenitefilms** [comment]
Also, should we stop CommandPost from switching to the Video Inspector, when we switch to the Video Mode? I think it would be better if we don't change the UI when changing modes, but we do change the UI when triggering a function (i.e. the FCPX UI should update automatically when we move the wheels in Video mode to change scale for instance). Thoughts @randomeizer ?

**Comment by latenitefilms** [comment]
I think maybe the "Video Mode" is what's causing the issues. Maybe a garbage collection issue?

**Comment by randomeizer** [comment]
If it's locking up, it's most likely a notification bug. Going to have to Rx it...

**Comment by randomeizer** [comment]
But yeah, we can turn off switching to Video when in Video mode. I think we already dropped that from the other modes.
