### ISSUE TITLE
Option to use iMessages for Mobile Notifications

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#156]
Currently FCPX Hacks Mobile Notifications only uses Prowl. This should be switchable between Prowl & iMessages (and maybe even Facebook & Twitter messages?).

**Comment by randomeizer** [comment]
And maybe Pushbullet? They have an API for 3rd party integration.

**Comment by latenitefilms** [comment]
Never heard of it - but sounds good!

**Comment by randomeizer** [comment]
I haven't used it, but seen a couple of good reviews lately. It may or may
not actually be appropriate.

**Comment by latenitefilms** [comment]
@randomeizer - I've made some tweaks based on your suggestions.

**Comment by randomeizer** [comment]
Cool, I'll take a look soon
