### ISSUE TITLE
Watch Folders - Can't Add Compressor Settings

### ISSUE THREAD

**Issue by marlowe310** [fcpxhacks/fcpxhacks#1565]
Hey I'm attempting to set up Watch Folders (using the latest versions of Compressor, FCPX, and CP) -- I can select a folder, but when I try to pick a Compressor Setting, all are greyed out (custom and default). Is this a known issue or is something likely wrong on my end?

Thanks much!

**Comment by latenitefilms** [comment]
Thanks for reporting @marlowe310 - we'll investigate.
