### ISSUE TITLE
Touch Bar Preferences UI Bug

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1568]
Michael Lunt writes:

> **What went wrong?**
> Multiple instances of touchbar button.  Instead of having just the one instance of a button appearing it appears in the empty slots available on the previous bar for FCPX (Bar 1) and also on the bar for All Applications.  Not sure why this is happening and also the application seems very slow to load in the selected icon and/or the action widget I select.  Not sure if this is expected.
> 
> **What did you expect to happen?**
> When I add a touch bar button it is placed where I want and only one instance of it.

**Comment by latenitefilms** [comment]
I'm going to close this, as I wasn't able to reproduce and never heard back from Michael.

**Comment by latenitefilms** [comment]
Waiting on Michael to send us a screen capture.

**Comment by latenitefilms** [comment]
Whilst we wait for a screen recording, it would be handy to see if all is working as expected on your machine David.

**Comment by latenitefilms** [comment]
Michael writes:

> I cannot do a screen recording but I can share some stills that show the issue.
> 
> Image 4 shows how CommandPost is duplicating the command three times over and also Image 1 is showing how CommandPost is copying the command to the All Application Bar 1.  If I remove it from here it also removes it from the FCPX Bar that I placed it in.
> 
> It’s a very strange bug.  Hope you can help.

![image](https://user-images.githubusercontent.com/22286696/50248991-e9dc9700-0430-11e9-983e-7debfd2d069b.jpeg)
![image 2](https://user-images.githubusercontent.com/22286696/50248997-ed701e00-0430-11e9-8889-4ca6d31bbf54.jpeg)
![image 3](https://user-images.githubusercontent.com/22286696/50248998-ee08b480-0430-11e9-811e-ad9857b6e12b.jpeg)
![image 4](https://user-images.githubusercontent.com/22286696/50248999-ee08b480-0430-11e9-905e-f042cbef5977.jpeg)

**Comment by randomeizer** [comment]
This looks a little bit similar to the bug I spotted in the Stream Deck config, where it got into a weird situation where two rows were synced together, change one, the other changes with it. It could be that the bug is in the config screen.

**Comment by latenitefilms** [comment]
Yeah, it's a weird one - I can't seem to reproduce.
