### ISSUE TITLE
Remove Advanced Preferences Panel

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1601]
Rather than have a user accessible developer mode toggle, I think we should basically just "enable" developer mode if we're loading the Lua scripts from the developer source directory (as opposed to from within the App Bundle).

Basically if `hs.settings.get("MJConfigFile") != nil` then we turn "developer mode" on (meaning we enable developer mode in webview's and load `cp.developer` on launch).

**Comment by latenitefilms** [comment]
Thinking about it further, we can probably remove the "Advanced" preferences tab all together, given that "Automatic Script Reloading" can easily be toggled via the Error Log, and I doubt anyone's actually using the Command Line Tool.

**Comment by photonclock** [comment]
Well, I just discovered CommandPost and the first thing I got excited about was using the command line tool...I'm running beta47 - went searching for it...no Advanced tab in the prefs. Was the command line tool removed entirely?

**Comment by latenitefilms** [comment]
@photonclock - Yes, it's been removed from the UI, as no one was really using it, but you can easily enable it via the Error Log.

Just type `hs.ipc.cliInstall()` in the Error Log to install.

We can easily add back Command Line support if it's something you feel passionately about though?

**Comment by latenitefilms** [comment]
Will solve in #1692
