### ISSUE TITLE
Move fullscreenKeyboardWatcher() into hs.finalcutpro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#161]

**Comment by randomeizer** [comment]
Actually, I think this should be moved into a plugin.

**Comment by latenitefilms** [comment]
I feel like the watcher itself should be part of `hs.finalcutpro`, but the functions called by the watcher should be in the plugin.

I think eventually we should have `hs.finalcutpro.watcher` that allow us to trigger things when Final Cut Pro is opened, closed, hidden, gone into full screen mode, the Command Editor is opened or close, the preferences files has been updated, etc.

**Comment by randomeizer** [comment]
What is it watching exactly? The fullscreen window? Or the keyboard?

**Comment by latenitefilms** [comment]
Kinda both.

It's main purpose is to watch the keyboard for keypresses (it's looking for when the user presses any of the following Final Cut Pro keyboard commands: `SetSelectionStart`, `SetSelectionEnd`, `AnchorWithSelectedMedia`, `AnchorWithSelectedMediaAudioBacktimed`, `InsertMedia` or `AppendWithSelectedMedia`) - but it only works when you're in fullscreen mode.

So... the fullscreen watcher should be in `hs.finalcutpro`, but the `hs.eventtap` should be in a plugin.

**Comment by randomeizer** [comment]
Yeah, agreed. There is actually a 'watch' method in the FullscreenWindow
already, but it's untested. Should work in the same way as the
CommandEditor watch method.

**Comment by randomeizer** [comment]
I've created `watch`/`unwatch` methods in `FullScreenWindow` in the #217 issue, and the function has been migrated into a plugin. Can close this now.
