### ISSUE TITLE
Clean up code comments

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1618]
In retrospect, I reckon we can probably loose:

```lua
--------------------------------------------------------------------------------
-- Logger:
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Hammerspoon Extensions:
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- CommandPost Extensions:
--------------------------------------------------------------------------------
```

**Comment by latenitefilms** [comment]
Ummm, actually, started doing this then changed my mind.

**Comment by randomeizer** [comment]
I never put them in anyway :p

**Comment by latenitefilms** [comment]
Yeah... I have a comment obsession it seems.

I'm going to reopen this, as I am probably far to excessive when it comes to commenting code in big blocks.

**Comment by randomeizer** [comment]
Personally, I dint like the big block header sections in general. Comments are important at times, but generally, if you can't understand the code from the code, it probably needs to be rewritten.

**Comment by latenitefilms** [comment]
Your definitely gonna need to rewrite the MIDI callback then... ;)
