### ISSUE TITLE
 Viewer Overlays prevent user from clicking Viewer GUI

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1651]

**Comment by latenitefilms** [comment]
Dimitar Maratilov [writes](https://www.facebook.com/groups/commandpost/permalink/2892808527641506/?__cft__[0]=AZUASA0-MnyPq-unvpsR_PFqfFXP_1pweEDd0CPBqfAQLkOPluwn_DSv2aBaI9hypzfi4hA4FiSzhlHzuNXetcRhiOx0511cNb-xG_yHTPGBtLE1e-nA0BM0EAozA_4xt1X9puJXWCUeaWJBPQ2v-sQIMTbfD-msH9rNulOnhejI7gEGltu16hxNtkKtUq6u4uE&__tn__=%2CO%2CP-R):

> When using moveable guides I'm unable to transform elements in my timeline is there a way, or this functionality isn't available yet.

**Comment by randomeizer** [comment]
Not sure there is any good way around this. Basically, our overlays put a mostly-transparent UI element on top of the FCP UI, which will collect any mouse-clicks, etc.

Two possible options:

1. Update our Overlays to use the official FCP Overlay function (won't work for things like draggable guides) (cf #2438)
2. Listen for mouse clicks in the overlay and do try sending it on to FCP at the relevant coordinate. Not sure this is possible, but _maybe_ via eventtap?

**Comment by latenitefilms** [comment]
Or we make each thing we draw it’s own unique canvas object.

**Comment by latenitefilms** [comment]
Closing in favour of #2719
