### ISSUE TITLE
Conflicts with Shuttle Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#166]
From Duncan:

> Hi Chris. 
> 
> Any idea why fcpx hacks might not play nicely with come to shuttle proud contour shuttle pro driver?
> 
> I get weird behaviors when i run both together.
>
> It affects the JKL keys amongst others. So I can't play the cut, or stop it. I tried it in a clean user login, with and without Shuttlepro, and it's definitely that. DO you want to "Friend" me and we can do this off board?

**Comment by randomeizer** [comment]
I haven't used it myself, but my guess is that the Shuttlepros are doing
their own keystroke manipulation, which may be stepping on the toes of
Hammerspoon's eventtap module.

**Comment by latenitefilms** [comment]
From Sharkbait:

> The “K” key does not seem to work while FCX hacks is running in conjunction with Contour Shuttle Pro.
> 
> This is the FCPX default set loaded, but seems across the board
> 
> It’s an old problem, and I thought I’d fixed it, but seems not.

**Comment by latenitefilms** [comment]
I'm not sure we can't do much about this, so I'm just going to close this issue for now.

**Comment by latenitefilms** [comment]
I'm going to re-open this issue, as I've had a few more complaints from users that want to use both the Contour Shuttle Pro and CommandPost. I've been in touch with Contour, so hopefully we can come up with a solution.

**Comment by latenitefilms** [comment]
I'm going to close this again, as I stopped getting emails from people complaining, so hopefully either we've fixed the bug, or Contour has!
