### ISSUE TITLE
Values on Tangent Display are not identical to FCPX UI

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1672]
Nash writes:

> 2. Would it be possible to also send all brightness values to Tangent as well?
> 
> 3. I notice the values on from the FCPX does not really match up with the Tamgent Values. Example. In FCPX. if POS X is -16.3 in Tangent it would display as -16.2. Would it be possible to correct this offset?

**Comment by latenitefilms** [comment]
@randomeizer - We may have discussed this in the past, but it would be great if the wheels values on the Tangent display matches the R/G/B values that are visible in the inspector. This requires maths, so it's sadly outside of my department.

**Comment by latenitefilms** [comment]
I'm also not sure why Saturation & Brightness values aren't being displayed on the Tangent. The Tangent Mapper is setup correctly, so it must be a problem in the Lua code where we're failing to send the correct values?

**Comment by latenitefilms** [comment]
Actually, ignore that last comment - I'd found a bug with those.

**Comment by latenitefilms** [comment]
However, the offset mentioned in the original issue... I have no idea. I assumed it was a rounding error of some kind, but it seems to be 0.1 off most of the time. Any ideas?

**Comment by latenitefilms** [comment]
I think for the wheels, instead of displaying the `wheel:colorOrientation()`, it would be better to use `wheel:colorValue()` and send a string (i.e. "10 0 1" - for the RGB values).

I'm just not sure how to convert `wheel:colorValue()` into a number that matches what we see in the inspector:

<img width="1077" alt="Screen Shot 2019-03-14 at 9 20 57 pm" src="https://user-images.githubusercontent.com/22286696/54349542-967c8c80-469f-11e9-91a6-1257ab622072.png">

**Comment by randomeizer** [comment]
The code values for each colour aspect range between 0.0 and 1.0 (a percentage, basically). To convert it, you multiply by the maximum allowed value in the target range (255 in this case).

With regards to what should get displayed, maybe it should be the Hex version (#FFFFFF)? Otherwise you could end up with "255 255 255", which is 11 characters.

**Comment by latenitefilms** [comment]
Ummm... maybe you can't send back "text" to the Tangent anyway?

<img width="220" alt="Screen Shot 2019-03-14 at 10 20 17 pm" src="https://user-images.githubusercontent.com/22286696/54353132-6a650980-46a7-11e9-9b93-50e372870f56.png">

**Comment by latenitefilms** [comment]
Interestingly, when I do:

```lua
 :onGet(function() return 255255255 end)
```

The Tangent actually displays "255255248".

So either there's a bug in our Tangent code, or a bug in the Tangent API itself? Weird that its 7 off?

**Comment by latenitefilms** [comment]
Andy from Tangent writes:

> The above should mean that you don’t need to try and squeeze all 3 of the RGB values into one box, which is presumably what you were doing when you discovered that 255255255 apparently equals 255255248. We suspect that this is something to do with the value passed being a 32 bit float and what you’re seeing is due to float rounding.

**Comment by latenitefilms** [comment]
Andy writes:

> The float thing is an inherent flaw/feature in the way that floats work rather than a problem in your code. The value to be displayed which is passed through to the Tangent Hub is specified to be a 32-bit float in our API.
>  
> We’ve confirmed this now:
> A 32-bit integer can easily accommodate 255,255,255 However a 32-bit float can only be accurate for integers up to 16,777,217. There will be gaps in the sequence for numbers larger than this.
>  
> I guess that 255,255,255 must lie in one of those gaps! Hopefully, sending 3 separate values for R, G & B will bypass this issue.
>

**Comment by latenitefilms** [comment]
Solved in #1774
