### ISSUE TITLE
Fix clipboardWatcher() so it correctly labels clipboard items by name

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#17]

**Comment by latenitefilms** [comment]
@randomeizer - I wonder if it's better/quicker to use [hs.base64](http://www.hammerspoon.org/docs/hs.base64.html) rather than `openssl`? For what it's worth I did originally try to use `hs.base64` but I could never get it to work as intended for whatever reason.

**Comment by latenitefilms** [comment]
Ummm... I just tried using `hs.base64` again but still had no luck.

**Comment by randomeizer** [comment]
I thought of that too, but hs.base64 outputs a string, and it's actually a
binary plist. There might be a library out there somewhere that will output
the result as binary, but we would still need to send it to `plutil` to get
the XML version anyway.
