### ISSUE TITLE
Incorrect Handling of Multiple Screens

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1757]
When I have the Timeline on a Secondary Screen, `require("cp.apple.finalcutpro"):viewer():UI()` incorrectly returns the Timeline `AXGroup` instead of the viewer. This breaks the timecode text (as originally reported in issue #1572).

In this case I have my MacBook Pro screen on the left, LG 5K in the Centre, and Sony Reference monitor on the right.

However, if you remove the Sony Reference monitor, so that only two monitors are connected, the same issue happens. Basically, if you put the "Timeline" on a secondary screen, it won't correctly return the viewer.

Screenshots of all three screens:

![Screen Shot 2019-03-27 at 3 00 34 pm (3)](https://user-images.githubusercontent.com/22286696/55049689-5a82f780-50a1-11e9-88bb-664eabd1fff9.png)
<img width="1680" alt="Screen Shot 2019-03-27 at 3 00 34 pm (2)" src="https://user-images.githubusercontent.com/22286696/55049690-5a82f780-50a1-11e9-8da4-3f2855364d1c.png">
<img width="2560" alt="Screen Shot 2019-03-27 at 3 00 34 pm" src="https://user-images.githubusercontent.com/22286696/55049717-7a1a2000-50a1-11e9-80a7-e83df47be6f3.png">

**Comment by latenitefilms** [comment]
As part of this issue we should also make sure all the AX cache's have a `matcher` function.

**Comment by randomeizer** [comment]
I believe this is now working in the #1757 branch.
