### ISSUE TITLE
Effects, Titles, Transitions, Generators Lists should be per Language

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#179]
We should have seperate Effects, Titles, Transitions and Generators Lists per language, so that if a user is constantly jumping between two Final Cut Pro languages, it doesn't break the HUD/Console/Shortcuts if the built-in Effects/Title/Transition/Generator name changes.

**Comment by randomeizer** [comment]
Yeah, I noticed the title changes. Are you suggesting the lists are
completely independent? Or that we should try to figure out what the new
name is?

**Comment by latenitefilms** [comment]
In the short term, I think we just make the lists completely independent as that's way easier, and I'm sure the amount of users switching FCPX languages is VERY low.

Otherwise it will just become WAY too complex, as 3rd party effects can translate the languages anyway they want.

**Comment by randomeizer** [comment]
Yeah, very tricky
