### ISSUE TITLE
hs.drawing objects don't appear on top of full screen windows when dock icon displayed

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#182]
For example, "Highlight Browser Playhead" doesn't work when Final Cut Pro is in full-screen mode, but doesn't generate any errors - so maybe `hs.drawing` can't work "over the top" of full screen windows?

**Comment by randomeizer** [comment]
It may be related to the layer height of the `drawing` windows. The full
screen window is probably set to a higher window than the default for drawn
shapes.

Is the full screen window on top of your main FCPX window, or on a separate
screen?

**Comment by latenitefilms** [comment]
I've submitted a Hammerspoon [issue](https://github.com/Hammerspoon/hammerspoon/issues/1184).
