### ISSUE TITLE
Tangent Color Board Controls fail in Polish

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1873]
Tomasz reports:

> Hello
> I have another problem now. In fcpx, I have mapped the controller for the color board. Unfortunately, it's not work good. Turning the balls, the values (angle, percentage) change but the colors do not change. By turning the knobs that should change the saturation and the exposures of values do not change. When the color values (angle, percentage) or the saturation or the exposures are changed manually with the mouse, attempting to change them with the panel ends with their resetting. I am sending a link https://youtu.be/XF9-9rq7toU for short video illustrating the panel's activities and xml with map.
> How to fix it?
> Tomasz

> Hi Chris
> I do:
> I deleted all previous FCPX version.
> I uninstalled and reinstalled both Tangen Hub and Command Post. 
> I reset FCPX preferences.
> The problem did not go away :((
> Default map supplied with Command Post work but only at Color Wheel.
> If i modify default map for example by adding Color Board exposure mapping to free knobs it does not work. Color Wheel works and Color Board does not work.

> Hi Chris
> Maybe this will help solve the problem.
> The answer to the first question. Yes. only  color board does'n work correctly.
> The answer to the second question. Yes but not exactly.
> Colour board UI values reset even if they are previously changed with the mouse. Just like in this video: https://youtu.be/bzPIOlxi9Bs
> For saturation and exposure the values indicated on the display are: 0 number or 50% or half of bar.
> I am asking for help. If it's a plug in problem, I'll delete it.
> Tomasz

[TangentDiagnostics-2019-06-03T143320.txt](https://github.com/CommandPost/CommandPost/files/3255762/TangentDiagnostics-2019-06-03T143320.txt)
[panel map test.xml.txt](https://github.com/CommandPost/CommandPost/files/3255763/panel.map.test.xml.txt)

**Comment by latenitefilms** [comment]
Tomasz reports:

> Chris, you're great !!!
> It works.
> The critical setting is: Numbers Separator Decimal
> It should be a dot instead of a comma.

![Zrzut ekranu 2019-06-6 o 01 54 06](https://user-images.githubusercontent.com/22286696/58998080-71349000-8842-11e9-922a-ab52684cc07b.png)

**Comment by randomeizer** [comment]
Ah, ok. Makes sense I guess. Can we access the system number format anywhere?

**Comment by latenitefilms** [comment]
Yeah, we already have:

```lua
--- cp.tools.toRegionalNumber(value) -> number | nil
--- Function
--- Takes a string and converts it into a number, with the correct
--- regional decimal separator.
---
--- Parameters:
---  * value - The value you want to process as a string.
---
--- Returns:
---  * The value as a number or `nil`.
function tools.toRegionalNumber(value)
    if type(value) == "string" then
        if locale.details().decimalSeparator == "," then
            value = value:gsub(",", ".")
        end
    end
    value = tonumber(value)
    return value
end

--- cp.tools.toRegionalNumberString(value) -> string | nil
--- Function
--- Takes a number and converts it into a string, with the correct
--- regional decimal separator.
---
--- Parameters:
---  * value - The value you want to process as a number.
---
--- Returns:
---  * The value as a number or `nil`.
function tools.toRegionalNumberString(value)
    if type(value) == "number" then
        value = tostring(value)
        if locale.details().decimalSeparator == "," then
            value = value:gsub("%.", ",")
        end
    end
    return tostring(value)
end
```

So, I'm not really sure why this isn't working correctly for Polish. Will have to do some testing.

**Comment by latenitefilms** [comment]
Ummmm... when I change my system to Polish, CommandPost still works as expected:

<img width="862" alt="Zrzut ekranu 2019-06-6 o 11 21 13 AM" src="https://user-images.githubusercontent.com/22286696/59000533-4c461a00-884e-11e9-8f07-e5068c6efe7e.png">

Not sure what's going on...

**Comment by latenitefilms** [comment]
Tomasz reports:

> Hi
> I changed back to using a comma instead of a dot, restart CommandPost and Final Cut Pro. 
> Using a comma instead of a dot restores the problem.
> Screenshot:

![Zrzut ekranu 2019-06-6 o 12 44 38](https://user-images.githubusercontent.com/22286696/59030802-56dfce00-88a5-11e9-8143-e16110bc224a.png)

Doing some further testing, Tomasz reports:

> The problem occurs
> grouping dot decimal comma
> grouping comma decimal comma
> grouping space decimal comma
> grouping apostrophe decimal comma
> grouping nothing decimal comma
>  
> No problem
> grouping comma decimal dot
> grouping space decimal dot
> grouping apostrophe decimal dot
> grouping nothing decimal dot
>  
> can not be set
> grouping dot decimal dot

Very strange.

@randomeizer - Can you reproduce on your machine switching to Polish?

**Comment by latenitefilms** [comment]
Tomasz says:

> Hello Chris
> I checked the error with my friend. It is exactly like me. It helps to change a comma with a dot. He has macbookpro 2016 with osx 10.13.6, Polish language, (same in tangent and midi - kork nano control).
> Tomasz
