### ISSUE TITLE
Clicking on Project moves me to the home screen

### ISSUE THREAD

**Issue by ghost** [fcpxhacks/fcpxhacks#1917]
screen recording: https://drive.google.com/file/d/1lsML_JFF42zDVQj0E3o6tXWfWsPKBj5H/view?usp=sharing

**Comment by latenitefilms** [comment]
@lukerooneyio - Huh, that's weird. Does it only happen when CommandPost is runnning?

**Comment by ghost** [comment]
Yes, that’s correct.

**Comment by latenitefilms** [comment]
Very strange! The only thing I can suggest is completely uninstalling using the uninstall tool (it will delete all your settings and preferences) then reinstall the latest beta. If it happens again, hopefully we can work out which CommandPost plugin is causing this weird behaviour.

**Comment by latenitefilms** [comment]
As we haven't heard from you in a while @lukerooneyio - I'm going to assume this issue has been solved somewhere along the lines? If not, please feel free to re-open this issue.

**Comment by ghost** [comment]
I believe it was fixed. Thank You
