### ISSUE TITLE
The options available in Touch Bar menu aren't the same in the Shortcuts menu

### ISSUE THREAD

**Issue by ghost** [fcpxhacks/fcpxhacks#1918]
touch bar menu: ![Screen Shot 2019-07-18 at 6 08 43 PM](https://user-images.githubusercontent.com/53066184/61502112-539d2f00-a987-11e9-9b85-17d52eb5dba5.png)

shortcuts menu: ![Screen Shot 2019-07-18 at 6 08 58 PM](https://user-images.githubusercontent.com/53066184/61502119-5dbf2d80-a987-11e9-95f0-442b97575d4c.png)

to find the same options in the shortcuts menu, you have to scroll down and find them alphabetically... this is ass.

**Comment by latenitefilms** [comment]
You can use the Filter search at the top of the Shortcut panel:

<img width="1112" alt="Screen Shot 2019-07-19 at 11 41 36 am" src="https://user-images.githubusercontent.com/22286696/61503193-336a8000-aa1a-11e9-9704-2fbba1d4e5c5.png">

I do agree though, that it's a bit weird having two methods of assigning Final Cut Pro shortcuts.

**Comment by ghost** [comment]
whoops, didn’t see that! thanks

**Comment by latenitefilms** [comment]
I'm going to close this issue, as whilst I agree that having two methods of assigning Final Cut Pro shortcuts is weird - there is a suitable workaround (i.e. use the Filter textbox in the Shortcut Preferences). Eventually we should probably rewrite the Shortcuts Preferences panel to only use actions.
