### ISSUE TITLE
Multiple instances of Command Post in the menu bar

### ISSUE THREAD

**Issue by ghost** [fcpxhacks/fcpxhacks#1920]
and quitting one, quits both of them :(

**Comment by latenitefilms** [comment]
Ummm, this shouldn't happen. Does quitting and restarting fix the issue?

**Comment by ghost** [comment]
Yes, it happens every once in a while. I think it got confused after updating. I replaced the old version in my applications folder, but it still happens from time to time.

**Comment by latenitefilms** [comment]
Are you “restarting” CommandPost via the restart menu bar item?

**Comment by ghost** [comment]
I usually quit and reopen it from the applications menu because the restart button won’t work.

**Comment by latenitefilms** [comment]
Fixed in CommandPost-App.
