### ISSUE TITLE
Volume controls don't work when using comma as decimal seperator

### ISSUE THREAD

**Issue by franzvb** [fcpxhacks/fcpxhacks#1922]
When mapping the Tangent ripple wheel to Final Cut Pro - Audio Inspector - Volume - Volume or Volume (Automatic keyframes)  the value jumps to the maximum (lowest or highest depending o the direction the wheel is turned) and gets stuck there. (End of video)
When mapped to Pan everything works fine. (beginnig of video)

https://drive.google.com/open?id=1BNEGdsbc1NHdHAPpNwXIx-4UW1wrU3Mh

**Comment by latenitefilms** [comment]
Is this using the latest beta?

Does changing your decimal number separator in macOS system preferences to a dot (.) fix the issue?

<img width="780" alt="Screen Shot 2019-07-24 at 10 45 22 pm" src="https://user-images.githubusercontent.com/22286696/61794567-cbc29380-ae64-11e9-95e3-88706634bb42.png">

**Comment by franzvb** [comment]
Hey Chris
i am running beta 75 and changing from , to . did the trick. Thank you!

**Comment by latenitefilms** [comment]
@franzvb - Thanks for reporting. We'll try and fix this in a future beta. I thought we'd finally solved all the decimal bugs, but apparently not!

**Comment by latenitefilms** [comment]
I believe this has been fixed in a previous beta.
