### ISSUE TITLE
updateEffectsList() fails in French

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#196]
It looks like instead of the first item in the Effects Browser saying "All Audio & Video", when in French, it says "All" - which confuses how we detect for all video and all audio.

**Comment by randomeizer** [comment]
As in, it uses 'All' three times?

**Comment by latenitefilms** [comment]
Yep - seems so! What do you think the best way is to tackle this?

<img width="461" alt="screen shot 2017-01-10 at 11 35 52 pm" src="https://cloud.githubusercontent.com/assets/22286696/21806595/4a1ceace-d78e-11e6-8f8b-2f643c19f651.png">

**Comment by randomeizer** [comment]
Probably just do a check to see if it's two or three matches. If 3, use the
last two instead.
