### ISSUE TITLE
Dual Screen Support broken in hs.finalcutpro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#197]
It looks like when the match frame and highlight features were moved from Chris' crazy code to using the `hs.finalcutpro` API it's broken dual-screen support.

**Comment by randomeizer** [comment]
I'll take a look. Probably there is a bug in how it is finding the browser in that configuration.

What specifically is on the second screen when is not working as expected? The Viewer? The Browser? The Timeline?

**Comment by latenitefilms** [comment]
I don't have a second monitor with me - but I think I had the Browser on a second monitor.

**Comment by randomeizer** [comment]
This one is fixed (hopefully). Awaiting final review.
