### ISSUE TITLE
CommandPost fails to load on case-sensitive file systems

### ISSUE THREAD

**Issue by SKiD12** [fcpxhacks/fcpxhacks#2006]
Hi, I have very strange issue with CommandPost ver.78 to ver. 81 - everytime I try to run CommandPost from my hard drive (no matter in what folder the app is located) it crashes. The only way I can run the app is to execute it directly form the DMG image. Any ideas what might cause the issue? Thanks :)

**Comment by latenitefilms** [comment]
@SKiD12 - That is strange! When you say "crash" is it actually crashing in macOS? If so, can you share a crash log? Can you try running CommandPost from the DMG and copy and paste the contents of the Debug Console here so we can have a look? I can't say we've ever come across this issue before!

**Comment by SKiD12** [comment]
@latenitefilms Yes, it crashes completely.
Here is the debug log, although last time there was more issues with "slow" plugins:
CommandPost v1.0.0-beta.81 (Build: 5629)

Build Date:                     Sep 26 2019, 00:24:22
macOS Version:                  10.14.6
CommandPost Locale:             en_CZ
Current Keyboard Layout:        Czech - QWERTY
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.4.6
Final Cut Pro Language:         en
Developer Mode:                 false

2019-09-25 23:34:16: 2019-09-25 23:34:12: -- Loading /Volumes/CommandPost/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2019-09-25 23:34:12: -- Loading extension: uielement
2019-09-25 23:34:16: 23:34:16         cp:     Loading Plugins...
2019-09-25 23:34:24: 23:34:24 ** Warning:   plugins: Slow Plugin: finalcutpro.setup.scan (2.556699)
2019-09-25 23:34:25: 23:34:25         cp:     Plugins Loaded.
2019-09-25 23:34:25:                          Startup Time: 4.717702 seconds
2019-09-25 23:34:25: -- Done.

**Comment by SKiD12** [comment]
![Screenshot_2019-09-25 23 40 31_Fup71y](https://user-images.githubusercontent.com/16972173/65641810-045e2500-dfee-11e9-9141-4f881cfa5bb3.png)

**Comment by SKiD12** [comment]
I also sent bug report

**Comment by latenitefilms** [comment]
Ummm.... so weird. Can you try this:

1. Right click on the CommandPost application and click "Show Package Contents"
2. Go to "Contents > Resources > extensions > hs > _coresetup"
3. Open `init.lua` in a plain text editor (such as BBEdit)
4. Change the line that says `if not hs._cpLoaded then` to `if fake == true then`

This will stop CommandPost from forcing you to quit. Can you send send us feedback after this, so we can see WHY it's not loading correctly?

**Comment by SKiD12** [comment]
Something is wrong with the syntax (I don't have any experience with lua scripting) 
`error loading module 'hs._coresetup' from file '/Applications/CommandPost.app/Contents/Resources/extensions/hs/_coresetup/init.lua':
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:98: 'then' expected near '='`

**Comment by latenitefilms** [comment]
Sorry, I meant: `if fake == true`

**Comment by latenitefilms** [comment]
Sorry, I meant: `if fake == true then`

**Comment by SKiD12** [comment]
Well after executing I get again the same Oops! window but now without the debug console. The app is running in the background without any window or icon in the tray

**Comment by latenitefilms** [comment]
Can you click on the dock icon to open the debug console? If so, can you enter the below and share what it returns?

```lua
print(hs.settings.get("MJConfigFile")); print(hs._cpLoaded); print(hs.inspect(hs.processInfo))
```

Also, have you tried running the Uninstall tool first?

**Comment by latenitefilms** [comment]
Can you CMD+TAB into CommandPost and open the Debug Console from the menubar?

**Comment by SKiD12** [comment]
Unofrtunately not. After the edit there is no dock icon and when I Cmd+Tab to CommandPost, nothing happens

**Comment by latenitefilms** [comment]
Ok, try undoing that original change, and change `if settings.get("MJConfigFile") ~= nil then` to `if true == true then`

**Comment by latenitefilms** [comment]
Also, try running this in Terminal and tell me what it says:

`defaults read org.latenitefilms.CommandPost MJConfigFile`

**Comment by SKiD12** [comment]
after the 2nd edit I get just error message without dock icon:
`2019-09-26 00:16:04: -- Loading /Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2019-09-26 00:16:04: -- Loading extension: uielement
2019-09-26 00:16:05: *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: module 'cp.ui.element' not found:
	no field package.preload['cp.ui.element']
	no file '/Users/skid/Library/Application Support/CommandPost/Extensions/cp/ui/element.lua'
	no file '/Users/skid/Library/Application Support/CommandPost/Extensions/cp/ui/element/init.lua'
	no file '/Applications/CommandPost.app/Contents/Resources/extensions/cp/ui/element.lua'
	no file '/Applications/CommandPost.app/Contents/Resources/extensions/cp/ui/element/init.lua'
	no file '/Users/skid/Library/Application Support/CommandPost/Extensions/cp/ui/element.so'
	no file '/Applications/CommandPost.app/Contents/Resources/extensions/cp/ui/element.so'
	no file '/Users/skid/Library/Application Support/CommandPost/Extensions/cp.so'
	no file '/Applications/CommandPost.app/Contents/Resources/extensions/cp.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...t.app/Contents/Resources/extensions/cp/ui/StaticText.lua:9: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...ndPost.app/Contents/Resources/extensions/cp/ui/Table.lua:15: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...tensions/cp/apple/finalcutpro/main/GeneratorsBrowser.lua:18: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...sources/extensions/cp/apple/finalcutpro/main/Browser.lua:14: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...tents/Resources/extensions/cp/apple/finalcutpro/init.lua:89: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:682: in function 'require'
	...ommandPost.app/Contents/Resources/extensions/cp/init.lua:23: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:784: in function 'hs._coresetup.setup'
	(...tail calls...)`

**Comment by SKiD12** [comment]
The terminal command returns:
`2019-09-26 00:18:12.642 defaults[6415:1933329] 
The domain/default pair of (org.latenitefilms.CommandPost, MJConfigFile) does not exist`

**Comment by latenitefilms** [comment]
Ummmm, do you have a case sensitive file system by any chance?

Try changing:

```lua
local Element               = require("cp.ui.element")
```

to:

```lua
local Element               = require("cp.ui.Element")
```

...in  "Contents > Resources > extensions > cp > ui > StaticText.lua"

**Comment by SKiD12** [comment]
Well, now it runs OK! But it is trying every time during startup to open DMG file 🤪
It displays license popup window of version 0.78(!!!) everytime I try to run the app. When I click Disagree, CommandPost is in the Dock and tray, but in a while it becomes unresponsive. After another while it became active, but when I tried to open Preferences, the license popup of ver. 078 appears once again and keeps popping up even when I click Disagree. Very strange 🧐

**Comment by latenitefilms** [comment]
@SKiD12 - We've been able to reproduce here, it was definitely the fact you're running a case-sensitive file system that was causing the issue - thanks heaps for problem solving with us! We'll push out a new public release shortly, which will hopefully resolve your issue. I'd suggest running the uninstall tool first, before installing the latest beta.

**Comment by latenitefilms** [comment]
@SKiD12 - This should be fixed in Beta 82. Let me know if you're still having issues.

**Comment by SKiD12** [comment]
I just updated to 0.82 and so far it is ok. Thank you very much, Chris :)
Best,

Pavel


čt 26. 9. 2019 v 8:41 odesílatel Chris Hocking <notifications@github.com>
napsal:
