### ISSUE TITLE
Add hs.finalcutpro:browser:isPlaying()

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#202]
It would be great to have a function in `hs.finalcutpro` that tells you if the user is currently playing something in the browser. I guess the only way to do this is to track the browser playhead position?

**Comment by randomeizer** [comment]
I liked into this pretty hard when working on Scrolling Timeline/Playhead
Lock. We can create a watcher to try and determine if the playhead is
moving, but it's difficult to determine if it's just the mouse clicking
around or if it's playing. I had something which would take a guess, but it
wasn't too reliable and used a fair bit of CPU...

**Comment by latenitefilms** [comment]
Ah, right - no worries!

It's annoying that Apple don't just change the menubar item from "Play" to "Stop"!

**Comment by randomeizer** [comment]
Yeah, I know. And the play button doesn't change either...

**Comment by latenitefilms** [comment]
Although it does change appearance - so there might be a way to detect that?

Maybe using a similar technique to [Interface Inspector](https://www.interface-inspector.com/)?

**Comment by randomeizer** [comment]
Cool app! I have no idea how they do their magic though. I'm guessing that
it involves the .nib files, although the fact that they can actually modify
properties live indicates there's something else going on too...

**Comment by randomeizer** [comment]
Related to #64
