### ISSUE TITLE
Lots of lag with play/pause, other MIDI actions

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2043]
Having a lot of lag with beta 84 with MIDI actions that I wasn't having previously. Most notably Play/Pause, Enable/Disable, and definitely any actions I'm pressing while playing a clip (even play/pause). They all lag at various times. Not sure if it's the current beta or something else. I've closed FCPX, the midi controller app, CP without a fix.

**Comment by randomeizer** [comment]
Not good! We’ll look into it.

In the meantime, have you tried reverting to the previous beta? You should be able to download it here:

https://github.com/CommandPost/CommandPost/releases

**Comment by pvanleer** [comment]
Just checked it out, no bueno. Same lag is happening unfortunately. Please let me know how else I can help in fixing this. Pretty hard to use with the lag, unfortunately :/

**Comment by latenitefilms** [comment]
@pvanleer - Can you please submit feedback via the menubar so that we can have a look at your error logs (or paste the contents of your Debug Console here)?

Can you recently updated to macOS Catalina or FCPX 10.4.7?

Do you remember which Beta you were on before updating to Beta 84?

What MIDI hardware are you using?

**Comment by pvanleer** [comment]
Hey Chris, I just submitted the feedback/error logs! 

I haven’t updated to Catalina yet, still running 10.14.6 as I’m waiting for some other programs I rely on to update. I did, however, update FCPX the other day. Unfortunately, I don’t know if the two are correlated timing wise as I edited last week (don’t recall if I was having lag issues then :/), then was out of town, then updated FCPX, then started editing again this week and noticed the issues. I was on BETA 83 before this which seemed to work well, minus not being able to switch my custom workspaces.

I’m on the Traktor Kontrol X1 :) 

Thanks,
Prescott

**Comment by latenitefilms** [comment]
Ummm... well, nothing major really changed from Beta 83 to Beta 84 that should affect MIDI performance. Also, as far as I can tell, nothing really changed much in FCPX from 10.4.6 to 10.4.7.

Can you try rolling back to Beta 83 and see if that fixes anything?

Do you still have 10.4.6 on your machine? Can you try running that and seeing if there's any difference?

Is every MIDI action laggy now - or just specific ones?

For completeness, here's the Debug Console contents:

```lua
CommandPost v1.0.0-beta.84 (Build: 5635)

Build Date:                     Oct  2 2019, 00:45:40
macOS Version:                  10.14.6
CommandPost Locale:             en
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.4.7
Final Cut Pro Language:         en
Developer Mode:                 false

2019-10-10 09:42:42: 2019-10-10 09:42:41: -- Loading /Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2019-10-10 09:42:41: -- Loading extension: uielement
2019-10-10 09:42:42: 09:42:42         cp:     Loading Plugins...
2019-10-10 09:42:44: 09:42:44 ** Warning:   plugins: Slow Plugin: finalcutpro.setup.scan (0.145026)
2019-10-10 09:42:44: 09:42:44 ** Warning:   plugins: Slow Plugin (Post): finalcutpro.midi.manager (0.152124)
2019-10-10 09:42:44:                  cp:     Plugins Loaded.
2019-10-10 09:42:44:                          Startup Time: 1.975266 seconds
2019-10-10 09:42:44: -- Done.
2019-10-10 10:36:00: ********
2019-10-10 10:36:00: 10:36:00 ERROR:colorInspe: Corrections Bar activation failed due to menu button timing out.
2019-10-10 10:36:00: ********
2019-10-10 22:10:18: ********
2019-10-10 22:10:18: 22:10:18 ERROR:   LuaSkin: hs.timer callback error: .../CommandPost.app/Contents/Resources/extensions/cp/rx.lua:179: Menu Item Disabled: Up (+1 dB)
stack traceback:
	[C]: in function 'error'
	.../CommandPost.app/Contents/Resources/extensions/cp/rx.lua:179: in field '?'
	.../CommandPost.app/Contents/Resources/extensions/cp/rx.lua:1158: in function <.../CommandPost.app/Contents/Resources/extensions/cp/rx.lua:1157>
2019-10-10 22:10:18: ********
```

**Comment by latenitefilms** [comment]
Are you still having issues @pvanleer?

**Comment by latenitefilms** [comment]
I'm going to close this for now as we haven't heard back, and I can't replicate here.

Feel free to re-open @pvanleer if you're still having issues.
