### ISSUE TITLE
Batch Export from Timeline not working

### ISSUE THREAD

**Issue by Saltiola7** [fcpxhacks/fcpxhacks#2046]
![Screenshot 2019-10-17 at 8 22 11](https://user-images.githubusercontent.com/13892355/66979857-afc33c80-f0b7-11e9-9f72-cfd27fcdcda9.jpg)

I re installed and resetted my computer and its still not working. Everytime different bug though. Now its saying that "Unable to show the Export Dialog, which has aborted the Batch Export.
Please try again."
When Im trying to batch export clips from timeline.

I rely on that feature for exporting Stock Footage Clips.

**Comment by latenitefilms** [comment]
Ummm, we'll do some testing and see if we can reproduce. Stay tuned.

**Comment by latenitefilms** [comment]
@tommisaltiola - Give Beta 86 a shot and let us know if you're still having issues. Fingers crossed!
