### ISSUE TITLE
Batch Export from Timeline Failed

### ISSUE THREAD

**Issue by Saltiola7** [fcpxhacks/fcpxhacks#2049]
I tried batch export from timeline with beta 86 and I have an issue that I have had before (Not my last issue, but happened before that)
It get to the export screen and naming of the file and then starts to count numbers in the end of the name like crazy and doesnt go anywhere. There is a GIF showing whats happening
![Oct-17-2019 16-40-55](https://user-images.githubusercontent.com/13892355/67014104-ea9b9380-f0fc-11e9-9397-1afec293d212.gif)

**Comment by latenitefilms** [comment]
Ah, ok - I’m not sure we’ve allowed for a “collapsed” save window. Try expanding it so you can see all the other files in the folder, etc and try again. We’ll address this properly in a future beta.

**Comment by latenitefilms** [comment]
Actually, no, ignore my last menu, I just tested with a "collapsed" save window and it worked fine on my machine. Are you able to share a higher quality screen recording, and include the Batch Export screen so we can see your settings? Have you selected "Use Custom Filename"? What about "Replace Existing Files"?

**Comment by latenitefilms** [comment]
I think #2050 should solve this.
