### ISSUE TITLE
Add to Shared Clipboard with Custom Label

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#205]
Currently when the Shared Clipboard is enabled, whenever you copy something within Final Cut Pro it's automatically added to the Shared Clipboard, and named using the `clipboard.findClipName()` function - however it could be handy if you could customise this name (for the purposes of the shared clipboard).

**Comment by randomeizer** [comment]
At what point would the user provide the custom label?

**Comment by latenitefilms** [comment]
We would basically add a new shortcut key called "Copy with Label". When the user presses the shortcut, it will prompt for a label (using a dialog box), then if the user has entered a valid label, we'll then save this label to a global variable (for later use in the clipboard module), then trigger the copy command in Final Cut Pro.

I'll try add this later today if I get a chance.

**Comment by randomeizer** [comment]
You could just pass it onto the clipboard function. Better than a global
variable.

Shared clipboard should probably move into the clipboard module too, to be
honest.

**Comment by latenitefilms** [comment]
> You could just pass it onto the clipboard function. Better than a global variable.

Good idea.

> Shared clipboard should probably move into the clipboard module too, to be honest.

The "saving" part already is. But yes, eventually we should move all the clipboard related stuff into there. However, I feel like it's probably better to do this when we eventually implement #136.
