### ISSUE TITLE
Add way to access menubar items for any application via the Search Console

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2067]
Related:

https://github.com/Hammerspoon/Spoons/blob/master/Source/KSheet.spoon/init.lua
https://github.com/mattorb/dotfiles/blob/master/hammerspoon/menusearch.lua

**Comment by randomeizer** [comment]
Basically, we should modify MenuAction so that it only provides the menu options for the currently active app, whatever that may be.

**Comment by latenitefilms** [comment]
Note to self, `hs.application:getMenuItems([fn])` offers a callback function so that it's non-blocking.
