### ISSUE TITLE
Multicam Clips Labelled incorrectly in Clipboard History

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#207]
See:

<img width="1036" alt="screen shot 2017-01-14 at 5 33 32 pm" src="https://cloud.githubusercontent.com/assets/22286696/21952974/a9f373ca-da7f-11e6-801b-b5f9fb9f0db1.png">

**Comment by randomeizer** [comment]
Hmm, odd. That text is coming from somewhere - I don't generate an 'Untitled Multicam Clip' text value. Are you certain the multicam clip itself isn't called 'Untitled Multicam Clip' in the browser?

**Comment by latenitefilms** [comment]
**Reveal is Browser** on the clip goes back to a multi-cam clip called "Chris Multicam". Selecting the clip on the timeline then clicking **Open in Angle Editor** also shows that the clip is called "Chris Multicam". However, interestingly adding a new instance of the clip from the Browser to the Timeline then copying gives the label of "Chris Multicam (+1)". Maybe the clip was originally called "Untitled Multicam Clip" at some point and I renamed it? Not sure.

**Comment by randomeizer** [comment]
Weird.

**Comment by latenitefilms** [comment]
I'm just going to close this issue for now, and we can re-evaluate if it comes up again in the future. Not really a deal-breaker.
