### ISSUE TITLE
My shortcut is giving me the wrong title

### ISSUE THREAD

**Issue by GregL111** [fcpxhacks/fcpxhacks#2096]
I set up a shortcut to open a custom title on the timeline, the short cut is Option + C. It worked for the first couple of weeks, but now every time I do option + C it opens up one of my pan right titles. I don't have a shortcut for this pan right title, I also deleted my shortcut for the custom title and tried a different shortcut but whatever I try it just opens up pan right. All my other shortcuts are fine except for this custom title one which is very frustrating.

**Comment by latenitefilms** [comment]
Try pressing the “Clear Cache” button in the Final Cut Pro panel in CommandPost’s preferences.

**Comment by latenitefilms** [comment]
Solved on [Facebook](https://www.facebook.com/groups/commandpost/permalink/2409615489294148/?comment_id=2409722402616790&reply_comment_id=2409723699283327).
