### ISSUE TITLE
selectedClipsUI() fails to get clip if it's in a secondary storyline group

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2100]
`fcp:timeline():contents():selectedClipsUI()` returns `nil` when this single clip is selected:

<img width="509" alt="Screen Shot 2019-11-04 at 12 01 19 am" src="https://user-images.githubusercontent.com/22286696/68085559-43598300-fe96-11e9-8876-f5daf1df0447.png">

**Comment by latenitefilms** [comment]
`selectedClipsUI` uses `attributeValue("AXSelectedChildren")` to get the list of selected AX objects, but it's not getting any.

UI Browser is also freaking out when selecting `AXGroup`'s in the timeline:

<img width="1537" alt="Screen Shot 2019-11-04 at 12 28 00 am" src="https://user-images.githubusercontent.com/22286696/68085953-b4029e80-fe9a-11e9-878f-1bfdb9d20684.png">

**Comment by randomeizer** [comment]
If we can confirm this is an issue, I guess we escalate it to Apple and cross our fingers...

**Comment by latenitefilms** [comment]
Seems to be working fine after changes in #2528.
