### ISSUE TITLE
Next/Previous Frame with Muted Audio Issue

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2163]
This feature is great, however it seems to mute the audio output for the whole computer, not just FCPX. When scrubbing next/previous frames, Spotify (how I noticed it) mutes as well. I'd prefer it to just be within FCPX.

**Comment by latenitefilms** [comment]
Unfortunately there's no way for CommandPost to control the audio volumes of individual application without doing something like [this](https://github.com/kyleneideck/BackgroundMusic) - which involves installing a custom sound output device, and is something we don't really want to do with CommandPost as it just complicates things.

If [this issue](https://github.com/kyleneideck/BackgroundMusic/issues/209) ever gets resolved, we may look at adding a custom action for using Background Music to do this.

**Comment by pvanleer** [comment]
I'm thinking you misunderstood my initial issue. Just to clarify, the "Next/Previous Frame with Muted Audio" action isn't muting the timeline clips within FCPX when activated, but muting the computer system-wide. I had something playing in Spotify while I was going through footage in FCPX and when I used the "with Muted Audio" actions, it muted Spotify as well as FCPX.

**Comment by latenitefilms** [comment]
Understood - this is by design. The only way we could implement this feature is muting the volume system-wide - there's no native way of muting specific applications on macOS.

**Comment by pvanleer** [comment]
Oh, got it! Thank _you_ for clarifying!
