### ISSUE TITLE
effectsShortcut() and transitionsShortcut() sometimes fail to apply effect/transition

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#223]
When adding an effect or transition from the Console, sometimes the effect doesn't actually apply.

Possibly related to the "mouse bug in Sierra"?

**Comment by latenitefilms** [comment]
@randomeizer - Just tested #223. If I choose an effect via the Console with the Effects Browser closed, it adds the effect fine, but it doesn't actually close the Effects Browser afterwards. Nor does it clear the search result.

Adding...

```lua
		timer.waitUntil(
			function() effects:itemIsSelected(effect) end,
			function()
				print("test")
				showTouchbar()
				effects:loadLayout(effectsLayout)
				if transitionsLayout then
					print("has transitionsLayout")
					transitions:loadLayout(transitionsLayout)
				end
				if not effectsShowing then
					print("hide effects")
					effects:hide()
				end
			end,
			0.001
		)
```

...tells me that `effects:itemIsSelected(effect)` is never actually turning true on my machine?

**Comment by randomeizer** [comment]
Hmm. And that timer is probably just spinning off into infinty as well, which is not ideal.

We should add a 'timeout' check regardless, but will have to try and figure out why the check is not working. The idea is that it waits until targeted item is selected (aka, was clicked), and then does the hiding/etc to reset everything.

**Comment by latenitefilms** [comment]
It looks like it's the old problem of `tools.ninjaDoubleClick()` not actually triggering when we want it to.

If I go back to using `timer.doAfter(0.1)` it seems to work every time on my machine, so it's still just a timing issue.

As discussed before, I think `hs.eventtap` just causes timing chaos. Hopefully [this](https://github.com/asmagill/hammerspoon_asm/tree/master/event) will eventually fix the issue.

**Comment by randomeizer** [comment]
So it needs a longer wait time?

**Comment by latenitefilms** [comment]
`timer.doAfter(0.1)` is what I originally had before we API-ified it, and it always seemed to work fine. In develop it's currently `0.000001`, which works MOST of the time on my laptop, but not EVERY time.

We can probably make it shorter than 0.1, but it would be purely a guess.

Ideally, it would be great to use something like `just.doUntil()`, so we don't have to put in an arbitrary wait period, but having the `tools.ninjaDoubleClick()` just seems to break things - at least on Sierra.

We could try using something like [MouseTools](http://www.hamsoftengineering.com/codeSharing/MouseTools/MouseTools.html) to get around things, but I would prefer not to have to bundle an executable file with FCPX Hacks if we can avoid it.

I reckon maybe we just live with the arbitrary 0.1 delay for now, and see what happens with the new `hs.eventtap` if/when it eventually comes out?

Unless you can come up with something clever?

I wonder if there's a way to "trigger" a double click action without having to simulate the mouse?

[Python](http://stackoverflow.com/questions/38766699/applescript-click-at-mouse-position)?

Thoughts?

**Comment by randomeizer** [comment]
Yeah, I don't know. 0.1 is a guess really, it's just a safer one.

`just.doUntil` doesn't work because it basically keeps Hammerspoon busy and (on Sierra) will not allow the mouse click to actually happen. Whereas using `timer` functions basically shunt off the remaining actions until some time later, so the mouse click will happen.

Hopefully the Hammerspoon guys can figure out a better solution. Thankfully there aren't too many things which require a mouse operation these days...

If it's working for now, let's just leave it as is.
