### ISSUE TITLE
Draggable guidelines only match default work space viewer window size & position

### ISSUE THREAD

**Issue by AndrewBrinsmead** [fcpxhacks/fcpxhacks#2237]
The draggable guidelines will only match up with the viewer screen correctly in the default workspace for FCPx; if I change back to my modified two screen workspace (or adjust the viewer frame size), then the guidelines don't adjust to match the viewer frame size & position; instead the guidelines stay at the default frame size, superimposed over the rest of the frame.

**Comment by latenitefilms** [comment]
It's possible you have a layout we haven't accounted for, although there's also a FCPX bug that causes Custom Workspaces to not work correctly if you create them in an earlier version of FCPX and use them on the latest version.

Try re-creating the custom layout and see if you're having the same issue. If you are, please post a screenshot of your setup and we'll try and reproduce, then fix.

**Comment by latenitefilms** [comment]
Ummm, it seems the overlay isn't updating when the Viewer is resized - something must have broken somewhere along the lines. Will investigate.
