### ISSUE TITLE
CP licence agreement keeps appearing

### ISSUE THREAD

**Issue by AndrewBrinsmead** [fcpxhacks/fcpxhacks#2245]
hi Chris, I've noticed that every time I reboot my Mac (and at other times), CP keeps asking me to agree to your licensing conditions.  I'm not sure why; I've already agreed to the terms a few times now, but it keeps reappearing.

**Comment by latenitefilms** [comment]
It must be trying to remount the package on boot. Try deleting the DMG file from your system.

**Comment by AndrewBrinsmead** [comment]
Thanks, I’ll give that a go!

**Comment by latenitefilms** [comment]
@AndrewBrinsmead - I'm going to assume you solved this, and am closing this issue. Feel free to re-open it if needed.

**Comment by AndrewBrinsmead** [comment]
Yup, your suggestion of deleting the DMG file from my downloads fixed the problem!
