### ISSUE TITLE
Test Tangent ApplicationDefinition API

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2257]
Andy writes:

> Your suggestion of changing the task with which Command Post is associated, whenever necessary, sounds like the best plan. The [latest Beta of the Hub](https://www.tangentwave.co.uk/wp-content/uploads/2020/02/TangentHub-Installer-1.5.6-BETA.pkg) already includes support for this, with a new, optional field (taskStr) passed in the ApplicationDefinition command. The Auto Switching function of the Hub should then switch control to Command Post on receipt of a new `taskStr`, whenever that task has focus.
>  
> Before sending `taskStr`, Command Post needs to Check the `protocolRev` value which is received in the `InitiateComms` command. If `protocolRev` is 7 or greater then the `taskStr` can optionally be passed in the `ApplicationDefinition` command.
>  
> We’ll be amending our documentation to add the 2 new Focus commands and the `taskStr` value shortly. For now though, here’s an extract :
> (New text in bold)
> ApplicationDefinition (0x81)
> ·         This is sent in response to the InitiateComms (0x01) command and establishes communication between the application and the hub.
> ·         Sends the application type and some file directory details to the hub.
> ·         If your application manages multiple user settings internally then this command should also be sent each time the user changes. This will notify the Hub to reload the preference files for the new user.
>  
> Format:                      0x81, <appStrLen>, < appStr>, <sysDirStrLen>, <sysDirStr>, <userDirStrLen>, <userDirStr>, **<taskStrLen>, <taskStr>**  
>  
> appStrLen                 The length of appStr
> The maximum length allowed is 256 bytes.
> Data type:                 Unsigned Int
>  
> appStr                        A string containing the name of the application. Note that this string is used to identify the application to the hub so it is crucial that the string remains constant throughout the lifetime of the application. The string must not include version numbers or similar additional information as this would mean that it changes from one release to the next.
> Data type:                 Character String
>                                      
>  
> sysDirStrLen             The length of sysDirStr
> The maximum length allowed is 1024 bytes.
> Data type:                 Unsigned Int
>  
> sysDirStr                    A string containing the absolute path of the directory that contains the Controls and Default Map XML files.
> This directory will typically within the directory in which the application is installed.
> By default this should always be set as we strongly recommend that applications ship with these XML files included in the distribution.
> To enable Unmanaged Mode (See Section 5) sysDirStrLen should be set to 0 and no sysDirStr sent.
> Data type:                 Path String.
>  
> usrDirStrLen             The length of usrDirStr
> The maximum length allowed is 1024 bytes.
> Data type:                 Unsigned Int
>  
> usrDirStr                    A string containing the absolute path of the directory that contains the User’s Default Map XML files.
> The directory will typically be within user space and the directory that contains application user data.
> This option is included for applications that manage several user preferences internally. It will not normally be required so usrDirStrLen will usually be set to 0. In this scenario the default user directory for the Wave Mapper utility will be used.
> Data type:                 Path String
>  
> **taskStrLen                The length of taskStr**
> **The maximum length allowed is 1024 bytes.**
> **Data type:                 Unsigned Int**
> **Protocol Rev:           Only available from revision 7 onwards.** 
> **The protocolRev value which is received in the InitiateComms command must be checked before sending this parameter.**
>  
> **taskStr                       A string containing the name of the task associated with the application. This is used to assist with automatic switching of panels when your application gains mouse focus on the GUI.**
> **This parameter should only be required if the string passed in appStr does not match the Task name that the OS identifies as your application. Typically, this is only usually required for Plugins which run within a parent Host application. Under these circumstances it is the name of the Host Application’s Task which should be passed.**
> **Any numerical characters included in taskStr will be stripped before matching.**
> **If taskStr is not required then taskStrLen should be set to 0.**
> **Data type:                 Character String**
> **Protocol Rev:           Only available from revision 7 onwards.** 
> **The protocolRev value which is received in the InitiateComms command must be checked before sending this parameter.**
>  
> If you get a chance, can you please check this build out to ensure that it does what you need when Command Post needs control of other applications. If it does then we’ll press ahead with adding in the 2 new Focus commands.

For reference, this is what I wrote previously:

> CommandPost aside, I think you plan works great for plugins within an application (i.e. ColorFinale2, Chromatic & Colorista all WITHIN Final Cut Pro).
>  
> CommandPost is obviously a different (and unusual beast), as we’re trying to do many things.
>  
> One possible solution would be to add an API that allows you to check if any applications have control (i.e. do any Tangent apps - such as ColorFinale2 - currently have focus in Final Cut Pro). That way, CommandPost can check if any plugins (i.e. ColorFinale2) or host apps (i.e. Final Cut Pro itself) have control, and if not, you could add another API command that allows CommandPost to forcefully take control. 
>  
> Essentially:
>  
> The Check Focus API call would have one argument for “Task String” (such as “Final Cut Pro”), which would either return “Host” (if FCPX has control of Tangent Hub) or “Plugin” (if a third party plugin has control over the Tangent Hub, such as ColorFinale2).
>  
> The Force Focus API would allow CommandPost to take control over Tangent Hub, ignoring the currently focussed app in macOS. If CommandPost triggered this, it would give CommandPost control, even if Final Cut Pro is active.
>  
> Bonus points for some kind of callback that’s triggered when the app focus changes - so that CommandPost could be notified when the focus changes (i.e. when ColorFinale2 triggers "Release Focus”).

**Comment by randomeizer** [comment]
Can you give a bullet-point list of the sequence of events/messages where this would be used exactly?

**Comment by latenitefilms** [comment]
Currently, `CommandPost.app` is what's associated with the CommandPost control map in Tangent Mapper/Hub, so if "Auto Switching" is enabled in Tangent Mapper, it only gives CommandPost control if `CommandPost.app` becomes the frontmost application.

What this new API addition allows is for us to tell Tangent Mapper to give us control whenever we want. So, for example, when FCPX get focus, we can tell Tangent Mapper to give us control without having to make CommandPost frontmost (or restart the Tangent Hub, which is what our current workaround is).

That's essentially the purpose of this specific GitHub issue - to test this very basic API.

Once we test it, and proves it works, then the next step is for Tangent to add some new "focus" API commands that developers like ColorFinale2 can implement. These "focus" API commands will essentially allow plugins like ColorFinale2 to tell Tangent Hub to take control as a higher priority than the host app (i.e. Final Cut Pro).

This is how Andy explained it to ColorFinale2:

> As you know, we’ve been working with Chris Hocking to find a solution to the panel focus switching issue. Currently he’s been working around the limitations of the Tangent Hub and you’ve obviously been assisting him with this. Many thanks.
>  
> We have however been considering various ways to create a seamless user experience when using plugins which support our panels with host applications which also support our panels. Not just for Color Finale 2 and Command Post but for all Plugins and Hosts. To enable this  we’d like to propose the following solution.
>  
> Ideally we would like the panel focus to follow the mouse focus on the GUI. This cannot be achieved for plugins by monitoring  the Task which has mouse focus as the same Task is reported for both the Host and the Plugin. Our alternative suggestion is for plugins to request focus from the Hub when it’s activated and then to return focus to the Host when it is dismissed. We’d achieve this by adding the following new commands to our API:
> 1.       Request Focus. Asks the Hub to switch the panel focus to the requesting Application (Plugin).
> 
> 2.       Release Focus. Return panel focus to the Host Application. (Or in your case Command Post)
> 
> 3.       Task String. To identify the task with which the Application (Plugin) should be associated with i.e. Final Cut Pro
>  
> CF2 would then send  the Command Request Focus when activated and Release Focus when it is dismissed.
> The Task String command allows the plugin to identify which Task it’s associated with, without the need for the user to do this manually. This command should only be sent once after initial connection is made to the Tangent Hub.
> The new Focus Commands will only function if the user has Auto-select Application enabled in the Mapper AND your plugin is associated with the Host Application’s task.
>  
> Please let me know if this sounds like a good approach. I know that you now want to add control of parameters which live in the Inspector rather than your own Window so this automatic focus switching may not be quite so helpful. An alternative/parallel solution could be to allow the user to map similar functionality to button presses, but that too has its limitations.
>  
> If you’d like to chat about this or if you have any ideas of your own how you’d prefer FCPX / CF2 support from Tangent to work then please just let me know.

Any questions let me know!
