### ISSUE TITLE
Make "Enable Shared Clipboard" option independent of "Enable Clipboard History"

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#226]
Currently **Enabled Shared Clipboard** is disabled if **Enable Clipboard History** is not already activated. These two functions should be independent of one-another.

**Comment by randomeizer** [comment]
This is not a small change exactly. Maybe should aim for 0.79? It honestly would be a good candidate for happening once we have plugins in develop.

**Comment by latenitefilms** [comment]
I don't think this should be too tricky to do. I'll have a proper look at it tonight and if it's easy enough I'll quickly bash it out, otherwise we can hold off until a future release.
