### ISSUE TITLE
Notifications don't display when triggered from the secondary display

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#228]
For example, try toggling the 'Enable Scrolling Timeline' option from the menu bar on the secondary display. Works fine on the primary display, nothing on secondary.

This may be a Hammerspoon issue, not sure.

**Comment by latenitefilms** [comment]
Seems to be working fine for me.

`hs.alert` defaults to putting the alert on `hs.screen.mainScreen()` (which corresponds to the screen with the currently focused window).

**Comment by randomeizer** [comment]
It's reliably not working for me whenever I'm focused on something on the
secondary window.

**Comment by latenitefilms** [comment]
Is it displaying on the other screen? Are you in full screen mode on either screen? Have you tried moving Final Cut Pro's main window onto your other screen (i.e. switching around the display which Final Cut Pro considers to be your "secondary" monitor)?

**Comment by randomeizer** [comment]
Test results:
* Single Window on primary display: visible in primary display
* Single Window on secondary display: not working
* Dual Windows: if focused on window in primary, visible in primary display
* Full Screen Single Window on primary display: not visible
* Full Screen Single Window on secondary display: visible in primary display

The same applies for clicking on a menu item:
* Clicking via the menu on the primary display: visible in primary display
* Clicking via the menu on the secondary display: not visible

**Comment by latenitefilms** [comment]
Do you have your second monitor on top of your primary monitor by any chance, or are they next to one another?

It looks like there's a bug in `hs.alert` - see: 
https://github.com/Hammerspoon/hammerspoon/issues/1196

We're currently using an unreleased version of `hs.alert` in develop, however, I tried using the "current" version and it also has the bug.

**Comment by randomeizer** [comment]
It's arranged to be on top.

**Comment by latenitefilms** [comment]
Try temporarily changing the display layout so that macOS things that they're side-by-side, and see if that fixes things? If it does, you could try fixing `hs.alert` yourself, or we could just wait until the Hammerspoon gurus get to it eventually. I had a quick look, but ran away scared pretty quickly.

**Comment by randomeizer** [comment]
I'll take a look later. Not a super-high priority at the moment.

**Comment by latenitefilms** [comment]
Fixed here:

https://github.com/Hammerspoon/hammerspoon/commit/6dda31fb35e712e1a4c7a8db6bf1407f301df2da
