### ISSUE TITLE
Add actions to "Press Top/Bottom Left/Right" on Loupedeck CT's Touch Wheel

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2280]
Nick writes:

> Hi Chris,
> 
> Apologies for e-mailing directly rather than through the app feedback form…
> 
> I’ve been using Commandpost with the Loupedeck CT and it’s been going pretty well - far better than with Loupedeck’s own software, so thanks for all the hard work you put into CommandPost and adding the CT to it.
> 
> As I’ll be losing the CT for a few days due to the key dropping off it & it having to be replaced by Loupedeck, I thought I’d better get on and send you the following….
> 
> I’ve a few things I’ve found that might be useful additions while using it and I’ve listed them below - basically a set of feature requests ;)
> 
> Loupedeck CT Feature Requests
> Ability to reset an individual control (to blank - action, icon, label)
> Ability to copy (or move) Bank Settings from one bank to another.
> Ability to copy control bank to another Application (for App version updates) eg Capture one 12 to Capture one 20.
> Add slide left/right action on top button screen - this could be used to move between control banks similar to the original Loupedeck software.
> Add slide up/down action on top button screen
> Add feature to set central dial screen to clock as per loupedeck default.
> expose bottom dial touch screen as mini trackpad/mouse input for finger slides? (eg to allow to use over selected colour wheels)
> division of wheel lcd into button zones similar to original LD CT  2/3/4/5 vert/horiz/diamond for single touch
> add ability to drag drop image to wheel rather than drop zone- same as for buttons.
> …and possible also for the small knobs?
> So far, I’ve not tripped over any more bugs for squishing, other than the text labels for the CT buttons can be very slow when typing in the text - seems the text is updating the image for the button after every keypress - not sure if that can be left until the user exits the field or clicks elsewhere maybe?
> 
> One other query - and forgive me as I’ve not been with Commandpost from the start and while I’ve done lots of programming, I’m not up to speed with the routines in CP - is there a way to programmatically change a button setting either from applescript of from the built in scripting - basically to either change the image associated with the button, or to change the button action - I’m thinking of times where there’s a toggle action, eg going from full screen to windowed, or from setting/unsetting a value … For instance in C1 Pro ⌘0 Zooms to fit and ⌥⌘0 zooms to 100%.  It would be useful to be able to change the knob press action to switch between the two depending on the last state. (Pity Phase One didn’t just toggle the value themselves, but they didn’t :( ) 
> 
> Best wishes
> 
> Nick
> 
> (Hope you and your family are avoiding this nuisance virus!)

**Comment by narimangafurov** [comment]
I completely agree! it would also be convenient to add the basic system setting in Loupedeck CT to all other applications, except for those that are selected and configured in CP. For example, when I open the Browser, it just turns off and nothing is visible on the display! I don’t even know how convenient it is to implement, but programming it for each application will require a lot of time. It would be convenient to have a common cell like system / finder. thank you for great product!

**Comment by latenitefilms** [comment]
**TO DO LIST:**
- [ ] expose bottom dial touch screen as mini trackpad/mouse input for finger slides? (eg to allow to use over selected colour wheels)
- [ ] Add feature to set central dial screen to clock as per loupedeck default.
- [ ] division of wheel lcd into button zones similar to original LD CT 2/3/4/5 vert/horiz/diamond for single touch
- [ ] Add slide left/right action on top button screen - this could be used to move between control banks similar to the original Loupedeck software.
- [ ] Add slide up/down action on top button screen
- [x] Ability to reset an individual control (to blank - action, icon, label)
- [x] Ability to copy (or move) Bank Settings from one bank to another.
- [x] Ability to copy control bank to another Application (for App version updates) eg Capture one 12 to Capture one 20.
- [x] add ability to drag drop image to wheel rather than drop zone- same as for buttons.
- [x] …and possible also for the small knobs?
- [x] So far, I’ve not tripped over any more bugs for squishing, other than the text labels for the CT buttons can be very slow when typing in the text - seems the text is updating the image for the button after every keypress - not sure if that can be left until the user exits the field or clicks elsewhere maybe?

**Comment by narimangafurov** [comment]
Great! waiting this

**Comment by latenitefilms** [comment]
@narimangafurov - Will try tick off some more things today and push out an update tonight.

**Comment by latenitefilms** [comment]
Prescott Van Leer [writes](https://www.facebook.com/groups/commandpost/permalink/2594920694096959/):

> I just got the Loupedeck CT and was curious if swipe and FN key capabilities are in the plan to be added soon?

**Comment by latenitefilms** [comment]
Will be addressed in #2375
