### ISSUE TITLE
Loupedeck CT Wheel and Dials slow

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2350]
I’ve noticed when you turn the main wheel or dials of the CT, if you turn slowly/methodically the functions work well, but if you turn quickly and more naturally as you would while editing, they lag a great deal and then after a few ticks nothing happens. Then you have to wait a few seconds for it to pick up again.

**Comment by studiobelvedere** [comment]
same Problem

**Comment by latenitefilms** [comment]
Ummm, interesting. What actions are you using exactly?

Do you see any errors in the Debug Console?

**Comment by pvanleer** [comment]
I'm seeing it with any action assigned to the wheel or dial. For the wheel, 10 frames back or forward is what I currently have assigned. If you do gradual turns it's fine, but as soon as you go too fast, it just quits responding, almost like it's not triggering above a certain speed of turn. For the dials, I have zoom, volume, rotation, pan left or right, and opacity assigned currently and they all behave the same as the wheel described above. 

There are no errors in the debug console because I don't think the turns are being picked up by the program to begin with once they happen. I can send video or provide more info if needed.

**Comment by latenitefilms** [comment]
I believe this issue has been addressed now somewhere along the lines in the 1.0.7 betas, but if not, please reopen this issue.
