### ISSUE TITLE
Loupedeck CT actions for Color Wheels not switching windows when on Color Curves

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2358]
With the Color Wheels, the Loupedeck CT actions (brightness knobs one side, saturation knobs the other, tint and temp on "slider" side touch screens), when you're NOT on the Color Wheels page and you activate one of the Color Wheels actions, it jumps the Inspector window to show the Color Wheels page on every page EXCEPT the Color Curves. If you're on HSL, Board, or the main effects page, it'll jump to show the Color Wheels, just not for Color Curves.

**Comment by latenitefilms** [comment]
Here's the problem:

<img width="1387" alt="Screen Shot 2020-08-18 at 2 26 09 am" src="https://user-images.githubusercontent.com/22286696/90419674-43abcd80-e0fa-11ea-8025-373a2cf06381.png">

When the Color Curves are showing, CommandPost still thinks the Color Wheels are showing.
