### ISSUE TITLE
Migrate HUD into a plugin

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#236]
Relates to #136.

**Comment by latenitefilms** [comment]
Error:

 ```
> *** ERROR: ...Post.app/Contents/Resources/extensions/hs/timer/init.lua:169: ERROR: incorrect type 'nil' for argument 1 (expected number)
stack traceback:
	[C]: in function 'hs.timer.new'
	...Post.app/Contents/Resources/extensions/hs/timer/init.lua:169: in function 'hs.timer.doEvery'
	/Users/latenitechris/CommandPost/cp/fcpx10-3/init.lua:241: in function 'loadScript'
	/Users/latenitechris/CommandPost/cp/fcpx10-3/init.lua:2236: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:452: in function 'require'
	/Users/latenitechris/CommandPost/cp/init.lua:185: in function 'loadScriptVersion'
	/Users/latenitechris/CommandPost/cp/init.lua:170: in function </Users/latenitechris/CommandPost/cp/init.lua:98>
	(...tail calls...)
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:452: in function 'require'
	/Users/latenitechris/CommandPost/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:507: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by latenitefilms** [comment]
I've finally had a chance to properly play with this. My observations:

I'm not sure if this is HUD code related or not, but pressing the CommandPost menu icon takes a little while to actually display the menu. Something is dramatically slowing it down compared to the way FCPX Hacks performs. In theory, the menubar menu should always load instantly (as all the "thinking" should be done in the background) - but it doesn't seem to be working that way anymore.

I've noticed that dragging the HUD with the Console active, will sometimes bring the Console to front of screen - but not always. Also, with the Console still active, when you first drag the HUD, it can be very laggy - but if you keep your mouse held down, and continue dragging, all the lagginess goes away.

However, if the Console isn't enabled, then the HUD seems quite buggy. For example, in a situation where you have the Console open, and you drag the HUD around the screen, sometimes the Console will pop to the front of screen. However, with the Console closed, this same action will make the HUD disappear. So, I think whatever is causing the Console to gain focus, is also causing the HUD to disappear.

If you enable XML Sharing with the HUD already open, it doesn't automatically show the Drop Targets. The only way I've been able to make the Drop Targets appear is to reload the Lua scripts.

Dropping files from FCPX to the Drop Target also doesn't seem to currently work?

The HUD Inspector values don't seem to update when the FCPX Preferences are reloaded.

The order of the Assign HUD Buttons Chooser seems random. It should probably be alphabetical order? We should also probably take the same right-click menu from the "FCPX Hacks Console", so users can show/hide different things in the Chooser.

None of the Effects, Transitions, Titles or Generators seem to appear in the Chooser currently?

**Comment by randomeizer** [comment]
Hey there. I should finally have some time this week to get back into this. To address your comments:

1. The Console seems to have changed in CP. It's generally 'always on top'. I'm not sure if this is affecting anything.

In general, focus with the HUD is tricky. It should only be visible if FCP is active. However, as soon as you click the HUD window, FCP is no longer active. And if the Console is or isn't visible, it seems to affect whether the 'active' app is CommandPost, so that's why it disappears when dragged. I think this comes down to figuring out a more reliable way of determining if the HUD is clicked or not.

How did the Drop Target code activate/deactivate previously? It could be a logic issue in the code that turns it on and off in the template though.

I was never sure how the Drop Target actually worked - I didn't have it running in the Hammerspoon version. But I haven't changed any of that code, to my knowledge. Possibly I missed something when converting it to a template?

I'll check if we are reloading the interface when updating the settings.

Yeah, sorting is a good idea. I think currently it's putting them in order that they come from the various 'Action' classes.

Effects/Transitions/Titles/etc appear for me, but you may have to re-run the scanners from the Shortcuts menus. I'm not exactly sure where you put the code that does the 'full scan' so they may not be in sync.

**Comment by randomeizer** [comment]
With regards to the right-click, maybe make it a separate issue that we port across once the Console has been ported to a plugin?

**Comment by latenitefilms** [comment]
Replies as follows:

> Hey there. I should finally have some time this week to get back into this.

Awesome! I'm also hoping to get back to things seriously over the next couple of weeks. I really want to get CommandPost to at least the same point as the current shipping version of FCPX Hacks, so that we can get it out there in the world, and start adding new features.

> The Console seems to have changed in CP. It's generally 'always on top'. I'm not sure if this is affecting anything.

Not on my system with #236 branch. The Hammerspoon Console (let's just call it the "Error Console" from now on), isn't always the front-most window for me, it can fall behind other applications. I did have some code in `cp/init.lua` at some point that "forced" the error console to be front-most (so it even appeared on the macOS login screen!), but I removed that code a while back, as it got annoying.

> In general, focus with the HUD is tricky. It should only be visible if FCP is active. However, as soon as you click the HUD window, FCP is no longer active. And if the Console is or isn't visible, it seems to affect whether the 'active' app is CommandPost, so that's why it disappears when dragged. I think this comes down to figuring out a more reliable way of determining if the HUD is clicked or not.

Agreed - it's a real pain. However, I still feel like, although still not perfect, the current public version of FCPX Hacks still works a bit better than this current code.

> How did the Drop Target code activate/deactivate previously? It could be a logic issue in the code that turns it on and off in the template though.

All good, the HTML wasn't escaped properly when you moved it across to become a template - however, I've since corrected this in the branch.

> Effects/Transitions/Titles/etc appear for me, but you may have to re-run the scanners from the Shortcuts menus. I'm not exactly sure where you put the code that does the 'full scan' so they may not be in sync.

Yeah, there must be some mistake in the "Scan Final Cut Pro" code. I'll look into that tomorrow.

> With regards to the right-click, maybe make it a separate issue that we port across once the Console has been ported to a plugin?

Good idea - will do!

**Comment by randomeizer** [comment]
I've just checked in some code to sort the options in the Button Chooser.

**Comment by latenitefilms** [comment]
> I've just checked in some code to sort the options in the Button Chooser.

Great, thanks!

Effects, Transitions & Titles all seem to work fine. I noticed a mistake in the generators code, but I've since fixed it.

One thing I don't like about the HUD Chooser as well, is that some items don't have a `subText` value. To keep things consistent - ideally EVERYTHING should have a `subText` value. I think only items that have been added via `cp.plugins.commands` are missing this.

**Comment by randomeizer** [comment]
Yeah, we just need to add a 'group' to all the commands. I hadn't gone through all the commands yet.

**Comment by randomeizer** [comment]
The HUD is now updating when options are enabled/disabled, and will always require at least one to be turned on.

**Comment by latenitefilms** [comment]
FYI: HUD is now moved into a plugin. It's not completely bug-free - but we'll address all these problems in seperate issues.
