### ISSUE TITLE
Add support for changing Loupedeck CT backlight levels

### ISSUE THREAD

**Issue by Corion** [fcpxhacks/fcpxhacks#2367]
First of all, thank you for this documentation of the Loupedeck CT commands!

In experimenting, I found that the command code 0x0409 sets the backlight level on my Loupedeck CT. The storage in register 2 seems to be only for common storage of the light level.

In my (Perl) code, I use the following sequence to update the backlight level:

    $value = read_register(2);
    # update byte 2 of $value
    set_register(2, $value);
    send_command(0x0409,$new_level);

**Comment by randomeizer** [comment]
So you have to update the register and then send the command?

**Comment by Corion** [comment]
No, the two are completely independent from what I see. The register only saves the value, but has no influence on actually changing the brightness.

The command is what changes the brightness, completely independent of the register.

I think the register is only used as common storage between applications so that all applications can persist the brightness in the same location.

**Comment by randomeizer** [comment]
So the read/set register commands are not necessary at all?

Given that it's just a single bit, I'm assuming that it's just switching something on or off. Does it affect the lights at all in either setting?

**Comment by Corion** [comment]
The read/set register commands are not necessary for raising/lowering the backlight level.

They might be nice, so the backlight level survives a device reboot, but only, if the next application also reads the initial level from the register.

Reading/writing the register does not change the lights at all. Only the 0x0409 command changes the lights.

**Comment by randomeizer** [comment]
Oh, it's the whole second byte of register 2. Got it.

**Comment by latenitefilms** [comment]
Thanks heaps @Corion - HUGELY appreciated!

I'll have a play with this when I get a chance.

If you stumble across any other functions, let me know.

**Comment by latenitefilms** [comment]
Will be addressed in #2375
