### ISSUE TITLE
Loupedeck CT pixel buffer format is 5-6-5, not 5-3-5

### ISSUE THREAD

**Issue by Corion** [fcpxhacks/fcpxhacks#2369]
One more finding while playing around with the Loupedeck CT. The color encoding routine for RGB colors is wrong. It seems to assume a 5-5-3 memory layout for b-r-g colours:

```
local function rgbToInt16(r, g, b)
    return (((b >> 3) & 0x1F) << 8) | (((r >> 3) & 0x1F) << 3) | ((g >> 5) & 0x07)
end
```

This is partially caused by the unspecified way, these numbers are then loaded as a raw array into the Loupedeck CT memory. It seems that the data is loaded as big-endian byte sequence from the array.

From my analysis, I found treating the memory words stored as little-endian and the bit/color correspondence as the more standard 5-6-5 order makes images display correctly for me. I only have Perl code to run, so my "port" of the rgbToInt16 function might be misleading, and this still needs a change in how the array-as-bytes gets passed on:

Working Perl code:

```
sub _rgb($r,$g,$b,$alpha=undef) {
    # The Loupedeck uses 5-6-5 16-bit color
    # The bits in the number are matched to
    # bits  0123456789012345
    # color bbbbbggggggrrrrr
    # the memory storage is little-endian
        my $bit =
	  (((int $r >> 3) & 0x1f) << 11)
        + (((int $g >> 2) & 0x3f) << 5)
	+ (((int $b >> 3) & 0x1f))
	;

	#die sprintf "[%d,%d,%d] %d - %04x", $r,$g,$b, $bit, $bit;
        return pack 'v', $bit
};
```
`pack 'v', $bit` takes a (16-bit) number and packs it into a little-endian byte sequence. I tested the bits and their effect by cycling through all 16 numbers with a single bit set and filling the screen, noting for each number how it affected the display.

If you cannot change the memory layout of the array representation in Lua, you can construct the numbers differently, by splitting the bits for green between the high and low byte, but that is quite involved code then.

If you want/need more Perl code, I have it at https://github.com/Corion/HID-LoupedeckCT , but if you want more Lua code, maybe you can tell me how to set up / install a minimal environment for testing out Lua code against my hardware.

**Comment by latenitefilms** [comment]
Legend, thanks heaps @Corion!

FWIW - we're not actually using the `rgbToInt16()` function in our current implementation, all the conversion logic is happening Objective-C land here:

https://github.com/CommandPost/CommandPost-App/blob/master/extensions/image/internal.m#L1621

To be honest, all this stuff goes a little over my head, so if you have any suggestions on what I should try to fix in the above code, let me know and I'll test it out.

**Comment by Corion** [comment]
Aah, that explains why it works. I think the following code should match my implementation:

                uint16_t color = (((green >> 2) & 0x3f) << 5 )| (((red >> 3) & 0x1F) << 11) | (((blue >> 3) & 0x1F));
                uint8_t little = color & 0xFF;
                uint8_t big = (color >> 8 ) & 0xFF;
                [output appendBytes:&big length:1];
                [output appendBytes:&little length:1];

My code sends the following byte sequences/commands to draw six tiny green squares in the middle of the virtual buttons 1-6 (row 1: button 1,2,3,4, row 2: button 1,2):
```
> ff 10 01 00 41 00 2d 00 2d 00 04 00 04 20 00 20    �...A.-.-.... . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 -- -- --    . . . . . . ....
> ff 10 02 00 41 00 87 00 2d 00 04 00 04 40 00 40    �...A.�.-....@.@
> 00 40 00 40 00 40 00 40 00 40 00 40 00 40 00 40    .@.@.@.@.@.@.@.@
> 00 40 00 40 00 40 00 40 00 40 00 40 00 -- -- --    .@.@.@.@.@.@....
> ff 10 03 00 41 00 e1 00 2d 00 04 00 04 80 00 80    �...A.�.-....�.�
> 00 80 00 80 00 80 00 80 00 80 00 80 00 80 00 80    .�.�.�.�.�.�.�.�
> 00 80 00 80 00 80 00 80 00 80 00 80 00 -- -- --    .�.�.�.�.�.�....
> ff 10 04 00 41 01 3b 00 2d 00 04 00 04 00 01 00    �...A.;.-.......
> 01 00 01 00 01 00 01 00 01 00 01 00 01 00 01 00    ................
> 01 00 01 00 01 00 01 00 01 00 01 00 01 -- -- --    ................
> ff 10 05 00 41 00 2d 00 87 00 04 00 04 00 02 00    �...A.-.�.......
> 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00    ................
> 02 00 02 00 02 00 02 00 02 00 02 00 02 -- -- --    ................
> ff 10 06 00 41 00 87 00 87 00 04 00 04 00 04 00    �...A.�.�.......
> 04 00 04 00 04 00 04 00 04 00 04 00 04 00 04 00    ................
> 04 00 04 00 04 00 04 00 04 00 04 00 04 -- -- --    ................
> 05 0f 07 00 41 -- -- -- -- -- -- -- -- -- -- --    ....A...........
```

The results are all acknowledged:

```
< 04 10 00 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 01 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 02 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 03 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 04 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 05 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 10 06 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
< 04 0f 07 01 -- -- -- -- -- -- -- -- -- -- -- --    ................
```

The first two squares are not recognizable with these small green squares, but when I move up the size to 16x16, they become discernable. I'm only posting the one for the lowest intensity, for space reasons:

```
> ff 10 01 00 41 00 2d 00 2d 00 10 00 10 20 00 20    �...A.-.-.... . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20    . . . . . . . . 
> 00 20 00 20 00 20 00 20 00 20 00 20 00 -- -- --    . . . . . . ....
```

**Comment by latenitefilms** [comment]
Switching:

```objc
uint16_t color = ((green >> 5) & 0x07) | (((red >> 3) & 0x1F) << 3) | (((blue >> 3) & 0x1F) << 8);
```

to:

```objc
uint16_t color = (((green >> 2) & 0x3f) << 5 )| (((red >> 3) & 0x1F) << 11) | (((blue >> 3) & 0x1F));
```

...definitely doesn't give the intended results:

![IMG_0063](https://user-images.githubusercontent.com/22286696/87217141-a686a800-c389-11ea-8e30-c5c15e5da893.jpg)
