### ISSUE TITLE
Warning message about TouchBar support in El Capitan

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#24]
Currently a dialog box pops up every time the script loads warning that the current version of macOS does not support the Touch Bar. This seems unnecessary...

**Comment by randomeizer** [comment]
This appears to be a mandatory dialog box which is generated by the 'touchbar' module when it is 'required'. The workaround will be either:

1. Update our code to check the version number before attempting 'touchbar' support.
2. Update the 'touchbar' module to not be so verbose.

**Comment by latenitefilms** [comment]
That's interesting! I've only got 10.12 with me currently, but will test this out on Monday. This was definitely not my intention, as **touchbar.supported()** should default to **touchbar.supported(false)** which does not display a dialog box.

**Comment by randomeizer** [comment]
Here's a screenshot:

<img width="511" alt="screenshot 2016-11-26 09 48 50" src="https://cloud.githubusercontent.com/assets/3589315/20636870/0c871c84-b3c1-11e6-8329-738f66119801.png">

**Comment by latenitefilms** [comment]
[Bug submitted](https://github.com/asmagill/hammerspoon_asm/issues/8).

**Comment by randomeizer** [comment]
I've upgraded the library to 0.6.1 which has resolved the dialog issue.
