### ISSUE TITLE
Create a script to check i18n files against the 'en' version

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#243]
A manually-run script which will compare the values in the different languages and produce a report on variations such as:

* Missing values
* Additional values (probably typos or old values)
* Values which contain a different set of injections (eg. "Foo %{bar}")

**Comment by latenitefilms** [comment]
I'm going to close this issue as a lot of the multiple language conflicts should now be handled by [POEditor](https://poeditor.com), and we have `_findUnusedLanguageStrings()` in `cp.developer` to display a list of unused values (although it probably needs to be updated to work with the JSON files).
