### ISSUE TITLE
Create a plugin for managing keyboard shortcuts

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#246]
Related to #135.

Create a keyboard shortcut manager which other plugins can use to register related keyboard shortcuts.

This may or may not include modifying the plists which are used by FCPX to configure shortcuts in the Command Editor. That's a bit more advanced, so I suspect it will be a separate issue to resolve that.

**Comment by latenitefilms** [comment]
FYI: Eventually it would be great to add a keyboard shortcut manager into FCPX Hacks for those users who are too scared to "Enabled Hacks Shortcuts in Final Cut Pro", so they can still customise shortcuts without having to enter an Administrators password.

[This](https://github.com/Hammerspoon/hammerspoon/issues/1187) might help if it ever gets made.
