### ISSUE TITLE
Add a Welcome Screen

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#247]
Something similar to:

<img width="934" alt="screen shot 2017-01-21 at 5 44 48 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172663/7cc888c2-e001-11e6-8fd5-8153c450ef1d.png">
<img width="934" alt="screen shot 2017-01-21 at 5 44 55 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172665/7d154c52-e001-11e6-9d8e-875bf5a72853.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 01 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172666/7d19093c-e001-11e6-932f-5e64093eafdf.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 09 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172667/7d209d8c-e001-11e6-94ab-6ddf28d37c29.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 13 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172668/7d2318b4-e001-11e6-9817-d7084ee8414f.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 16 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172669/7d2596b6-e001-11e6-887f-316b60da5a99.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 20 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172664/7cf5d318-e001-11e6-8c75-2d17e2163c60.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 24 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172670/7d28bdfa-e001-11e6-92f9-6e6d86099dd2.png">
<img width="934" alt="screen shot 2017-01-21 at 5 45 28 pm" src="https://cloud.githubusercontent.com/assets/22286696/22172671/7d41f89c-e001-11e6-964f-0df37be225b1.png">

**Comment by latenitefilms** [comment]
Maybe this Welcome screen should be the thing that explains to users how and why they need to enable Accessibility permissions, and also suggest that they update all the lists (i.e. Effects, Transitions, Titles, Generators), so that they don't get confused when the Console/HUD/Shortcut buttons are empty.

**Comment by randomeizer** [comment]
Yeah. I wish there was a better way of getting the effect/transition/etc
lists though...

**Comment by latenitefilms** [comment]
Well, it is TECHNICALLY possible to build this list without Final Cut Pro open, but it's a lot of work and coding.

All the 3rd party effects, generators, titles and transitions stored in the `/Library/Application Support/Final Cut Pro/Templates/` and `~/Movies/Motion Templates/` folders are just Motion XML files (`ozxmlscene`) with different extensions:

Compositions = `.motn`
Effects = `.moef`
Generators = `.motn`
Titles = `.moti`
Transitions = `.motr`

As these are just XML, they should be pretty easy to "read" and work out the name and category.

FxPlug plug-ins are installed to `/Library/Plug-Ins/FxPlug`. These SHOULD be fairly simply to "read" as well, as their name and category SHOULD be located in the `/Contents/Info.plist` file - however I have noticed that SOME 3rd party plugins don't contain this information, so I'm not exactly sure how we'd determine these ones off the top of my head.

Audio Effects are a bit more complicated. I believe the Audio Units are stored in `/Library/Audio/Plug-Ins`, but they need to be "validated" before they're available in Final Cut Pro - which is determined from `~/Library/Preferences/com.apple.audio.InfoHelper.plist`, but I have no idea how it all works.

Internal Effects are also a bit more complicated, as they're scattered around the Final Cut Pro bundle.

Although it would be cool, if we could build these lists without using GUI Scripting - I think it falls into the too hard basket for now.

Maybe however, we need to have a single "Scan Final Cut Pro Plugins" button in the menubar that scans for all the effects, generators, titles, transitions and maybe even menu items - in addition to the existing individual items in the "Assign Shortcuts" menubar?

**Comment by randomeizer** [comment]
Or have it as an option at the top of the 'Assign Shortcuts' item.
Rescanning all of them at once kind of makes sense. Doing the individual
ones is a bit annoying TBH...

**Comment by latenitefilms** [comment]
Agreed - it would definitely make sense to "scan" them all in the one go.

However, I'm not sure the "Assign Shortcuts" menu though is the best place for it - given this also affects the HUD & Console. Maybe we should put it in the "Preferences" menu? I'm also not sure of the best naming for it. "Scan Final Cut Pro Plugins" is probably not right. Maybe something like "Analysis Final Cut Pro Configuration", "Scan Final Cut Pro Configuration", or just "Scan Final Cut Pro"?

The label might also not matter as much if we "force" the user to perform the "scan" on the first launch of CommandPost, via the Welcome Screen - as we can then explain that, "if you update a transition, effect, title or generator, please perform 'Preferences > Scan Final Cut Pro' again", etc.

Also, I wonder if it's worthwhile leaving the original "Update Effects/Transitions/Titles/Generators List" items there, so that if you install a new effect for instance, you don't have to rescan everything? Although, thinking about it, that probably just complicates things - I think maybe a single "scan" button is enough.

Maybe also, if a "scan" hasn't completed, when you first try activate the HUD or Console, it doesn't let you, and explains that you need to perform the "scan" before continuing?

Thoughts?

**Comment by latenitefilms** [comment]
Maybe something like this?

![01](https://cloud.githubusercontent.com/assets/22286696/22861618/62ff6b64-f171-11e6-94fd-eae75ece8e2c.jpg)
![02](https://cloud.githubusercontent.com/assets/22286696/22861616/62fcbaae-f171-11e6-8121-4ba06403d7ea.jpg)
![03](https://cloud.githubusercontent.com/assets/22286696/22861617/62fe306e-f171-11e6-85fe-b086c513e8f1.jpg)
![04](https://cloud.githubusercontent.com/assets/22286696/22861620/6301d4c6-f171-11e6-86e7-bf442be56f29.jpg)
![05](https://cloud.githubusercontent.com/assets/22286696/22861619/63007b44-f171-11e6-8a54-17c59269f873.jpg)

**Comment by randomeizer** [comment]
Yeah, some basic 'setup steps' would be good, and it just checks them every
time it loads. Maybe one a week on took off that too. If everything is up
to date, nothing happens. If not, they get walked through the process.
