### ISSUE TITLE
Add hs.accessibilityState() checks for all GUI Scripting Functions

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#250]
Currently when FCPX Hacks load it performs `hs.accessibilityState(true)`, which prompts the user to enable the Accessibility Controls for Hammerspoon - but there's no checks in place to make sure that the user actually does it.

We should either add `hs.accessibilityState()` checks to everything that requires Accessibility permissions (which is most things, as all the Final Cut Pro specific hotkeys require Accessibility Access) - or maybe FCPX Hacks will forcefully quit until the Accessibility State is true (this is how it originally was in original version of FCPX Hacks - as changing the Accessibility State requires Hammerspoon to restart anyway to get back full functionality).

**Comment by randomeizer** [comment]
How many features _don't_ require accessibility to be enabled?

**Comment by latenitefilms** [comment]
Not many... just the "hacks" (moving markers), etc. Everything that uses `hs._asm.axuielement` requires Accessibility, and any `hs.eventtap` which try to capture `keyUp` and `keyDown` events will also fail until Accessibility is enabled.

However, I did just notice that you can switch Accessibility off, and the highlight playhead shortcut (for example) will stop working, but as soon as you switch it back on, it works again (without having to restart Hammerspoon).

**Comment by randomeizer** [comment]
Interesting

**Comment by latenitefilms** [comment]
If we decide to go with a standalone app, [this](https://github.com/fcpxhacks/hammerspoon/commit/89506669702a653a8aa60f03d8fa5ce79d033d9f) could be a good way to fix things.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as the current way of doing things in develop seems to work fine.

**Comment by latenitefilms** [comment]
Actually... should we add some kind of "watcher" into CommandPost, so that if Accessibility does get disabled by the user whilst the app is running, that it hides the menubar, and alerts the user to enable accessibility to restore functionality?

**Comment by latenitefilms** [comment]
...or maybe rather than disabling the menubar, we add in some kind of function that automatically disables plugins that require accessibility when accessibility is disabled? Thoughts @randomeizer ?

**Comment by latenitefilms** [comment]
Now that we have a Welcome screen, I think that if the user tries to trigger a function that requires Accessibility and it's disabled, CommandPost should just re-load so that the Welcome Screen is shown.

**Comment by latenitefilms** [comment]
Note to self: https://github.com/Hammerspoon/hammerspoon/issues/1239
