### ISSUE TITLE
Effects Presets not appearing in Search Console

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2505]
Gil Sylvain [writes](https://www.facebook.com/groups/commandpost/permalink/2754975721424788/):

> Hello! There's a question I've been asking myself for a while, how do you manage to use "effect presets" with CommandPost?
> To make sure that I make myself understood : there are some plugins for whom I need to change the default presets everytime I wanna use them so I saved it with the "Save Effects Presets". It's now in my list of plugins under a folder that I had to create. But when I look for that plugin/presets in CommandPost, I can not find it. Is there a way to do so? It would save me hours in editing.
> I tried to find the information here and on the website but I don't see anyone talking about it.

> Thanks! I tried but for example I was looking for a preset that I called "Greenkey". As you can see it exists on my list, but doesn't appear in the search console. I tried every tab on the top (just to make sure), and it doesn't show up.

![122962428_226402432150869_7879893363863240905_o](https://user-images.githubusercontent.com/22286696/97777263-18962d80-1bc3-11eb-9731-09d62558f272.jpg)

**Comment by pvanleer** [comment]
I have this same question/issue. Custom saved preset effects and Custom Workspaces are not assignable in the Keyboard Shortcut section for use in the Loupedeck software. They don't show up whether using the search bar or action select field.

**Comment by latenitefilms** [comment]
@pvanleer - Thanks for letting me know. I think I know what the issue is, but I've been insanely flat out in Unreal Engine-land, and haven't had a chance to work on CommandPost for a few weeks - will try and fix this up soon.

**Comment by latenitefilms** [comment]
@pvanleer - Apologies for the delayed reply. I've just tested it and it seems to work fine here. However, you will need to re-scan your plugins after adding the new Effects Preset. You should see a macOS notification appear when you add a new Effects Preset. You can also manually re-scan via the "Scan Motion Templates" button in the Final Cut Pro panel of CommandPost's preferences.

I'm closing this issue for now, but feel free to re-open if you're still having problems.
