### ISSUE TITLE
Guides and overlays not working in FCP 10.5

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#2514]

**Comment by DavidNapier** [comment]
MacOS Big Sur, FCP 10.5 - latest version of CP - graphical functions like HUB, Guides etc. not working, other functions like scrolling timeline etc do. MacPro 2013 - Firepro D300s. HUB appears when FCP is loading but then disappears when FCP UI loads up.

**Comment by latenitefilms** [comment]
Thanks @DavidNapier - I'll try look at Big Sur next week.

**Comment by DavidNapier** [comment]
Excellent Chris. Many thanks. Love you work! Both with CP and the film stuff.

**Comment by latenitefilms** [comment]
@DavidNapier - I haven't been able to reproduce this on a fresh install of macOS Big Sur & FCPX 10.5.1. Are you able to try trashing your FCPX preferences and window layouts, and see if the latest CommandPost Beta 30 works?

**Comment by DavidNapier** [comment]
Hey Chris

I did a totally new install on the latest CP etc. and all is now working fine. Perhaps I stuffed up the permissions or something. But so many thanks for your support. 

BTW.  read you’ve done some work in UNREAL with MOCAP and 3D? I’d love to chat about this for a kids series I’m developing- if you have time. 

Have a good Xmas.

Cheers

DN
