### ISSUE TITLE
feature request: add timeline horizontal scrolling shortcuts to FCPX

### ISSUE THREAD

**Issue by robotechdy** [fcpxhacks/fcpxhacks#2537]
I just tried CommandPost to enable zoom in/out with my mouse (e.g. set as **CMD + mouse scrolling**), which **works great**!

Now, I am wondering is that possible to add shortcuts to enable timeline horizontal scrolling with a normal mouse (a normal mouse without a horizontal wheel). For example, we can set **Ctrl + mouse scrolling** to perform timeline horizontal scrolling,
I have an Apple Magic mouse that can perform timeline horizontal scrolling action by default. However, I (and some of my artist friends) still prefer to use a normal moue (e.g. a good gaming Logitech/Razer mouse) with more precise control.

**Comment by latenitefilms** [comment]
Unless I'm misunderstanding, you should already be able to do horizontal scrolling with a normal mouse wheel by holding down the SHIFT key?

**Comment by robotechdy** [comment]
@latenitefilms 
Ah, I see. Thanks!
