### ISSUE TITLE
Dual Screen Inconsistencies

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#254]
Peter Metcalf reports:

> Hi Chris. The Dual screen thing seems to be broken again.

> Re the reveal in browser not working dual screen. ….or sometimes. I have found it’s related to the primary screen being full screen, (UI, not output) or so I seem to be seeing. However once bouncing in and out of that mode all seems fine.

> I've found what seems to be causing the issue. If the first time I use the match frame I'm in full screen in the UI it doesn't work. But going back to full screen is not a problem after resizing. 

```
-----------------------------
| FCPX Hacks v0.78          |
| Created by LateNite Films |
-----------------------------
Hammerspoon Version:            0.9.52
macOS Version:                  10.12.2
Final Cut Pro Version:          10.3.2
Final Cut Pro Language:         en
FCPX Hacks Locale:              en_NZ
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app

> Successfully loaded.
> Expected exactly 1 selected clip in the Libraries Browser.
 > Error occurred in singleMatchFrame().
> Expected exactly 1 selected clip in the Libraries Browser.
 > Error occurred in singleMatchFrame().
> Expected exactly 1 selected clip in the Libraries Browser.
 > Error occurred in singleMatchFrame().
> Expected exactly 1 selected clip in the Libraries Browser.
 > Error occurred in singleMatchFrame().
```

**Comment by randomeizer** [comment]
Could we get a screenshot of the configuration where it's failing? It is
usually an issue with some possible combination that the code is not
accounting for.

**Comment by latenitefilms** [comment]
@randomeizer - Sent via Facebook (as I'm not sure Peter Metcalf wants us to share his screenshots publicly).

**Comment by randomeizer** [comment]
Ok, from looking a the screenshots, my guess is we're having trouble finding the Browser when it's on the secondary window at times.

I'll look into it.

**Comment by latenitefilms** [comment]
Note to self - commenting out the below line (AXTitle) fixes things:

```
function SecondaryWindow.matches(element)
	if element and element:attributeValue("AXSubrole") == "AXUnknown" then
	--and element:attributeValue("AXTitle") ~= "" then
		local children = element:attributeValue("AXChildren")
		return children and #children == 1 and children[1]:attributeValue("AXRole") == "AXSplitGroup"
	end
	return false
end
```

**Comment by randomeizer** [comment]
Are you able to replicate the configuration where the title is ""?

**Comment by randomeizer** [comment]
I've removed the test for 'not blank'. It should be safe enough without it.
