### ISSUE TITLE
New Fullscreen Shortcuts Buggy

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#255]
It looks like **Enable Shortcuts During Fullscreen Playback** has been broken since #217.

If I'm using dual screens, FCPX Hacks is thinking I'm in fullscreen playback mode when I'm not.

**Comment by randomeizer** [comment]
I'm having trouble replicating this exactly. Could you post the configuration of your screen when this is an issue?

**Comment by latenitefilms** [comment]
Ummm... I can't reproduce now, so I'm assuming one of the other fixes to `cp.finalcutpro` must have fixed things. I'll close the issue for now.
