### ISSUE TITLE
Rearrange & Cleanup Folder Structure

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#257]
@randomeizer - Whilst we're doing some major code changes, should we move `i18n`, `semver` and `slaxml` out of the `fcpxhacks/modules` folder and just into the root `hs` folder? Maybe `protect.lua` as well?

One day I'd like to re-look at `dialog.lua` and maybe make it more generic, so that it can be turned into a proper Hammerspoon core module - not specifically for FCPX Hacks.

Maybe we could move `tools.lua` into a plugin?

Let's get rid of `fcpx10-2-3.lua` and concentrate on 10.3 moving forward.

`fcpx10-3.lua` should eventually disappear, and any non-plugin code should just go in `fcpxhacks/init.lua`.

Thoughts?

**Comment by randomeizer** [comment]
Yeah, I was thinking that. We might want to split some of these into
separate issues, to contain the testing required.

Also, one we are an app, we should probably not use 'hs.' for the prefix
for our custom modules. Maybe 'cp.' instead?

This should happen after we finish #136 however.

**Comment by latenitefilms** [comment]
> Also, one we are an app, we should probably not use 'hs.' for the prefix
> for our custom modules. Maybe 'cp.' instead?

Yeah, I think that's a great idea.

The only reason we're using "hs" currently is because I wanted to keep it as simple as possible for users to drag the two files in the DMG release. But if we go to a standalone app (which I think we definitely do), then we can definitely move all our custom modules into a "cp" folder instead.

**Comment by latenitefilms** [comment]
Split into seperate issues.
