### ISSUE TITLE
Toolbox to convert a Vimeo CSV to FCPXML with Markers

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2610]
Gary Roll writes:

> Chris, I enjoyed your talk at the FCPX Global Summit this year. 
> 
> I’d like to request to have a small feature added to CommandPost that would greatly help our team’s workflow as well as others that work in a simliar manner.
> 
> We like the Frame.io Review-Page CSV notes that import directly into FCP timeline as ToDo markers but as a small non-profit, we cannot do the expense of monthly fees for multilple editors at Frame.io.
> 
> What I have found that works (sometimes) is using the downloaded CSV from Review Notes on our Vimeo review page, and importing them into a free application called MarkX that exports fcpxml which can imported into FCP and which then creates storyline ToDo markers that can be ticked off as Completed (like Frame.io). The issue is that the MarkX app is inconsistent and doesn’t always work-sometimes only a few notes import and actually become markers. MarkX isn’t providing support (after all, it’s a free app from a single creator) and I get it. However, It seems that this might be easily added to the CP workflow (I know, easy for me to say) and would be a great solution for many editors around the world who use your product.
> 
> If I’m unclear or you have questions, I’ve created a 2 page PDF to show our staff how to do the process that I’d be glad to send you.

**Comment by latenitefilms** [comment]
Example CSV from Vimeo:

```
  "Video Version","#","Timecode","Username","Note","Reply","Date Added","Resolved"
"Eggs Cannot Fly - Edit 30.mov",1,00:00:26,"LateNite Films","Test 1",--,"Friday, February 26, 2021 At 3:43 PM",No
"Eggs Cannot Fly - Edit 30.mov",2,00:00:28,"LateNite Films","Test 2",--,"Friday, February 26, 2021 At 3:43 PM",No
,,,,,,,
```

**Comment by randomeizer** [comment]
What's your plan? FCPXML template that you inject code into?

**Comment by latenitefilms** [comment]
Basically, similar to how Frame.io works. I'll make a very simple Toolbox panel that accepts a CSV file, then once the CSV is received I'll generate a new FCPXML (like Frame.io does) which contains a Compound Clip with a Timecode Generator that goes the length of the video, and Titles on top with to-do markers - and send that to FCPX. We should already have all the bits to do this, the only thing I'll struggle with is the maths, but it's only to the second, not the frame, so hopefully it won't be too hard.

**Comment by latenitefilms** [comment]
Adam Olivero writes:

> Hey question. Can Commandpost import markers from a CSV File into the Final Cut Pro X Timeline? I make markers and timing with TimeStats and they can export via CSV.

**Comment by latenitefilms** [comment]
https://twitter.com/editblog/status/1453109054868426764?s=21
