### ISSUE TITLE
Can't find touchbar option in preferences 

### ISSUE THREAD

**Issue by luke310** [fcpxhacks/fcpxhacks#2615]
I've got a MacBook Pro 2019 with touchbar but can't find the option for touchbar in preferences, I'm on the latest update for the MacBook. please help.

**Comment by latenitefilms** [comment]
Sorry for the delayed reply @luke310 - just to confirm, did you look in the "Control Surfaces" window? Somewhere along the lines we split off the Preferences and Control Surfaces into their own windows to simplify things.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now. Feel free to re-open if you're still having issues.
