### ISSUE TITLE
Issues with Dual Displays in Final Cut Pro X

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2687]
[Joseph Linaschke](https://photojoseph.com) reports:

> Hey there,
> 
> Ironically, when I wanted to report an issue with the "provide feedback or report an issue" menu option, that does nothing, so I'm reverting to email — sorry.
> 
> I think dual display FCP layouts affect a lot of things in CommandPost. I'd uninstalled it the past because of it, but recently installed to try again. For example, I'm trying to use the draggable guides, but can NOT get them to show up, regardless if I toggle them off/on manually, or using caps lock, if I have a dual display layout. As soon as I rever to the default FCP layout, it works perfectly.
> 
> Is there a way to make this behave with dual displays?
> 
> thanks so much,
> -Joseph 

> Hey Chris!
> 
> OK, the "feedback" option, it turns out, was opening behind a bunch of other windows. I saw it finally when I shut a bunch of apps down at the end of the day! When I select it now, it does open on top, but also takes about 12 seconds to open. And during that time, my system is quite unresponsive, there's no errors in your Debug Console, but when it finally opens, the system catches back up. Weird.
> 
> Even more odd about the dual screen. This is actually similar to the issue I had before, now that I think about it, and why I stopped using it. Someone (maybe you) had made the same suggestion about the custom layout, but this is a brand new one — I just trashed FCP prefs a few days ago, so this is brand new. 
> 
> Just ran a test. Weird results for sure. I reset to the default layout, and caps lock toggles the guides just fine. I then started rebuilding my own layout, one piece at a time. Caps lock still worked. I finally SAVED my custom layout, and immediately caps lock stopped working!
> 
> I then proceeded to quit everything else on the system, and no luck. I even moved the screen layout in Display preferences, but that made no difference.
> 
> of course as soon as I go back to the default layout, it works fine!
> 
> super weird!
> -Joseph 

![Screen Shot 2021-04-20 at 6 12 33 PM](https://user-images.githubusercontent.com/22286696/116338782-a031c180-a81f-11eb-9472-688af1c14df0.jpg)
![Screen Shot 2021-04-20 at 6 12 33 PM (2)](https://user-images.githubusercontent.com/22286696/116338800-a758cf80-a81f-11eb-9f83-9ea483eb62fb.jpg)

**Comment by randomeizer** [comment]
As of fixing #2715, which may or may not be related, I can't replicate this bug, with or without custom workspaces. Probably worth getting Joseph to retest it again with the next release.

**Comment by latenitefilms** [comment]
I also tried doing the same layout as Joseph, and can't reproduce any issues. My caps lock key also seems to be working correctly every time.

**Comment by latenitefilms** [comment]
Joseph writes:

> Hey mate, finally got to test this. Upgraded (to 1.2.6, not 1.2.5, as that’s what showed up) and the problem is still there. Single screen mode, the overlays are fine. Dual screen, and they don’t appear. Also notice there’s double Overlay menus, if that means anything.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/22286696/121266698-55b36280-c8fe-11eb-88ef-d73cb1558ac5.png">

**Comment by latenitefilms** [comment]
Joseph writes:

> I uninstalled and reinstalled, and that addressed the double menu.
> 
> As for windows management or other automation software… let’s see…
> 
> Bitfocus companion (quit; no difference)
> Stream Deck (quit; no difference)
> 
> Can’t think of anything else that’d qualify. But just to be sure, I just manually quit absolutely everything that I could find that wasn’t core system. (My god Adobe has a crap-ton of background processes!!). Here’s all that’s left, which is still a lot but the only ones I can’t seem to quit are ones that are probably being re-launched by FCP, and Mimestream (and related) which is my mail app and brand new to my system. 
> 
> I even quite and relaunched both FCP and CommandPost after quitting all the other apps.
> 
> - accountsd
> - ActivityMonitor
> - AdobeIPCBroker
> - adprivacyd
> - AGMService
> - AirPlayUIAgent
> - akd
> - AMPArtworkAgent
> - AMPDeviceDiscoveryAgent
> - AMPLibraryAgent
> - amsaccountsd
> - amsengagementd
> - APFSUserAgent
> - AppleSpell
> - AppSSOAgent
> - appstoreagent
> - AquaAppearanceHelper
> - ArchiveService
> - askpermissiond
> - AssetCacheLocatorService
> - assistant_service
> - assistantd
> - AssistantService
> - AudioComponentRegistrar
> - avatarsd
> - backgroundtaskmanagementagent
> - bird
> - CacheDeleteExtension
> - CalendarAgent
> - CalendarWidgetExtension
> - CallHistoryPluginHelper
> - CallHistorySyncHelper
> - callservicesd
> - CalNCService
> - CarbonComponentScannerXPC
> - CategoriesService
> - CategoriesService
> - CategoriesService
> - CategoriesService
> - CategoriesService
> - CategoriesService
> - CategoriesService
> - cdpd
> - cfprefsd
> - CinemaGradeHelper
> - cloudd
> - CloudKeychainProxy
> - cloudpaird
> - cloudphotod
> - CMFSyncAgent
> - colorsync.useragent
> - com.apple.accessibility.mediaaccessibilityd
> - com.apple.appkit.xpc.openAndSavePanelService(FinalCutPro)
> - com.apple.appkit.xpc.openAndSavePanelService(Frame.io)
> - com.apple.audio.InfoHelper
> - com.apple.audio.SandboxHelper
> - com.apple.audio.SandboxHelper
> - com.apple.audio.SandboxHelper
> - com.apple.audio.SandboxHelper
> - com.apple.BKAgentService
> - com.apple.CharacterPicker.FileService
> - com.apple.CloudDocs.MobileDocumentsFileProvider
> - com.apple.DictionaryServiceHelper
> - com.apple.geod
> - com.apple.hiservices-xpcservice
> - com.apple.iCloudHelper
> - com.apple.photos.ImageConversionService
> - com.apple.photos.ImageConversionService
> - com.apple.PressAndHold
> - com.apple.quicklook.ThumbnailsAgent
> - com.apple.Safari.History
> - com.apple.Safari.SafeBrowsing.Service
> - com.apple.sbd
> - com.apple.siri.ClientFlow.ClientScripter
> - com.apple.siri.ClientFlow.ClientScripter
> - com.apple.siri.embeddedspeech
> - com.apple.speech.speechsynthesisd
> - com.apple.tonelibraryd
> - com.divergentmedia.scopelinkserver
> - CommandPost
> - CommandPostNetworking
> - CommCenter
> - commerce
> - ContactsAccountsService
> - contactsdonationagent
> - containermanagerd
> - ContainerMetadataExtractor
> - ContextService
> - ContextStoreAgent
> - ControlCenter
> - CoreSyncHelper
> - coreauthd
> - CoreLocationAgent
> - CoreServicesUIAgent
> - corespeechd
> - corespotlightd
> - CoreSpotlightService
> - ctkahp
> - ctkd
> - deleted
> - devicecheckd
> - diagnosticextensionsd
> - diagnostics_agent
> - DiskUnmountWatcher
> - distnoted
> - dmd
> - Dock
> - DockExtra
> - DockExtra
> - DockHelper
> - DolbyDigitalEncoder(FinalCutPro)
> - DropboxFinderExtension
> - EasyPlanarTracker
> - EasyPointTracker
> - EscrowSecurityAlert
> - ExternalQuickLookSatellite-x86_64
> - ExternalQuickLookSatellite-x86_64
> - familycircled
> - fileproviderd
> - FinalCutPro
> - Finder
> - findmydevice-user-agent
> - fmfd
> - FMIPClientXPCService
> - FolderActionsDispatcher
> - followupd
> - fontd
> - fontworker
> - Frame.io
> - FrameIOHelper
> - FxFactory
> - FxFactoryService(FinalCutPro)
> - FxPlugCinemaGradePlugin
> - homed
> - icdd
> - iCloudNotificationAgent
> - iconservicesagent
> - identityservicesd
> - imagent
> - IMAutomaticHistoryDeletionAgent
> - IMDPersistenceAgent
> - imklaunchagent
> - IMRemoteURLConnectionAgent
> - IMRemoteURLConnectionAgent
> - IMRemoteURLConnectionAgent
> - IMRemoteURLConnectionAgent
> - IMTranscoderAgent
> - InternalFiltersXPC
> - iStatMenusStatus
> - iStatMenusAgent
> - itunescloudd
> - keyboardservicesd
> - KeychainCircleNotification
> - knowledge-agent
> - localizationswitcherd
> - LocationMenu
> - lockoutagent
> - loginitemregisterd
> - loginwindow
> - lsd
> - MailCacheDelete
> - maild
> - mapspushd
> - Markup(Mimestream)
> - mdbulkimport
> - mdworker
> - mdwrite
> - media-indexer
> - mediaremoteagent
> - MessagesBlastDoorService
> - MessagesBlastDoorService
> - MIDIServer
> - Mimestream
> - MimestreamNetworking
> - MimestreamWebContent
> - MimestreamWebContent
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MTLCompilerService
> - MusicCacheExtension
> - mUtilityXPCService(FinalCutPro)
> - nbagent
> - ndoagent
> - neagent
> - networkserviceproxy
> - newsd
> - NewsToday2
> - NotificationCenter
> - nsurlsessiond
> - org.sparkle-project.InstallerStatus
> - OSDUIHelper
> - parsecd
> - PasswordBreachAgent
> - pboard
> - pbs
> - PFS_INSL
> - PFSAutoTracker
> - photoanalysisd
> - photolibraryd
> - pkd
> - PlugInLibraryService
> - PlugInLibraryService
> - PlugInLibraryService
> - PlugInLibraryService
> - PlugInLibraryService
> - PlugInLibraryService
> - PlugInLibraryService
> - PodcastContentService
> - printtool
> - PrintUITool
> - progressd
> - promotedcontentd
> - ProtectedCloudKeySyncing
> - QuickLookSatellite
> - QuickLookSatellite
> - QuickLookUIService(com.apple.appkit.xpc.openAndSavePanelService(FinalCutPro))
> - QuickLookUIService(com.apple.appkit.xpc.openAndSavePanelService(Frame.io))
> - QuickLookUIService(PID595)
> - rapportd
> - rcd
> - recentsd
> - RegisterProExtension
> - remindd
> - RemindersWidgetExtension
> - replayd
> - ReportCrash
> - reversetemplated
> - routined
> - SafariBookmarksSyncAgent
> - SafariCloudHistoryPushAgent
> - SafariLaunchAgent
> - SafeEjectGPUAgent
> - SafeEjectGPUService
> - ScopedBookmarkAgent
> - ScreenTimeAgent
> - ScreenTimeWidgetExtension
> - searchpartyuseragent
> - secd
> - secinitd
> - sharedfilelistd
> - sharingd
> - SidecarRelay
> - Siri
> - siriknowledged
> - SiriNCService
> - SoftRAID_Monitor
> - SoftwareUpdateNotificationManager
> - spindump_agent
> - Spotlight
> - StocksWidget
> - storeaccountd
> - storedownloadd
> - studentd
> - suggestd
> - swcd
> - SystemUIServer
> - talagent
> - tccd
> - TemplateStopper
> - TextInputMenuAgent
> - TextInputSwitcher
> - translationd
> - transparencyd
> - triald
> - trustd
> - TrustedPeersHelper
> - TVCacheExtension
> - UIKitSystem
> - universalAccessAuthWarn
> - UsageTrackingAgent
> - USBAgent
> - useractivityd
> - UserEventAgent
> - usernoted
> - UserNotificationCenter
> - ViewBridgeAuxiliary
> - VTEncoderXPCService
> - Wallet
> - WeatherWidget
> - Wi-Fi
> - WiFiVelocityAgent
> - WorldClockWidget
> - XprotectService

**Comment by latenitefilms** [comment]
Joseph writes:

> oh! This is exciting!
> 
> I recreated my workspace (for the millionth time, but first time since this new update), and now it works! I’m pretty sure I didn’t miss any of my settings.
> 
> I’ve attached the two workspaces — the new one is called “PhotoJoseph” and the old one is called “PhotoJoseph broken”. I haven’t compared their XML to see if I can see what’s different, but so far, the new one works! I’ve relaunched FCP (only once), but it worked through that. 
> 
> Fingers crossed!!! You may have fixed it!
> -Joseph 
> 

[PhotoJoseph-Workspaces.zip](https://github.com/CommandPost/CommandPost/files/6620473/PhotoJoseph-Workspaces.zip)
