### ISSUE TITLE
Create script for generating the delivery DMG

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#27]
Having a simple script to create the DMG for delivering on a version of the script will be useful.

**Comment by latenitefilms** [comment]
I think this is a great idea if you're up for tackling. Maybe using something like [this](https://github.com/andreyvit/create-dmg)?

**Comment by randomeizer** [comment]
Yeah, I've been toying with it today, using this tool so far:

https://github.com/LinusU/node-appdmg

However, that one doesn't support displaying a EULA prior to mounting the DMG.

**Comment by randomeizer** [comment]
By the way, what did you use to create the background image? Photoshop? Could you send me the original file? I may have to tweak some elements.

**Comment by latenitefilms** [comment]
Here you go: [FCPX Hacks - DMG Background.zip](https://github.com/fcpxhacks/fcpxhacks/files/614077/FCPX.Hacks.-.DMG.Background.zip)

**Comment by randomeizer** [comment]
Thanks. I've found a script to add the EULA as well.

**Comment by randomeizer** [comment]
I've created a script for building the DMG file from the source, with instructions in the README.
