### ISSUE TITLE
Loupedeck+ encoders send double values

### ISSUE THREAD

**Issue by davvidavvi** [fcpxhacks/fcpxhacks#2717]
Using a Loupedeck+ scroll wheel (P1 Wheel) to adjust volume on a selected clip. The down action is **Adjust Volume Down (-1 dB)**, the up action is **Adjust Volume Up (+ 1dB)**. In practice, volume is adjusted by 2 dB because Loupedeck+ sends a value twice for every "click" on the scroll wheel. Same is true for the big Control Dial.

**Comment by latenitefilms** [comment]
Thanks for reporting!

I can't reproduce this on the Control Dial, but I can on the P1 to P8 controls.

It could just be dodgy hardware. I'm using model "LD+", version "02.32". I also have an original Loupedeck, but it's not currently with me to test.

I'll have a think about the best way to tackle.

**Comment by davvidavvi** [comment]
🙌 Thank you kindly for looking into this. (The model I've got is 02.50).
