### ISSUE TITLE
Add basic audio control to Monogram

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2744]
Drew Boyd suggests:

> Hi all - please consider my request to work with Command Post to offer robust inputs for the sliders within FCPX (Volume, Effect Mix, etc.) for selected clips.
> 
> I purchased the slider panel thinking it would be useful for FCPX audio work, but have found it lacking in the early stage.
> 
> Otherwise, great products!

**Comment by andyjhayes** [comment]
Adding related comments from other Monogram + CommandPost users:

> For FCPX, it would be very usefull to set an adjustement for audio level in clip with dials or sliders.

[Shared via Monogram community forum](https://support.monogramcc.com/hc/en-us/community/posts/4405365442957)

> [the FCP + CommandPost integration] could benefit from surround panner support where the dial or orbiter is controlling amount and position

(Shared via a 1:1 email thread)

**Comment by latenitefilms** [comment]
Luke Goodall writes:

> What feature would you like to see implemented or improved?
> Hey Chris and the Command Post Team. Love your work. I have a suggestion for a future update. Or if there’s already a way to do it, please let me know.
> 
> I have the Monogram CC and was glad to see the audio level volume (1DB up and down) added to the Essential Keys Module but was wondering if it was possible to adjust audio much smoother and intuitively by using the Dial module instead. Much in the same way it can control the overall volume of my Mac. It would speed up my process a heap! 
> 
> Thanks again! Loving this so far.
