### ISSUE TITLE
Issue in Batch Export with "Select Clip"

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2814]
Kevin writes:

> Command post batch exports select the range under my mouse instead of the first clip
> 
> I just need to move my mouse away from the timeline, somehow select clip prefers the clip under the mouse rather than next to the playhead

**Comment by kevinluk07** [comment]
The cursor does moves to the correct clip while doing selections in Monterey, while the erronous behaviour was observed in Big Sur. Both machine is running FCPX 10.5.4 and Command Post 1.2.16 (7028)

**Comment by kevinluk07** [comment]
> The cursor does moves to the correct clip while doing selections in Monterey, while the erronous behaviour was observed in Big Sur. Both machine is running FCPX 10.5.4 and Command Post 1.2.16 (7028)

Looks like that was luck. Also happens in Monterey.

**Comment by randomeizer** [comment]
Without looking at the code, my guess is that we are using the Select under Playhead command, which picks up the mouse is the skimmer is active. Probably need to temporarily turn off skimming during the operation, and restore it at the end, similar to "Mark All Clips".

**Comment by latenitefilms** [comment]
I can't see anything obvious in the code where skimming would have an impact. I also can't see how skimming is turned off in "Mark All Clips"?
