### ISSUE TITLE
Option to invert timeline zoom redirection in FCP

### ISSUE THREAD

**Issue by dutchct** [fcpxhacks/fcpxhacks#2820]
In my system preferences, I've chosen to reverse my mouse scroll direction to match that of a windows machine.

I'm assuming this is causing command post to zoom the timeline in the opposite direction as most other apps.

Would be great to have a reverse direction on this.

Thanks!

**Comment by latenitefilms** [comment]
@dutchct - Are you talking about the "Enable Timeline Zooming with Mouse Scroll & Modifier Key" option in the Final Cut Pro preferences panel? In theory, this should respect your macOS scroll direction settings - but I can foresee a use-case where you might want to do the opposite of what macOS does, so I'll look into adding a new preference.

**Comment by dutchct** [comment]
Yes, I see that and I love the fact that it exists! It's just that for me, the zoom direction is opposite to what I would expect.

I've been messing around with it a little more, would it also be possible to adjust the step size? At the higher zoom levels (closer to the timeline) the zoom steps are quite large.
