### ISSUE TITLE
Add support for the DaVinci Resolve Speed Editor

### ISSUE THREAD

**Issue by dutchct** [fcpxhacks/fcpxhacks#2821]
Basically, I'm moving from resolve, I've got the speed editor, but it only works in resolve.

I'd loooove to see this thing working in FCP!

**Comment by latenitefilms** [comment]
I've looked into this extensively, and unfortunately, it's simply not possible. Blackmagic has locked down the Speed Editor fairly significantly, and uses a token based authentication system to ensure it only works with Resolve. The only possibilities are if Blackmagic opens things up (very unlikely) or someone creates some custom firmware for the device (also very unlikely). Sorry!

**Comment by latenitefilms** [comment]
@dutchct - Scrap that... some genius solved the authentication. We'll add support for the Speed Editor ASAP.

**Comment by dutchct** [comment]
> @dutchct - Scrap that... some genius solved the authentication. We'll add support for the Speed Editor ASAP.

Ohh boy! Excited!

**Comment by sd-ditoy** [comment]
> @dutchct - Scrap that... some genius solved the authentication. We'll add support for the Speed Editor ASAP.

@latenitefilms - Any chance you could share this information? I'm currently looking into building a simple windows app for myself and really would like to know how you solved the authentication/token exchange.

**Comment by latenitefilms** [comment]
Everything is open-source, so feel free to explore the code!

**Comment by rixnco** [comment]
> > @dutchct - Scrap that... some genius solved the authentication. We'll add support for the Speed Editor ASAP.
> 
> @latenitefilms - Any chance you could share this information? I'm currently looking into building a simple windows app for myself and really would like to know how you solved the authentication/token exchange.

@sd-ditoy Didi you made any progress ? I'm also trying to customize the speed editor on windows. Any hint or info I could use to "enable" the communication with the speed editor?

**Comment by latenitefilms** [comment]
@rixnco - Everything is open-source, so feel free to explore the code!

**Comment by rixnco** [comment]
> @rixnco - Everything is open-source, so feel free to explore the code!
Hi Chris,
I couldn't find anything related to low-level interaction with the Speed Editor in this repository.
I finally found out that what interested me was in the CommandPost-App repository and based on Sylvain Munaut's work.
Thanks.

**Comment by boehs** [comment]
> I finally found out that what interested me was in the CommandPost-App repository and based on Sylvain Munaut's work.

Thanks, this is a direct link!

https://github.com/CommandPost/CommandPost-App/tree/039f03e8132121f5da92e97ec33130a68cf9ab95/extensions/blackmagic
