### ISSUE TITLE
Actions for Controlling Audio Channels in the Inspector

### ISSUE THREAD

**Issue by danielsti** [fcpxhacks/fcpxhacks#2830]
I already tried to find out the code for changing things like PanMode or activating only ch 1 or ch2. But I could not find the right command. 
I tried using parts of this code:

cp.apple.finalcutpro.inspector.audio:show()

**Comment by latenitefilms** [comment]
We'll add this as built-in actions, however in the meantime, you can change the pan mode via:

```lua
cp.apple.finalcutpro.inspector.audio:pan():mode().value:doSelectValue("Music"):Now()
```

Activating Components SHOULD be possible with:

```lua
cp.apple.finalcutpro.inspector.audio.audioConfiguration:component(1):enabled():doPress():Now()
```

...however it looks like there's a bug preventing this. This is fixed in #2833, and will be included in the next update.
