### ISSUE TITLE
Move Final Cut Pro Language Options to Top of Menubar

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#288]

**Comment by randomeizer** [comment]
Top of menu bar? Why there?

**Comment by latenitefilms** [comment]
Surprisingly, a lot of users seem switch between English & other languages on a regular basis. I would have assumed that you'd pick a language and stick to it - but I think a lot of Final Cut Pro plugins and effects have lots of bugs when not in English, so people switch back and forth when they need to.

Putting it on the top of the menubar, just makes it easier to access.

**Comment by randomeizer** [comment]
Fair enough.
