### ISSUE TITLE
Control Surface Settings: Device images displayed 4 times

### ISSUE THREAD

**Issue by archetyped** [fcpxhacks/fcpxhacks#2887]
Some device images are being displayed as 4 smaller images instead of a single larger image in the Control Surfaces settings dialog.

As a result, the clickable areas for the device's controls do not align with the device image.

## Details

* CP: 1.3.1
* Mac OS: 12.3
* Affected devices:
    * Resolve Speed Editor
    * TourBox
    * Razer Tartarus

## Screenshot

![CP_1 3 1_Control Surfaces_Resolve_Issue_Device-Image](https://user-images.githubusercontent.com/3237917/160898158-189e541d-b300-41d1-88b3-91d264d1e842.png)

**Comment by latenitefilms** [comment]
Can you please share a screenshot of the Debug Console (click the CommandPost dock icon) and something is clearly breaking?

**Comment by archetyped** [comment]
```
CommandPost v1.3.1 (Build: 7250)

Build Date:                     Mar 30 2022, 17:54:13
macOS Version:                  12.3.0
CommandPost Locale:             en_US
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.6.1
Final Cut Pro Language:         en
Developer Mode:                 false

2022-03-30 10:06:02: 2022-03-30 10:06:02: -- Loading /Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2022-03-30 10:06:02: 10:06:02         cp:     Loading Plugins...
2022-03-30 10:06:04: 10:06:04    plugins:     Plugin disabled: 'textedit.application.manager'
2022-03-30 10:06:04:                          Plugin disabled: 'core.menu.menuaction'
2022-03-30 10:06:05: 10:06:05                 Plugin disabled: 'ecammlive.application.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'ciscowebexmeetings.application.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'aftereffects.preferences'
2022-03-30 10:06:05:                          Plugin disabled: 'aftereffects.tangent.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'aftereffects.shortcuts'
2022-03-30 10:06:05:                          Plugin disabled: 'aftereffects.application.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'aftereffects.effects'
2022-03-30 10:06:05:                          Plugin disabled: 'zoom.shortcuts'
2022-03-30 10:06:05:                          Plugin disabled: 'zoom.application.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'skype.shortcuts'
2022-03-30 10:06:05:                          Plugin disabled: 'skype.application.manager'
2022-03-30 10:06:05:                          Plugin disabled: 'microsoftteams.application.manager'
2022-03-30 10:06:05:                  cp:     Plugins Loaded.
2022-03-30 10:06:05:                          Startup Time: 3.159614 seconds
2022-03-30 10:06:05:                          Garbage Collection Mode: generational
2022-03-30 10:06:05: -- Done.
```

**Comment by latenitefilms** [comment]
Is this the contents of the Debug Console after you've opened the Control Surfaces page and things aren't working?

It looks like you've disabled a lot of plugins, that MIGHT be related - but there's no obvious errors in the Debug Console.

**Comment by archetyped** [comment]
Yes, there is no additional console output when the Control Surfaces settings are opened and the affected pages are interacted with.

**Comment by latenitefilms** [comment]
That's very strange. The interface is basically just a HTML page using WebKit. Do you have any Safari Extensions that might be overriding the CSS styles?

**Comment by latenitefilms** [comment]
Do the Loupedeck panels look correct?

**Comment by archetyped** [comment]
Yes, all Loupedeck device images are displaying correctly.

Only the control surface pages listed under "Affected devices" in the first post are affected.

**Comment by latenitefilms** [comment]
Great, thanks! I'll try and push out a fix soon.

**Comment by latenitefilms** [comment]
This should be fixed in the latest update. If not, please re-open this issue and let me know.

**Comment by archetyped** [comment]
> That's very strange. The interface is basically just a HTML page using WebKit. Do you have any Safari Extensions that might be overriding the CSS styles?

No change to control surface pages after Safari extensions disabled and CP restarted.

Is there a way to inspect the generated HTML/CSS of a webview in CP (like a browser's dev tools)?

**Comment by latenitefilms** [comment]
Is that after installing the latest update?

**Comment by archetyped** [comment]
Sorry, posted reply to your earlier message before seeing your latest update.

v1.3.2 fixes the repeating of the image, but the image remains quite blurry:
![CP_1 3 2_Control Surfaces_Resolve_Issue_Device-Image](https://user-images.githubusercontent.com/3237917/160953644-f9ecd21b-7d17-42eb-b993-144f6beb9716.png)

**Comment by archetyped** [comment]
Should I create a new issue for the display issue?

**Comment by latenitefilms** [comment]
All good - I'll have a look at it. It's just a single PNG, so hopefully I can just swap it out with something higher resolution - making sure it matches the original sizing so everything still lines up. FYI - Here's the image:

https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/controlsurfaces/resolve/prefs/images/speededitor.png

Feel free to have a play at replacing it out yourself in the app's package contents if you want in the meantime.

**Comment by archetyped** [comment]
What's strange is that the source image is perfectly legible, but the quality is significantly lower when displayed in the settings page.

Is there a way to inspect the generated HTML/CSS of a webview in CP (like a browser's dev tools)?  If so, I would be glad to take a closer look.

**Comment by latenitefilms** [comment]
To turn on "developer mode" you'd need to manually change this line within your application bundle:

https://github.com/CommandPost/CommandPost/blob/c4c6f8233ee6f61325b72714b394686c1728f593/src/extensions/cp/config/init.lua#L307

You should be able to change "~=" to "==". You can then right click on the webviews.

Alternatively you can see the (terrible) HTML here:

https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/core/controlsurfaces/resolve/prefs/html/panel.html

**Comment by latenitefilms** [comment]
AFAIK we shouldn't be scaling the image, but maybe it's worth playing with these CSS settings:

https://www.w3schools.com/cssref/css3_pr_image-rendering.asp

**Comment by latenitefilms** [comment]
Note to self:

https://stackoverflow.com/a/31930690

**Comment by archetyped** [comment]
Looks like the image's dimensions are being cut in half for some reason.

```lua
print(hs.inspect.inspect(i:size()))
```

Adding the above snippet to `insertImage()` reports:

```
 h = 241.0,
 w = 223.49999362792
```

Which is half of the source image's actual dimensions:

```
  h = 482,
  w = 447
```

**Comment by archetyped** [comment]
Ah, the image's DPI is set to 144dpi. The correct dimensions are reported when using a copy of the image set to 72dpi.

**Comment by latenitefilms** [comment]
Setting `image-rendering` to `-webkit-optimize-contrast` does make some kind of minor visible difference.

**Comment by archetyped** [comment]
It looks like the pixel dimensions of an image object (using `imageFromPath()`, `imageFromURL()`, etc.) are affected by DPI metadata in the source file.  If a DPI higher than 72 is set, then the pixel dimensions of the image object are reduced.

For example, the Speed Editor image is set to 144DPI, causing the pixel dimension to be cut in half (144/2 = 72).  As a result, you end up with a 224px x 241px image that is being forced to display at 200% its size (447px x 482px).

This is the reason why the image quality is decreased compared to the source image.  The reduced pixel dimensions have been confirmed by inspecting the data URI generated by `encodeAsURLString()`.  Unfortunately, no amount of CSS can improve such a downsized image to match the original.

I haven't been able to find any, but if CP has a way to inspect file metadata, then the image's DPI can be determined (e.g. via the `PixelsPerUnitX`/`PixelsPerUnitY` metadata fields) and accommodated for.

Alternatively, removing the DPI metadata from the images used by CP will ensure that image objects generated from these files have the same pixel dimensions.  You can test this by replacing CP's Speed Editor image with this one:
![speededitor](https://user-images.githubusercontent.com/3237917/161361718-b659d47d-0ac4-4b51-8cb7-9789357d34ff.png)

Note: This is on a non-retina device, so testing on device with a retina display may be necessary to determine if the results are the same.

**Comment by latenitefilms** [comment]
Thanks for all your investigation work! 

I've replaced the image with a 894x964 @ 72dpi PNG which looks better. I'll push it out in the next update, so we'll see what you think.

I'm assuming it was you that crashed CommandPost with `hs.image.getExifFromPath()`? This will be fixed in Hammerspoon/CommandPost in the next update too!

https://github.com/Hammerspoon/hammerspoon/pull/3177

**Comment by archetyped** [comment]
Thanks! In case this wasn't previously noted, the image DPI/low-quality display issue appears to be present on all other control surface settings pages that use a device image (Loupedeck, Razer, etc.), so those images may need to be replaced as well.

> I'm assuming it was you that crashed CommandPost with `hs.image.getExifFromPath()`? This will be fixed in Hammerspoon/CommandPost in the next update too!

Yes, it probably was when I inadvertently used the wrong path and CP crashed instead of returning `nil`. Thanks for pushing a fix upstream 👍

**Comment by latenitefilms** [comment]
Thanks! To be honest, it's probably low-priority for now, as you're the first one to ever notice/tell us, but I've added it to the to-do list so we'll have a look at some point. I've created a new issue for this. Thanks again for all your help!!

**Comment by archetyped** [comment]
> you're the first one to ever notice/tell us

I'm guessing that's probably because the other pages using device images (e.g. Razer Tartarus) have a base device image that is overlaid with images of the various buttons.  The background device image contains DPI metadata, while the individual button images do not.

As a result, though the base device image is low-quality (1/4 the resolution of the original), it is mostly obscured by the button images which are displayed at their original quality.

If you can provide the sources where you got the device images, I would be glad to submit a PR with the corrected image dimensions and metadata.

**Comment by latenitefilms** [comment]
That would be amazing! If you’ve looked at the HTML/CSS, you can clearly see I have no idea what I’m doing - so a pull request is always welcome!

I’m not sure I have the original files - I would have just Googled “Loupedeck+ Transparent PNG” or similar.

The preferences panels code gets SLIGHTLY better with each new Control Surface I add. We definitely don’t need individual button images - replacing the background image makes way more sense, and will reduce the overall CommandPost App size, which is always a bonus.

Good luck! Yell out if you have any questions!
