### ISSUE TITLE
Add support for reading NIBArchive format

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#2914]
Some documentation: https://github.com/matsmattsson/nibsqueeze/blob/master/NibArchive.md

**Comment by latenitefilms** [comment]
**Final Cut Pro 10.6.1:**
<img width="321" alt="FCPX 10 6 1 - 1 - Final Cut Pro" src="https://user-images.githubusercontent.com/22286696/163066246-02a20011-45fb-4de0-b110-4fb4aee5f0f7.png">
<img width="511" alt="FCPX 10 6 1 - 2 - File" src="https://user-images.githubusercontent.com/22286696/163066252-d32b282a-a422-494a-8f15-38e5f4301000.png">
<img width="314" alt="FCPX 10 6 1 - 3 - Edit" src="https://user-images.githubusercontent.com/22286696/163066255-313fc01d-060a-40dc-b114-b593c7bf4059.png">
<img width="242" alt="FCPX 10 6 1 - 4 - Trim" src="https://user-images.githubusercontent.com/22286696/163066256-deb43bac-05d1-4781-8254-c497d8470292.png">
<img width="559" alt="FCPX 10 6 1 - 5 - Mark" src="https://user-images.githubusercontent.com/22286696/163066258-9f9153b5-0ab7-4d30-aac9-c056c77c9cd6.png">
<img width="535" alt="FCPX 10 6 1 - 6 - Clip" src="https://user-images.githubusercontent.com/22286696/163066264-7696b629-20bf-4a1e-b762-224b9ed348e4.png">
<img width="656" alt="FCPX 10 6 1 - 7 - Modify" src="https://user-images.githubusercontent.com/22286696/163066268-a38b1f90-9fe2-4c35-bc19-908ba3c744ca.png">
<img width="525" alt="FCPX 10 6 1 - 8 - View" src="https://user-images.githubusercontent.com/22286696/163066272-c76d38c4-2097-4eb5-8eb8-a23263960e99.png">
<img width="338" alt="FCPX 10 6 1 - 9 - Window" src="https://user-images.githubusercontent.com/22286696/163066275-145e9456-cd07-418a-85f3-219eb18c4980.png">
<img width="404" alt="FCPX 10 6 1 - 10 - Help" src="https://user-images.githubusercontent.com/22286696/163066278-2a04c816-a605-480c-ac8a-5b888af3a3d2.png">

**Final Cut Pro 10.6.2:**
<img width="317" alt="FCPX 10 6 2 - 1 - Final Cut Pro" src="https://user-images.githubusercontent.com/22286696/163066310-328584d8-6f98-4c58-ba43-347c71394c51.png">
<img width="545" alt="FCPX 10 6 2 - 2 - File" src="https://user-images.githubusercontent.com/22286696/163066319-d46fa65b-356b-4bb4-acd7-0b9c81f576b9.png">
<img width="305" alt="FCPX 10 6 2 - 3 - Edit" src="https://user-images.githubusercontent.com/22286696/163066325-ab8ef7ca-ec4d-425b-a62e-b6cb48d50c26.png">
<img width="244" alt="FCPX 10 6 2 - 4 - Trim" src="https://user-images.githubusercontent.com/22286696/163066332-874da43a-4110-49b9-bb3d-3e0e50995e69.png">
<img width="575" alt="FCPX 10 6 2 - 5 - Mark" src="https://user-images.githubusercontent.com/22286696/163066333-16bb5194-5311-4ae3-8adc-271f094c8acc.png">
<img width="541" alt="FCPX 10 6 2 - 6 - Clip" src="https://user-images.githubusercontent.com/22286696/163066338-2d45b757-6dbb-4f68-bc32-b626735781ec.png">
<img width="657" alt="FCPX 10 6 2 - 7 - Modify" src="https://user-images.githubusercontent.com/22286696/163066343-ea0956b8-8c50-400f-8763-59944d0c7b31.png">
<img width="533" alt="FCPX 10 6 2 - 8 - View" src="https://user-images.githubusercontent.com/22286696/163066345-5a299b68-6eef-4c33-b880-5a200427b416.png">
<img width="324" alt="FCPX 10 6 2 - 9 - Window" src="https://user-images.githubusercontent.com/22286696/163066347-6e0135c1-802d-4c86-9d35-703ec8221ee8.png">
<img width="393" alt="FCPX 10 6 2 - 10 - Help" src="https://user-images.githubusercontent.com/22286696/163066348-8b7c802c-5d8f-4f03-8233-272a447ccfdc.png">

**Comment by latenitefilms** [comment]
Fixed in #2928
