### ISSUE TITLE
Update cp.app to detect correct language when adjusted in System Preferences

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2948]
Sam Pluemacher reports:

> I did a complete reinstall of FCP after the latest FCP update came out, but immediately set it to english through system preferences. So I never use it in german.

Turns out you can actually set the language for specific applications in System Preferences!

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22286696/164202513-1c5675f9-95ca-47cd-99fc-9513e4cd0085.png">

When you set it to German (for example)...

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22286696/164204021-3f36e486-cfdf-4e18-9d59-d9b9008cec6d.png">

...it updates the Final Cut Pro preferences file as such:

<img width="233" alt="image" src="https://user-images.githubusercontent.com/22286696/164203870-c1ddab86-f0e9-47cd-86bc-985622a8b64f.png">

Currently `cp.app` doesn't allow for this.

**Comment by latenitefilms** [comment]
It looks like the issue is that `cp.i18n.localeID` is expecting something like `en_AU` and not `en-AU`, which is causing things to break.

```lua
> require("cp.i18n.localeID").parse("en-AU")
nil	nil	nil

> require("cp.i18n.localeID").parse("en_AU")
en	AU	nil
```

**Comment by latenitefilms** [comment]
Looks like we should be treating them as “Language IDs” rather than “Locale IDs”.

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

**Comment by latenitefilms** [comment]
This seems to fix things in this particular case, but unsure if it'll break other things:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/22286696/164215218-27ef088e-d77f-4d41-933b-50bf99778bcc.png">

**Comment by randomeizer** [comment]
Yeah, it will definitely need to support both "_" and "-". However, not sure if it should be tweaking this (which is correctly parsing locale IDs) to also support language IDs, or if I should add a specific Language ID parser as well.

**Comment by randomeizer** [comment]
Ok, so there is already a `languageID` parser. We just need to use that to parse `AppleLanguages`, then use the `languageID:toLocaleID()` method to convert it as required.

**Comment by randomeizer** [comment]
I've pushed a fix for this which I believe fixes the `AppleLanguages` issue. Not sure if there are any other edge cases this affects.

**Comment by latenitefilms** [comment]
@randomeizer - Interesting, that fix doesn't work for Chinese, when set via System Preferences.

For example, the only option in System Preferences is "Chinese, Simplified":

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22286696/164332325-8369f83a-88a0-4663-9536-b1a4ec92d393.png">

<img width="289" alt="image" src="https://user-images.githubusercontent.com/22286696/164333425-60927c89-b4ff-4c9b-8ee4-498c1b585638.png">

...which actually uses:

```lua
> hs.inspect(cp.apple.finalcutpro.preferences.AppleLanguages)
{ "zh-Hans-AU", "en-AU" }
```

...even though FCPX uses "zh_CN" internally.

This value doesn't parse correctly as a language ID or a locale ID:

```lua
> require("cp.i18n.languageID").parse("zh-Hans-AU")
nil	nil	nil

> require("cp.i18n.localeID").parse("zh-Hans-AU")
nil	nil	nil
```

I wonder if instead of parsing the the language/locale ID's ourselves, we should just use `hs.host.locale.details()`?
