### ISSUE TITLE
Add Setup Panel for macOS Shortcuts

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#2954]
When opening the Search Console for the first time, it says "Loading...", and pauses. Upon force quitting CP, discovered a System Prefs prompt asking about access to Shortcuts, which then disappeared.

**Comment by randomeizer** [comment]
Looking through the `hs.chooser` API, I can't see an obvious way of changing the Z level of a Chooser instance. I think the options are either to add such a parameter to `hs.chooser`, or to hide the chooser while it's loading for the first time?

**Comment by latenitefilms** [comment]
Normally the permission box appears on top, however I wonder if we should just ask for Shortcuts permissions during the initial setup? There's a heap more permission dialogues in Monterey - FCPX asks three or four times for different things.

**Comment by randomeizer** [comment]
Yeah, should probably be in setup. What plugin(s) are using Shortcuts?

**Comment by randomeizer** [comment]
I'd also say that perhaps whatever Action loader is triggering the shortcut prompt should not trigger it - just bail if permission has not been granted.

**Comment by latenitefilms** [comment]
I don't believe it's possible to "detect" whether or not you have app-specific permissions. You get once chance at triggering and user accepting it.

This is where it's triggered:

https://github.com/CommandPost/CommandPost/blob/ce371173dd0fe37939d6609b93811e1dda0bf515/src/plugins/core/macosshortcuts/init.lua#L35

**Comment by randomeizer** [comment]
So how do we run it on startup, other than just running it? With our other permissions, we can push a Setup panel if it's not currently enabled. Here, hard to tell without triggering the permission.

**Comment by latenitefilms** [comment]
The only way I can think of doing it is having a dialogue before the Accessibility Dialog that explains that a popup will appear, and what to do if you don't give it permission now but want to later. This would just have to be a "one off" popup - as there's no way we can determine if the popups ever happened, or if you actually have permission or not (as far as I know).

Given there's so many other popups like this though, I'm tempted to just leave it as-is for now. I do a fresh install of CommandPost fairly regularly, and the Shortcuts permission popup is normally pretty obvious. I also don't imagine there's a lot of people actually using the Shortcuts actions, so it's probably not the end of the world is they don't accept the permissions. Whether or not you actually acknowledge the popup shouldn't really have any impact on CommandPost.

**Comment by randomeizer** [comment]
I don't use it either. The problem I has was that I activated the Search Console, the app basically froze, and I couldn't tell it was because the permissions dialogue was blocked by the search dialogue.

Perhaps the fix is to have Shortcuts support turned off by default, and you have to enable it for it to show up, in which case we prompt them when it's enabled. Could be via a  setup panel and/or a checkbox in Preferences.
