### ISSUE TITLE
Add ability to include timeline timecode in Timeline Batch Export Custom Name

### ISSUE THREAD

**Issue by Stooovie** [fcpxhacks/fcpxhacks#2970]
Hi, I would love a feature that would export selected clip/range from timeline, adding the in-point timecode into the filename. This would be tremendously useful for one-man-band VFX jobs to make FCPX-After Effects roundtrips easier - I don't always work with scene/shot numbers so I rely on TC to place the newly created VFX back onto the FCPX timeline.

**Comment by latenitefilms** [comment]
@Stooovie - Are you talking about the source/clip timecode or the project/timeline timecode?

The "Custom Filename" feature in Timeline Batch Export already supports these variables:

Please enter a custom filename below.

You can also use these optional variables:

```
{original} = Original Clip Name
{yyyy} = Year
{yy} = Year
{mm} = Month
{dd} = Day
{hh} = Hour
{mm} = Minutes
{ss} = Seconds
```

...so it's POSSIBLE we could also support source timecode and/or timeline timecode.

**Comment by Stooovie** [comment]
I'm sorry I mean the project/timeline TC, yes. So when I get the file back from AE (usually with a suffix like 01:34:33:00-VFX.mov, I know where to put it on the FCPX TL.
