### ISSUE TITLE
Custom shortcuts to Saved Effect Presets

### ISSUE THREAD

**Issue by Gabby16Bitbox** [fcpxhacks/fcpxhacks#2985]
I have found the possibilty to use shortcuts to effects which is amazing, but when i create a custom preset for one effects i can't find it on the CP Menu or add a shortcut to it

*update*
I noticed that sometimes it works, i can in fact use custom effects, but the way it reconizes it, is random. I don't know how to make it work after i just saved one.

I would like a lot this option.

**Comment by latenitefilms** [comment]
After you add a new "Effects Preset" you may have to press the "Scan Motion Templates" button within the Final Cut Pro preferences panel within CommandPost for it to appear in the Search Console:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22286696/169749651-c399f92e-116a-4a35-8750-70c0d6fdf4af.png">
