### ISSUE TITLE
Timeline section disappeared from Command Post

### ISSUE THREAD

**Issue by Gabby16Bitbox** [fcpxhacks/fcpxhacks#2986]
i don't know why that happened, but i cannot find anymore the timeline option from the Command Post menu *screenshot attached* 
![Schermata 2022-05-22 alle 14 11 24](https://user-images.githubusercontent.com/105720077/169695724-fce9d38c-bd4d-454b-a93e-0e0724fa45f8.png)
is there a way to have it back? I also noticed that since it disappeared, when i use the Scrolling Timline shotcut it activates but is not working anymore, and i can't also zoom in the timeline with mouse wheel. Tried to reinstall CP and delete most of my apps but to no anvil
Any help?

**Comment by randomeizer** [comment]
Hi there. The Final Cut Pro-specific items will only be visible when Final Cut Pro is the active application. Try ensuring that it is focused, then check the menu again.

**Comment by latenitefilms** [comment]
I'm going to close this issue, but just yell out if you're still having problems!

**Comment by Gabby16Bitbox** [comment]
@latenitefilms I still can't use the scroll wheel to zoom (tried everything and when i just installed the mac it was functional with CP) for some weird reason, but the rest worked, thanks!
