### ISSUE TITLE
Hammerspoon causes system-wide lag?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#303]
See:

> My main issues are lag and even worse missed keystrokes/mouse clicks, not just in FCPX but seemingly system wide.
> Example : Space bar on playback - sometimes I go through about 30 seconds before it works and I’m pressing it regularly. 
> Some keyboard shortcuts every now and then don’t work at first then do, or, I’ll hit something, it doesn’t work, I hit it again and then
> Everything catches up and runs it twice, returning back to square one or needing to undo work.

```
-----------------------------
| FCPX Hacks v0.78          |
| Created by LateNite Films |
-----------------------------
Hammerspoon Version:            0.9.52
macOS Version:                  10.12.3
Final Cut Pro Version:          10.3.2
Final Cut Pro Language:         en
FCPX Hacks Locale:              en_GB
Current Keyboard Layout:        British
Final Cut Pro Path:             /Applications/Final Cut Pro.app
```

**Comment by latenitefilms** [comment]
Every now and again, I also notice this "lagging" on my machine (macOS 10.12.2). 

For example, every now and again, I'll notice that typing things in other apps (Safari, Mail, Pages, etc.) is a bit laggy. Closing Hammerspoon and/or CommandPost-App instantly fixes things. If I then re-load Hammerspoon/CommandPost-App, the lagging isn't there anymore.

I wonder if this is a Sierra thing? Have you noticed similar issues @randomeizer ?

**Comment by randomeizer** [comment]
Yeah, I have noticed from time to time. My (unproven) guess is that it may be either timer/watcher/eventtap related. We have a lot of little loops running in the background watching for events, and I suspect they may get jammed up from time to time.

It's a bit hard to narrow down exactly what the specific one (if it is just one) would be, but we can do some testing with plugins that do watching/etc, disable them, see if it resolves the issue. But because it's intermittent, it's hard to prove...

**Comment by latenitefilms** [comment]
I wonder what would happen if we put all the hotkey functions (and menubar functions for that matter) in their own `hs.timer`'s - so that everything runs on it's own "thread", as to not interrupt the main code?

**Comment by randomeizer** [comment]
Not sure if that would be better or worse. But should be fairly simple to
implement - just modify a couple of functions in `cp.commands.command`.

**Comment by latenitefilms** [comment]
Interesting note from one user...

> Ok, here’s the issue then. I had text expander running, closing that made everything work much better. I also closed Alfred incase that was interfering.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as it doesn't really have a specific problem or solution.
