### ISSUE TITLE
Problem with volume adjustment with increments on Loupedeck+

### ISSUE THREAD

**Issue by molnarnoah** [fcpxhacks/fcpxhacks#3052]
Hi! I would like to use the P5 wheel for the volume on Loupedeck+. I use the FCPX shortcut for volume +-1 dB but I want to use the +-0.1 dB feature with modifier key on the same P5 wheel, but when I'm trying it goes straight to -∞. Doesn't matter it's increasing or decreasing. Thank you for your help!

**Comment by latenitefilms** [comment]
@molnarnoah - Sorry, I haven't been able to replicate.

Are you using this action?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/22286696/182740322-8bf6f147-ba9a-4dfd-9701-3b4781702d78.png">

It's working fine here. Does it work correctly if you try assigning it to the Loupedeck+ buttons (as opposed to a knob)?

Are you using one of the "Fn" banks are the "modifier"?

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22286696/182740522-04bb13b7-42ac-42bd-a12b-fbdf79dbc361.png">

**Comment by molnarnoah** [comment]
Yes I'm using the same. I don't know why. Maybe it's somehow connected with the mute button.

**Comment by latenitefilms** [comment]
I was never able to reproduce this. I'm going to close for now, but if you're still having issues @molnarnoah, please reopen and I'll try and find a solution.
