### ISSUE TITLE
Add Shortcut Manager

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#306]
As discussed originally [here](https://github.com/CommandPost/CommandPost/issues/246#issuecomment-275108285), we really need to add a keyboard shortcut manager into CommandPost for those users who are too scared to "Add CommandPost Shortcuts to Final Cut Pro", so they can still customise shortcuts and have full access to all of CommandPost's feature without having to enter an Administrators password.

Some ideas in regards to how the UI could be built have been discussed previously [here](https://github.com/Hammerspoon/hammerspoon/issues/1187#issue-199753143).

I feel like this is something we should add for the initial release of CommandPost, so that EVERY user can have access to all of CommandPost's features - even if initially, it's a pretty basic UI.

Thoughts @randomeizer ?

**Comment by latenitefilms** [comment]
Started in #355.

**Comment by latenitefilms** [comment]
@randomeizer - I've added the ability to customise shortcuts - but it currently doesn't save across restarts. I would think we probably want to add this functionality into `cp.commands` - but I didn't want to do this without your thoughts first.

It's all very much a work-in-progress, but you get the idea.

I do like your idea of being able to have "sets" of keyboard shortcuts, which I also think should be pretty easy to implement. However, I think rather than "loading" the shortcuts from an external file, we should just add an import/export feature to keep things simple.

Thoughts?

**Comment by latenitefilms** [comment]
FYI: I've merged the first attempt of this feature into develop, so at least we have something usable in there, but as discussed above, it's certainly not finished.

**Comment by latenitefilms** [comment]
I wonder if it's worth adding a "table generator" to `cp.web.generate` to "drive" the plugins and shortcuts Preferences panels?

**Comment by latenitefilms** [comment]
Interface Inspiration?

![screen shot 2017-03-29 at 12 17 37 pm](https://cloud.githubusercontent.com/assets/22286696/24434600/55bd8ae8-147c-11e7-86e4-1bcd0298fd44.png)

**Comment by latenitefilms** [comment]
Also, while I think about it, given there's a lot of duplicate code between all the `core.preferences.panels` plugins (i.e. `mod:addDropdown`, `mod:addButton`, etc.) - I wonder if this can all be offloaded to a `cp.web` function as well?

**Comment by randomeizer** [comment]
Yeah, I was observing that yesterday. Some might go in `cp.web`, others
maybe into a shared panel table or something
