### ISSUE TITLE
Shift Command Opt Commands don't work in Blender with BM Speed Editor

### ISSUE THREAD

**Issue by AlexPetrov108** [fcpxhacks/fcpxhacks#3138]
Hi there,

For some reason when you assign any standard command from Blender which includes Shift, Command or Option to a button on a Blackmagic Speed Editor keyboard, it only executes the letter as if those shift/command/opt buttons weren't pressed. 

For example, 'Shift + A' is supposed to open a Create menu and 'A' alone selects everything in the scene. When you assign 'Shift and A' to a button and press it in Blender, it selects everything in the scene instead of opening a Create Menu. The same applies to any other combination.

For clarity purposes, I tried to assign a 'Shift + A' combination to a button on my Wacom tablet and it worked without any issues so it's not a Blender problem.

Tested on MacOS 12.6, Blender 3.2 and 3.3, the latest firmware of the Speed Editor.

**Comment by latenitefilms** [comment]
Huh, interesting. Lets try this:

Click the CommandPost menubar item, then select "Preferences > Scripting". 

Click the "New" button, then type something like "Press Shift A", and paste in this code:

```lua
cp.tools.keyStroke({"shift"}, "a", nil, true)
```

You should now find a Snippet called "Press Shift A" in the Search Console.

Does this action work correctly in Blender?

**Comment by AlexPetrov108** [comment]
Thanks! Just tried that and nothing happened - no reaction in the interface. I wasn't sure though if the checkboxes in that Snippet menu should be on or not. The first one didn't turn on, saying that it failed to install the command line support. Turning on the AppleScript support one didn't help either.

**Comment by latenitefilms** [comment]
No, you don't need to click either of those checkboxes. Do you get an error if you press the "Execute Code" button?

If you assign the same Snippet to a shortcut key or button in TextEdit, does it write "A"?

**Comment by AlexPetrov108** [comment]
There is no error when executing the snippet, and it does type 'A' in the TextEdit. **AND**, when I saw that it's typing in the TextEdit, I decided to go back to Blender settings and for some reason, that snippet wasn't set for the button I tried to press. I set it again, and it actually **opened** that Create Menu in **Blender**!!

So does it mean, that the app can be updated with this info in mind, or do I need to create those snippets myself for all the commands I need?

Thank you!

**Comment by latenitefilms** [comment]
Good question! Basically, there's two different methods we can use for injecting virtual keyboard shortcuts, and both seem to have pro's and con's and work in some cases, but not others. I think we'll just have to have two actions for the two different methods, and users will have to determine which works best for the app they're using. I'll try have a look at this later tonight or tomorrow and push out a fix.

**Comment by latenitefilms** [comment]
Actually, before I do that, can you try creating another Snippet with this code, just to make sure it definitely doesn't work?

```lua
cp.tools.keyStroke({"shift"}, "a", nil, false)
```

If it doesn't do what you expect, can you try putting your cursor in a textbox in Blender and see if it writes "a" or "A"?

**Comment by AlexPetrov108** [comment]
Sure, I confirm that switching the last argument to 'false' changes the action in Blender as if I pressed only 'a' instead of 'shift + a'. Having said that, in both cases, it types the capital letter in the text field. 

I hope it helps and I agree that having two options for users would be the best decision to solve the issue considering the circumstances. Good luck and thank you =)

**Comment by latenitefilms** [comment]
Awesome, thanks! I'll try and have a proper look at this tomorrow.
