### ISSUE TITLE
Order search console results by most used.

### ISSUE THREAD

**Issue by dutchct** [fcpxhacks/fcpxhacks#3140]
When using the search console with final cut (ctrl+space), it would be awesome to order results by most used over the last 3-4? days.

For example, I always select the same effect, but it's always 3rd on the list. It would be great if it was first and I could just hit return to select instantly.

**Comment by latenitefilms** [comment]
Ummm, it should already do this?

For example:

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/22286696/201616516-f5d3401e-8905-4879-9efe-218968d32839.png">

You can also right-click on items to "favourite" them.

**Comment by dutchct** [comment]
Hrm, I don't think mine is doing what yours is doing. If I have my search field empty, basic title is at the top, with a bunch of stuff I don't use below it.

If I search "pan" my pan and zoom plugins come up, but the one I use the most is 3rd in the list.

I did not know about the favorite feature, thanks for that. I'll start using that.

**Comment by latenitefilms** [comment]
That's strange. My most recent actions are definitely at the top of the list.

Have you got "ALL" selected in the Toolbar?

Keep in mind that each instance of the Search Console is different - for example, the Search Console you trigger in Final Cut Pro using CONTROL+OPTION+COMMAND+SPACE has a different "memory" and preferences than the Search Console that's triggered by a button in the Control Surfaces panel.

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/22286696/202827162-d22526ae-e171-4ddb-a0d0-621e5f90ab57.png">

**Comment by dutchct** [comment]
I have all selected at the top.

I think that's the problem, I used the control surfaces panel to create a shortcut "control+space" to bring up the search console. Is it possible to unify how these search consoles work in that case?

**Comment by latenitefilms** [comment]
Ummmm... Every time you press CONTROL+SPACE it should bring up the same Search Console though.

**Comment by dutchct** [comment]
Sorry, I must have miss understood this post:

"Keep in mind that each instance of the Search Console is different - for example, the Search Console you trigger in Final Cut Pro using CONTROL+OPTION+COMMAND+SPACE has a different "memory" and preferences than the Search Console that's triggered by a button in the Control Surfaces panel."

I'm quite confused now. In one post you say they're different and in the next, you say they're the same.

**Comment by latenitefilms** [comment]
Sorry for the confusion.

Every time you trigger the same action (in your case CONTROL+SPACE) it opens the same instance of that Search Console. It will remember which Action Groups you have enabled for that Search Console.

Each Control Surface panel also has its own Search Console instance. For example, all the "Select" buttons on the MIDI Control Surfaces panel are the same instance of the Search Console, and all the "Select" buttons on the Razer Control Surfaces panel are another instance of the Search Console. 

The reason for this is you probably want to keep the search selected Action Groups when you're remapping a Control Surface, and you don't want it changing the Search Console in Final Cut Pro.

Favourites and "hidden" actions are also saved within that instance of the Search Console - so you can have different favourites in your MIDI Control Surfaces Panel for instance.

There are also actions for opening Search Console with pre-selected Action Groups:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22286696/204075742-cc3b6cf2-17d8-4946-8fbf-47d11c8fa1e1.png">

Does that make sense now, or have I confused things more?

**Comment by dutchct** [comment]
Got it now, thank you.
