### ISSUE TITLE
Add possibility to change modifiers to navigate timeline / panels as you prefer

### ISSUE THREAD

**Issue by Gabby16Bitbox** [fcpxhacks/fcpxhacks#3146]
At the moment you need to press shift while scrolling with mouse wheel to horizontal navigate around timeline. 

You can fix that with third party program adding modifiers to the wheel on them, but if you do that then the effects panel wheel need a modifier to work. 
Is there a way to eliminate change or make that both the timeline and the effect panel work horizontal and vertical without modifiers like in premiere pro and other NLE?

**Comment by latenitefilms** [comment]
This is discussed in #1075
