### ISSUE TITLE
Razer Tartarus V2 Key Press Issue

### ISSUE THREAD

**Issue by Left0verPizza** [fcpxhacks/fcpxhacks#3148]
Hello, I just started playing with the software and I'm running into some issues I can't seem to figure out.  I'm trying to set a single keypress to the "O" key on a keyboard so when I'm editing in Premiere Pro it just simply makes an out point on my timeline.  When I press it not only does it create an outpoint but it seems to randomly delete part of the clip to the out point.  This behavior seems to be on some other keypresses as well.  I have the 15 button set to re-do and when I press that it will complete the action but also highlight the source panel.  Pressing another set to "L" for jog forward will also select the clip on the timeline.

Any help would be greatly appreciated.

**Comment by latenitefilms** [comment]
That's strange. Can you try opening something like TextEdit, and press all the keys, and see if they do anything without having anything assigned to them?

To confirm, you're definitely using the "Razer Tartarus" (as opposed to all the other models)?

**Comment by Left0verPizza** [comment]
Thanks for the response.  I just closed command post and typed with it in text edit.  The keys all type or do some sort of word processing function without anything assigned to them.  With command post they behave the same way in text edit which I would expect since I haven't mapped anything for that program.  Using the Tartarus V2 keyboard as well as in the software.

**Comment by Left0verPizza** [comment]
Hello, I see you've updated the milestones and appreciate you looking into this.  Really excited about this software so if there's something I can do to help you isolate the issue let me know.

**Comment by Left0verPizza** [comment]
Ok, so doing a little digging and from what I can tell it must be a bug with the software.  When I close command post I can press the keys on the Tartarus and see one key press in a text edit file.  In this case 12 is typing "a".  When I open command post I have the 12 button mapped to "j" and in text edit I can see that one press has it type "aj" in quick succession, so something is firing the default keypress of the device the way OSX is reading it then followed by Command Post.

**Comment by latenitefilms** [comment]
Thanks for the follow up. Apologies for the delay in investigating this. Is this only happening for certain keys?

I'll try and plug in a "Razer Tartarus V2" and see if I can reproduce.

**Comment by latenitefilms** [comment]
I just plugged in a **Razer Tartarus V2**, and it all works as expected for me.

In its default layout, pressing "12" definitely doesn't type "a" for me.

What model number do you have? I have **RZ07-0227**, and the product number is **RZ07-02270100**.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22286696/205224817-6cef5bd7-cc6e-4548-9ec2-ffb10cc6389f.png">

**Comment by Left0verPizza** [comment]
Well it seems to be working now.  I don't know if it was the update or if more likely there was another piece of software interfering but it's acting as expected.

Thanks for helping!
