### ISSUE TITLE
Fix Waveform Disappearing / Rendering during playback solution

### ISSUE THREAD

**Issue by Gabby16Bitbox** [fcpxhacks/fcpxhacks#3161]
Final Cut has since years a bug that makes the waveforms vanish every time you make a cut during playback or zoom in and out the timeline. It is so frustrating for an editor that comes from Premiere pro and is the only reason I can't edit full time in FCPx. You fixed this bug when you enable "rendering during playback" in Final Cut preferences and that is AMAZING. But it makes the program so much slower and choppy with my M1 Mini.

I wonder if there is another solution to fix this Bug for good since apple is taking years. Maybe activate the render only for the waveforms? A lot of people are complying and it would be the best thing for FCP users to have it gone for good. 

Ex of the bug: https://www.youtube.com/watch?v=Gc3Meli4jfg

**Comment by latenitefilms** [comment]
Huh, that's interesting. We haven't had anyone else complain about "rendering during playback" - and seems to work fine on our Apple M1 Max's. Unfortunately I don't think there's anything we can do about it - all we're doing is turning on a hidden preference inside Final Cut Pro. Sorry!
