### ISSUE TITLE
Windows and/or Linux version

### ISSUE THREAD

**Issue by ysn2021** [fcpxhacks/fcpxhacks#3207]
Is it possible to port CommandPost to Windows or Linux with reasonable effort? There is nothing comparable for those operating systems. At least Lua seems to be available for both as well. Or is there something Mac-specific standing in the way of a port?

**Comment by randomeizer** [comment]
While Lua itself is cross-platform, and some of the libraries we have written are purely in Lua, the vast majority link to macOS-specific libraries under the covers. That includes most of the interesting stuff that CommandPost does, such as the search console, integrating with applications, listening to keyboard and mouse actions.

It would essentially be a completely different application on another platform.

Are there any features in particular you wanted in those operating systems? It's possible that other applications exist already that do something similar.

**Comment by ysn2021** [comment]
Thank you for the response, David. I'd love to use the Davinci Resolve Speed Editor with graphics tools like Blender or Krita. There are nice apps for listening to keyboard or mouse actions on the other OSes, like easystroke for Linux or strokesplus for Windows, but there seems to be no way to use the Resolve Speed Editor outside of Davinci Resolve. To me this feels like a waste of this beautiful piece of hardware. You have solved the problem greatly, but only Mac users are the lucky ones. I still greatly appreciate your work and hope that there will be a solution for windows or linux one day.

**Comment by randomeizer** [comment]
@latenitefilms is more familiar with the Speed Editor code, but it is open source, so it's possible someone could port it. I think it's a bit out of scope for us though, unfortunately.

**Comment by ysn2021** [comment]
I fully understand that. Thank you for the friendly and helpful info. I'll have a look at the code and try to figure out, whether I can make sense of it.

**Comment by latenitefilms** [comment]
Apologies for the extremely delayed reply!

You can find all our Blackmagic Speed Editor code here:

https://github.com/CommandPost/CommandPost-App/tree/master/extensions/blackmagic

This code should definitely be possible to "port" across to Windows or Linux.

Hope this helps!

**Comment by ysn2021** [comment]
Thank you, that's very kind of you.
