### ISSUE TITLE
Loupedeck Live - Images not updated

### ISSUE THREAD

**Issue by exlee** [fcpxhacks/fcpxhacks#3219]
Hi,

I've installed CommandPost and it doesn't seem to work with Loupedeck Live.
CommandPost doesn't report any errors whatsoever (see attached console dump).

Beyond missing images everything else works. I can change color of the buttons, app switching works, haptic feedback works correctly and configuration is also there. For some reason it just doesn't seem to "send" the images.

- After initial connection icons are the default "boot" ones, i.e. green "pacmans".
- After reloading CommandPost it's changes to all black.
- I tried to use multiple source of icons (drag and drop, from app, even without - only text), but nothing gets updated.

I'm running Ventura 13.4 (but I updated to check if restart/update would help as it didn't work on 13.3) on Apple Silicon.

```CommandPost v1.4.17 (Build: 7956)

Build Date:                     Mar 17 2023, 15:33:25
macOS Version:                  13.4.0
CommandPost Locale:             en_PL
Current Keyboard Layout:        Polish
Final Cut Pro Path:             
Final Cut Pro Version:          Not Installed
Final Cut Pro Language:         Not Installed
Developer Mode:                 false

2023-06-03 14:44:34: -- Loading /Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2023-06-03 14:44:42: 
2023-06-03 14:44:42: 14:44:42         cp:     Loading Plugins...
2023-06-03 14:44:45: 14:44:45 ** Warning:   plugins: Slow Plugin: core.loupedeckctandlive.manager (1.7251179218292)
2023-06-03 14:44:45: 14:44:45 ** Warning:   plugins: Slow Plugin: core.menu.menuaction (2.1272149085999)
2023-06-03 14:44:45:                  cp:     Plugins Loaded.
2023-06-03 14:44:45:                          Startup Time: 2.842362 seconds
2023-06-03 14:44:45:                          Garbage Collection Mode: generational
2023-06-03 14:44:45: -- Done.
```

**Comment by exlee** [comment]
FYI: I've found the issue, it seems that (for whatever reason) Loupedeck Live behaves exactly the same as Razer Stream. I'll draft a PR, but not sure if that's catch all (maybe there are devices that don't behave like Stream?) so extra checkbox in UI might be needed.

**Comment by latenitefilms** [comment]
This is super interesting! Thanks for sharing!

Are you able to share the hardware details that are on the sticker on the back of your Loupedeck?

Are you able to confirm what firmware your device is running?

**Comment by exlee** [comment]
Sure, here's some extra information that could help.

I've done some extra hacking and it seems that I could completely re-route Live to be used in CommandPost as Razer Stream Controller. Did this because it seems that plastic frame grid over display is covering some of output. See the [picture](https://github.com/CommandPost/CommandPost/assets/3380474/fc0d6b2d-78fb-4f39-b27e-646943b51cd6). 

If that's NOT the case with Razer Stream i suppose there could be completely separate rendering logic. 
If it is - I could probably hack some stuff to fix it.

---

Captured data from serial:
```
Manufacturer: Loupedeck
Product: Loupedeck Live
```

Firmware (output of `hs.loupedeck:requestFirmareVersion` - btw. it could be put in docs, took me a moment to find it 😅 )
```
{
  b = "0.2.11",
  c = "0.9.0",
  data = "\v\t",
  i = "0.0.0",
  id = 3079
}
```

Sticker Info (? - non-latin char):
```
Model/????: Loupedeck Live
TYPE/???: LDD-2001 VER/???: 02.00
Input: 5V --- 0.7A(max) LOUPEDECK OY, FINLAND
??: 5V --- 0.7A(??) MADE IN THAILAND ?????

Compliance logos
S/N: [Redacted]
```

I'm not comfortable with sharing full S/N but let me know if there are any specific digits that'd be helpful.

**Comment by latenitefilms** [comment]
Legend, thank you! I'll try plugging in a Loupedeck Live, updating the firmware, and see if I can reproduce.

**Comment by latenitefilms** [comment]
Note to self... this is what I was running:

<img width="805" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/dda77038-c7d9-4faa-9d32-b80e12ac037a">

**Comment by latenitefilms** [comment]
...after updating:

<img width="1927" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/9a3cf90b-3232-4a30-9103-86c5b2f3939b">

**Comment by latenitefilms** [comment]
Ok, so even with the latest v0.2.5 firmware, the Loupedeck Live still seems to work on CommandPost.

**Loupedeck Live**
**Type:** LDD-2001
**Version:** 01.30

**Comment by latenitefilms** [comment]
...and v0.2.5 is the latest firmware the latest Loupedeck software will let me install:

<img width="1927" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/102c5423-64a9-48f6-9675-ee6e6979037d">

**Comment by latenitefilms** [comment]
Here's what CommandPost reports using `:requestFirmwareVersion()`

<img width="626" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/fe844f97-0171-4622-8cb5-a0d6211f9fbc">
