### ISSUE TITLE
Invalid FCPXML File with Sony Timecode Repair on FCPX 10.6.6

### ISSUE THREAD

**Issue by ikester** [fcpxhacks/fcpxhacks#3222]
Hi. I'm trying to run the Sony Timecode Repair for a simple project on FCPX 10.6.6 and I'm getting this:

> Invalid FCPXML
> The supplied FCPXML did not pass DTD validation. Please check that the FCPXML supplied is valid and try again.

This is in the log file:
`2023-06-14 19:28:28: 19:28:28 ERROR:sonytimeco: The supplied FCPXML did not pass DTD validation. Please check that the FCPXML supplied is valid and try again.`

I'm not familiar with the code but I imagine it might have something to do with the latest version of the XML DTD?

**Comment by latenitefilms** [comment]
Yes, we need to update CommandPost to use the latest FCPXML in v10.6.6. I'm hoping to push out an update later today.

In the meantime, you can try this earlier beta:

https://latenitefilms.digitalpigeon.com/msg/-16akAEbEe6OFQYn7yQzAw/DsIGeI7-AKhM2X_Dc82o2g

**Comment by latenitefilms** [comment]
An update for CommandPost is now out!

https://commandpost.io/download/
