### ISSUE TITLE
Loupedeck live не меняет банки

### ISSUE THREAD

**Issue by 3mvideo** [fcpxhacks/fcpxhacks#3270]
Loupedeck live does not switch banks (all other commands and controls work). I switched it before, but didn’t notice at what point it stopped to understand the reason.
The switch buttons contain the commands “loupedeck live bank 1,2,...7”; when you try to change the commands, only “loupedeck live bank 1,2,...7 Unit 1,2,...7” is available. Selecting this command still does not switch banks.
MacBook pro 16 m1pro macOS 13.5.2 FCP 10.6.8
If you run the official Loupedeck program the banks switch.
![4](https://github.com/CommandPost/CommandPost/assets/94798595/d41d5bc1-35f2-4559-b5e6-92071b660672)
![1](https://github.com/CommandPost/CommandPost/assets/94798595/bd43c407-3c36-400e-9941-ddd951cc7c82)
![2](https://github.com/CommandPost/CommandPost/assets/94798595/954fff9a-4087-49fb-ae86-c50d6c143af4)
![3](https://github.com/CommandPost/CommandPost/assets/94798595/7ce8cf52-0fe0-4749-9a09-8fab0b206679)

**Comment by latenitefilms** [comment]
I believe it's because you've got **Preview Selected Application & Bank on Hardware** checked. This will basically force it to whatever bank you have selected in the Preferences.
