### ISSUE TITLE
Loupedeckct for FCPX Button Error Exclamation Point

### ISSUE THREAD

**Issue by livesince89** [fcpxhacks/fcpxhacks#3273]
Just bought and installed everything but a lot of the installed function have an ! Error. How do i fix this.

**Comment by latenitefilms** [comment]
You're going to have to give a bit more information...

Are you using CommandPost's Native/Direct Loupedeck CT support or are you using the official Loupedeck application and the CommandPost Plugin?

Can you share a screenshot of what you're seeing?

**Comment by livesince89** [comment]
Hey Chris!

So i’ve downloaded CP from the website.
And then through LD downloaded and installed the plugin.

I’ve uninstalled both and tried again today, no luck.
This is what i’m seeing.

[image: Screenshot 2023-10-03 at 3.45.38 PM.png]

**Comment by latenitefilms** [comment]
Unfortunately your screenshot didn't attach properly. Try replying via the GitHub website.

**Comment by livesince89** [comment]
CommandPost Error.png
<https://drive.google.com/file/d/1sTuPaAnxbIdZxq7uum9XsYs_N9kaJoMO/view?usp=drive_web>

**Comment by latenitefilms** [comment]
That doesn't look like the CommandPost Plugin is actually installed.

Try following the instructions here: https://support.loupedeck.com/setting-up-commandpost-plugin

**Comment by livesince89** [comment]
ahhh okok, that worked, thank you so much dude!
