### ISSUE TITLE
User Customised Final Cut Shortcuts don't work

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#328]
There seems to be a bug in `cp.commands` that is preventing plugin commands (such as "Select Clip at Lane") that don't have a default shortcut built-in from working?

**Comment by randomeizer** [comment]
Is everything matching up with the new 'cp' prefix for commands?

**Comment by latenitefilms** [comment]
Yes, for example, `cpSelectClipAtLaneOne` definitely appears in the new plists correctly.

**Comment by latenitefilms** [comment]
@randomeizer FYI - I'm still having issues with this one.

**Comment by latenitefilms** [comment]
This seems to be working now for me, so I'm going to close this issue for now.
