### ISSUE TITLE
is it possible to add an audio input / output setting for FCP?

### ISSUE THREAD

**Issue by concealedResonances** [fcpxhacks/fcpxhacks#3289]
I would to have an audio input / output setting in FCP, is there any chance you guys can add it? thanks

**Comment by latenitefilms** [comment]
@concealedResonances - Could you explain in more detail what you mean exactly? Do you want to specific a specific audio output just for Final Cut Pro (as opposed to macOS and other applications)?

I believe there's third party tools that can do this, and it's probably outside the scope of CommandPost?

**Comment by concealedResonances** [comment]
> @concealedResonances - Could you explain in more detail what you mean exactly? Do you want to specific a specific audio output just for Final Cut Pro (as opposed to macOS and other applications)?
> 
> I believe there's third party tools that can do this, and it's probably outside the scope of CommandPost?

if there is a tool for that I have no idea. I can choose input when do VO in FCP but there isn't a dedicated audio preference drop menu.

Basically, I would like to choose which audio in/out FCP uses, like you see in any other app like logic or Davinci (speaker set up) or PP (audio hardware), without messing around with the system audio in/out. So I can route audio with "blackhole"  (https://github.com/ExistentialAudio/BlackHole) as I like.

I ask  before but I have no idea why they can not simply added in the preferences.

**Comment by latenitefilms** [comment]
Maybe try [Audio Hijack](https://www.rogueamoeba.com/audiohijack/)?

**Comment by concealedResonances** [comment]
> Maybe try [Audio Hijack](https://www.rogueamoeba.com/audiohijack/)?

sure, thanks

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but feel free to re-open if you think there's anything else we can do in CommandPost.
