### ISSUE TITLE
If installed, FCP7 may get opened when performing some actions

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#33]
For example, pasting from clipboard history.

**Comment by randomeizer** [comment]
This appears to be due to a change in the way FCP is being found. Previously it was using the '/Applications/Final Cut Pro.app' path to find the app, now it's using the title.

The better way is to use the bundle ID, which for FCPX is `com.apple.FinalCut`, and for FCP7 is `com.apple.FinalCutPro`.

**Comment by randomeizer** [comment]
I've put code which looks for FCPX via its bundle ID rather than title to make this more reliable. I've also added an 'fcpxApplication()' method into the 10.3 code to make it easier to fix future issues.

**Comment by latenitefilms** [comment]
Perfect - thanks so much!

I've been meaning to experiment with using bundle ID's since the beginning, but never got around to it!

Also, brilliant idea to put it all in the `fcpxApplication()` function - that makes so much more sense!

Thanks again!
