### ISSUE TITLE
Error when I add the Draw Mask effect for example, and when the Effects category is not selected to All.

### ISSUE THREAD

**Issue by lamer40** [fcpxhacks/fcpxhacks#3314]
When I try to apply the Draw Mask effect and if the Effects tab is not set to All Videos & Audio I get the following error.
When I set the tab to All Videos & Audio the Draw Mask is being properly applied to the clip.
I'm using the latest versions of CP

https://github.com/CommandPost/CommandPost/assets/3479840/49e16998-fe9c-4f77-8680-4e5a4736e709

**Comment by latenitefilms** [comment]
Thanks! Closing in favour of #3315.
