### ISSUE TITLE
App should be clear when its screen recording

### ISSUE THREAD

**Issue by quantuminformation** [fcpxhacks/fcpxhacks#3324]
ATM after I close the app or leave FCP I go to accessibility and disable screen recording for CP, which is a drag

**Comment by randomeizer** [comment]
Clear in documentation?

To my knowledge, we only use it in two places:

1. Grabbing a tiny screenshot of the "Play" button on the viewer, so that we can determine if it's currently playing or paused.
2. Screenshot of the Viewer itself if you create an overlay or memories for later use.

**Comment by quantuminformation** [comment]
should be some UI to show that screen is being recorded, like with zoom or Slack has similar

**Comment by randomeizer** [comment]
I guess? Wouldn't it be simpler just to close CP if you're not using FCP? Or do you use it for other tasks?

**Comment by quantuminformation** [comment]
CP could be running on a background process, so I'd be concerned about privacy

**Comment by randomeizer** [comment]
If you quit CommandPost, and it's not in the  menu bar, it's not running. It doesn't run any background services.

**Comment by quantuminformation** [comment]
ok thx
