### ISSUE TITLE
Please Add AAF Export

### ISSUE THREAD

**Issue by Don0612** [fcpxhacks/fcpxhacks#3340]
If possible, please add a direct AAF export/import function. Just like X2Pro converts FCPX XML files to aaf format to be opened in ProTools, Cubase etc
It would be very convenient to export/impoort AAF files from final cut directly instead of using DaVinci Resolve with timeline import, the extremely expensive X2Pro or Apple Logic to do so. As FCP 7 had the omf feature that time,  FCPX is still lacking this important feature to exchange audio with DAWs properly. (Almost any other major editing software has got an aaf export/import feature) Apple does not want to add it, it seems.

It would be great to have an embedded/non embedded files option, as well.

**Comment by randomeizer** [comment]
Unfortunately, it's not a simpler thing to support. That's why X2Pro costs money - it takes significant time to get it working and keep it working.
