### ISSUE TITLE
Search Console fails to apply actions

### ISSUE THREAD

**Issue by jacktheripper96** [fcpxhacks/fcpxhacks#3365]
<img width="1277" alt="Screenshot 2024-08-21 at 8 14 37 PM" src="https://github.com/user-attachments/assets/4482b39b-a71b-43e8-a4fe-f7c80101ab8b">
<img width="1179" alt="Screenshot 2024-08-21 at 8 14 53 PM" src="https://github.com/user-attachments/assets/26a3f5c3-2d89-4cd2-bf87-db508df6f425">
<img width="763" alt="Screenshot 2024-08-21 at 8 15 20 PM" src="https://github.com/user-attachments/assets/2e11d146-4614-4d1d-9f6b-e8cbd065ac35">

Anytime I try and use the Search Console, specifically with custom titles, effects, sounds, or generators I get an error message.

**Comment by latenitefilms** [comment]
Ummm, that's strange. Can you take a screenshot of the Titles panel for the "Assembler" title?
