### ISSUE TITLE
Search Console fails to apply actions

### ISSUE THREAD

**Issue by kurtfarr** [fcpxhacks/fcpxhacks#3366]
Over the years I download and try to get CommandPost to work and it rarely does. It's exactly the utility I need. I always use the latest CommandPost software version as well as the latest FCX & macOS . But it's always the same result...most features do not work and a ton of spinning beach balls. Outside of CommandPost I have not seen a spinning beach ball in nearly a decade.

Any help would be appreciated! I would love to use this utility. thanks

**Comment by latenitefilms** [comment]
There are thousands of people using CommandPost, so your experience is definitely not normal.

Do you have any other applications that use the Accessibility API that might be conflicting? BetterTouchTool, Keyboard Maestro, etc?

What features specifically aren't working for you?

**Comment by kurtfarr** [comment]
Hi Chris. Thanks for the quick reply. I had “Better Snap tool” but deleted it a while back.
My 3rd party plugins consist of 

Unclutter
Neofinder 
Lasso (windows manager)

Anything else I should look for? CommandPost looks incredible but just could not get around the bad performance on my Macs. 
I do think it is specific to me because I really don’t see anyone else having issues.

I assume it does run on Silicon? 

thanks Chris



Kurt Farr
Multimedia Production Specialist / Instructional Technologist
M.S Instructional Technology
Bloomsburg Pa.
570-764-7218

**Comment by latenitefilms** [comment]
Yes, most of our users are using Apple Silicon.

Can you try just quitting everything else (especially Lasso), apart from CommandPost & Final Cut Pro, and report back any specific problems/issues?

**Comment by kurtfarr** [comment]
Hi Chris.

I did some testing this morning and started to get some items to work.

Overlays were not working but after switching keyboards overlay shortcut did work


HUD

This is what I got after adding the following item from HUD

Adding “solid” gives error

Adding RT Alignment ruler gives error

Adding isotope rx10 plugin (3rd party) DOES WORK 



At first I thought 3rd party items did not work. And then I tried RX 10 Izotope and that did work


The main features that I would use is HUD & Search console. Do you have any tips/tricks to get the most out of these 2 features? 

PS when I found out you included font search my mind was blown, thank you

Any advice is much appreciated

Thanks 




Kurt Farr
Multimedia Production Specialist / Instructional Technologist
M.S Instructional Technology
Bloomsburg Pa.
570-764-7218

**Comment by latenitefilms** [comment]
Closing in favour of #3365
