### ISSUE TITLE
FCP XML issue when importing to Davinci Resolve studio 18.6.6 using CommandPost

### ISSUE THREAD

**Issue by asohawramii** [fcpxhacks/fcpxhacks#3370]
I use FCP 10.8.1 and when I want to transfer the timeline to Davinci resolve to color and finalize everything else there, I use CommapndPost.
the problem is Davinci Resolve Studio does not support opening FCPXML files with version 1.12, and Commapost is exporting by default this version.

is there any way to solve this? or any manual trick to change the command post XML file export version?

Command Post version: 1.4.27

**Comment by latenitefilms** [comment]
Easiest/quickest fix is to just open up the FCPXML is a Text Editor and change `1.12` to `1.11`.

You could also use [Capacitor](https://capacitor.pro). 

I'm pretty sure DaVinci Resolve v19.0.0 now supports the latest FCPXML.

**Comment by latenitefilms** [comment]
Curious... what feature are you using? Timecode Repair Toolbox?

**Comment by asohawramii** [comment]
@latenitefilms I exported the FCPXML using latest commandpost version, then opened the XML file to change the version from 1.12 to 1.11.

till now OK, and when I import XML into davinci resolve. for a moment the clips work well and all load. but unfortunately davinci resolve is stuck and not responding.

**Comment by asohawramii** [comment]
@latenitefilms **NEW UPDATE**

After trying few times by closing and opening davinci resolve and importing the timeline, finally could open the timeline ready to work on.

not sure if I will face same issue or not in future, but will keep you updated.

So many thanks for the amazing support. cuz I was suffering for few months and now I'm smiling since this simple tweak is saving a looooooooot of time for me

**Comment by asohawramii** [comment]
Hey Chris,
First of all appreciate your amazing support.

your tool is a lifesaver, and cannot express my feelings right now.
I'm just smiling.

I use the tool for timecode issues between FCPX and Davinci resolve. since
I edit videos and use Sony cameras. so the Sony timecode toolbox is my only
tool to use right now.
but if there are other things you think I benefit from and save more time,
let me know of course.

[JUST THINKING LOUD] Maybe you add a feature to your tool to scan, ripple
check, and delete silence moments in a video same as adobe audition. or any
other program.

**Comment by estudioek** [comment]
> Easiest/quickest fix is to just open up the FCPXML is a Text Editor and change `1.12` to `1.11`.
> 
> You could also use [Capacitor](https://capacitor.pro).
> 
> I'm pretty sure DaVinci Resolve v19.0.0 now supports the latest FCPXML.

NO, Davinci is NOT supporting it, at least not the Command Post xml file...

**Comment by latenitefilms** [comment]
There's no real difference between FCPXML v1.12 and v1.11 - at least not for 99% of users, so you can safely change the version number without any impact to DaVinci Resolve.

<img width="798" alt="image" src="https://github.com/user-attachments/assets/a4f56c60-9859-4300-82d4-36fa54387ff9">

**Comment by estudioek** [comment]
I finally got it to work changing the name to 1.11 
Thanks a lot

**Comment by latenitefilms** [comment]
Closing in favour of #3384
