### ISSUE TITLE
Batch Export Timeline - Destination Presets and Destination Folder

### ISSUE THREAD

**Issue by samplue** [fcpxhacks/fcpxhacks#3396]
Running FCP 11 and CP 1.5.0 the list of destination presets will only show some of the presets. 
Selecting a destination folder is not respected during export, but it will choose the last location that was used during a prior export.
![Sam_2024-11-29_11h20m37](https://github.com/user-attachments/assets/6cb61ff5-cd26-4e31-8202-4d173c5b4b88)
![Sam_2024-11-29_11h22m08](https://github.com/user-attachments/assets/24c3fe32-628e-4c1e-9e53-e4b4761a458c)

**Comment by latenitefilms** [comment]
I think it's still most likely reading your old FCP 10.8.1 Destinations. I'll try and fix this next week.

**Comment by latenitefilms** [comment]
I believe this is now fixed in CommandPost 1.5.1, but if you're still having issues please reopen this issue.

**Comment by samplue** [comment]
Thank you! Just ran a test and everything worked as expected.
