### ISSUE TITLE
Incompatible 1.5.0 auto-upgrade requiring 13.0 offered to 12.7.6 users

### ISSUE THREAD

**Issue by ivucica** [fcpxhacks/fcpxhacks#3399]
Hi,

My Macbook Pro 2016 (still perfectly serviceable, especially with an eGPU) is stuck on 12.7.6 (still usable).

Final Cut Pro is not upgradeable anymore, but this is fine for my casual use.

CommandPost automatic upgrade to 1.5.0 was offered to me today without detection or warning that the release is not runnable under versions older than macOS 13.0. Since I cannot upgrade my Macbook with T1 chip to 13.x, it'd be cool if the upgrade was not offered at all, or if the changelog was updated with a massive warning that CommandPost 1.5.0 and later are not compatible with macOS 12.x or older.

(No need to add support for 12.x, but a big warning would be awesome in preventing users from performing the upgrade and having their .app replaced with an incompatible version.)

**Comment by latenitefilms** [comment]
Thanks for reporting! I believe this is now fixed, but if you're still having issues feel free to re-open this issue.
