### ISSUE TITLE
How can I use AppleScript to execute a plugin through COMMANDPOST, so that Stream Deck can execute specific commands through the official software?

### ISSUE THREAD

**Issue by qq411240** [fcpxhacks/fcpxhacks#3401]
How can I use AppleScript to execute a plugin through COMMANDPOST, so that Stream Deck can execute specific commands through the official software?

**Comment by latenitefilms** [comment]
You can get CommandPost to execute any Lua script via AppleScript - see:

https://commandpost.io/scripting/applescript/

For example:

```applescript
tell application "CommandPost"
	execute lua code "require(\"cp.plugins\")(\"finalcutpro.timeline.lanes\").selectClipAtLane(1)"
end tell
```

You can use the **Preferences > Snippets** page to generate appropriate Lua Code based off existing actions.

See:

https://commandpost.io/preferences/scripting/
