### ISSUE TITLE
Move cp.metadata to just cp?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#342]
Currently variables like the `scriptName` are stored in `cp.metadata` - for example `cp.metadata.scriptName`. However, would it make more sense to just keep it in the "root" cp namespace (i.e. `cp.scriptName`)?

Thoughts @randomeizer ?

**Comment by latenitefilms** [comment]
Also maybe `cp.metadata.get/set/reset` should be renamed to `cp.settings.get/set/reset` to keep consistent with it's Hammerspoon counterpart?

**Comment by latenitefilms** [comment]
I'm not sure about this one @randomeizer - thoughts? Feel free to close this issue if you don't think it's important.

**Comment by randomeizer** [comment]
It's not in `cp` so that it can be imported from anywhere. And since it
does different things to what `hs.settings` does, I don't think it should
be called that either.

If you really want to rename it, something like `cp.config` might work.

**Comment by latenitefilms** [comment]
Great idea - I like `cp.config` much better!

Addressed in #355.
