### ISSUE TITLE
Add Better Javascript Validation to Feedback Form

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#347]

**Comment by latenitefilms** [comment]
Also, do further experimenting with using AJAX to transmit the form data. Currently I'm not having much luck - due to Safari's security settings when transmitting data between two different servers (i.e. localhost and the remote PHP server).

**Comment by randomeizer** [comment]
Yeah, you will have to set up something like CORS at the server side to use
AJAX to submit the form.

**Comment by latenitefilms** [comment]
Note to self: 

[Detecting hs.webview Errors](https://github.com/Hammerspoon/hammerspoon/issues/1243)
