### ISSUE TITLE
Multiple Watchers?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#352]
Interesting discussion [here](https://github.com/Hammerspoon/hammerspoon/issues/1245#issuecomment-283392466).

**Comment by randomeizer** [comment]
Yeah, I have been wondering about that myself. We spin up quite a few...

Things like the 'window' watchers are an attempt to group them together,
but I think we can do better.

**Comment by latenitefilms** [comment]
@randomeizer - Is this something we can/want to address anytime soon?

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, and we can address any specific concerns in their own issues.
