### ISSUE TITLE
Playhead Timeline Lock Bug

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#353]
Feedback:

> It seems that the “Enable Playhead Timeline Lock” sometimes works and sometimes doesn’t. It will start out working and then stop (the playhead will function as normal {before hacks})
> 
> Also when it is working there is a pronounced jitter in the timeline and the playhead. The video playback is fine.
> I have a Mac Pro 2013
> 16G Ram
> Processor: 3.5 GHz 6-Core Intel Xeon E5
> GPU: 2 AMD FirePro D500 3G RAM
> 
> -----------------------------
> | FCPX Hacks v0.78          |
> | Created by LateNite Films |
> -----------------------------
> Hammerspoon Version:            0.9.52
> macOS Version:                  10.12.3
> Final Cut Pro Version:          10.3.2
> Final Cut Pro Language:         en
> FCPX Hacks Locale:              en_US
> Current Keyboard Layout:        U.S.
> Final Cut Pro Path:             /Applications/Final Cut Pro.app
> 
> > Successfully loaded.
> 2017-03-01 17:15:40: ********
>  > ERROR:   LuaSkin: hs.timer callback error: ...ey/.hammerspoon/hs/finalcutpro/main/TimelineContents.lua:114: attempt to index a nil value (local 'ui')
> stack traceback:
> 	...ey/.hammerspoon/hs/finalcutpro/main/TimelineContents.lua:114: in function 'hs.finalcutpro.main.TimelineContents.viewFrame'
> 	...johnsipley/.hammerspoon/hs/finalcutpro/main/Timeline.lua:245: in function 'hs.finalcutpro.main.Timeline.lockPlayhead'
> 	...ohnsipley/.hammerspoon/hs/fcpxhacks/modules/fcpx10-3.lua:6688: in function <...ohnsipley/.hammerspoon/hs/fcpxhacks/modules/fcpx10-3.lua:6685> [17:15:40]
> 2017-03-01 17:15:40: ********

**Comment by randomeizer** [comment]
This will most likely be due to the 'play watching' code believing that the playhead has stopped before it actually does. It's a fine balancing act to decide how long to wait before that is decided.

I'll take a look at it.

**Comment by latenitefilms** [comment]
Looks like this has already been fixed in develop.
