### ISSUE TITLE
"Assign Choosers" should have ability to Show/Hide Sections via Right Click

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#354]
The assign HUD Chooser should have the same display options as the Console Chooser.

**Comment by latenitefilms** [comment]
I've updated the issue subject, as the Console Chooser "sections" have now moved to the menubar.

For the HUD Chooser and the Assign Shortcuts Choosers, we should add "section" selection as a right-click menu. The HUD Chooser & Assign Shortcuts Choosers, should ideally be the same code too - to avoid duplication.

Thoughts @randomeizer ?

**Comment by randomeizer** [comment]
You want to have separate 'sections' enabled for the HUD vs the Console? It's not really easy to do currently - the sections are enabled in the action manager as a whole, so they're either on for everyone or off for everyone.

**Comment by latenitefilms** [comment]
Ah, right! I didn't realise that the **Console Sections** now affect the **Assign HUD Buttons** chooser. That seems a little bit... weird?

The Console is all good. I like the fact that you control the "sections" from the menubar. That shouldn't change.

However, I feel like the **Assign HUD Buttons**  chooser should either always just show EVERYTHING, or have a right click option that allows you to "filter" the results (like the FCPX Hacks Console).

The **Assign Shortcuts** choosers probably don't matter, however thinking about it... maybe we should have seperate shortcuts for Video vs Audio shortcuts, and maybe a set of shortcuts for menubar actions?

Really though... the only reason we have these seperate is because of the "Hacks Shortcuts" functionality.  I really like the "Hacks Shortcuts" but if we did decide to drop this later down the line, then these "Assign Shortcuts" features don't really matter any more, as you will be able to assign whatever you want in the Shortcut Preferences Panel.

**Comment by randomeizer** [comment]
Which shortcuts are the 'Hacks Shortcuts' again?

**Comment by latenitefilms** [comment]
The "Hacks Shortcuts" are when **Control CommandPost Shortcuts within Final Cut Pro** is enabled and CommandPost reads the shortcut values from the current Final Cut Pro Command Set.

See: `finalcutpro.hacks.shortcuts`

**Comment by randomeizer** [comment]
Can we change that name now then? They're called 'commands' internally already...

On a slight tangent, what if we actually ditched the concept of having effects vs titles vs whatever shortcuts in sets of 4 and just allowed you to assign a keyboard shortcut to pretty much anything which shows up in the Console? We would have to manage the keyboard combo assignment in the Preferences Panel I think, but it would simplify a few things...

**Comment by randomeizer** [comment]
The downside is that you wouldn't have your keyboard combos for those shortcuts able to be stored in a separate Custom Command Set in FCPX. Hmm.

**Comment by randomeizer** [comment]
Or...we have a set of 10 (or 20, or whatever) fixed 'cpActionXX' commands that can be assigned within FCPX, and allow them to be assigned to whatever in the 'Action Shortcuts' panel. These would replace the existing individual 'Shortcuts' for effects/titles/etc. Any type of action (apply effect, click menu, whatever) can be assigned to any 'action shortcut' slot, and they are triggered by the FCPX Command Set combo.

**Comment by latenitefilms** [comment]
> Can we change that name now then? They're called 'commands' internally already...

"Hacks Shortcuts" are just an easy way to describe it. I'm not sure of a better way to describe it - as something like Final Cut Pro Commands - could get confusing with Final Cut Pro's OWN commands.

> On a slight tangent, what if we actually ditched the concept of having effects vs titles vs whatever shortcuts in sets of 4 and just allowed you to assign a keyboard shortcut to pretty much anything which shows up in the Console? We would have to manage the keyboard combo assignment in the Preferences Panel I think, but it would simplify a few things...

> The downside is that you wouldn't have your keyboard combos for those shortcuts able to be stored in a separate Custom Command Set in FCPX. Hmm.

That's basically what I was saying... Historically, the only reason we have four presets is because you have to manually add those four presets to Final Cut Pro's Command Set plists.

> Or...we have a set of 10 (or 20, or whatever) fixed 'cpActionXX' commands that can be assigned within FCPX, and allow them to be assigned to whatever in the 'Action Shortcuts' panel. These would replace the existing individual commands for effects/titles/etc. Any type of action (apply effect, click menu, whatever) can be assigned to any of them, and they are triggered by the FCPX Command Set combo.

This is definitely a good idea - but I feel like it's quite a bit of work to get it done, so maybe something for 0.80?

**Comment by randomeizer** [comment]
This has been fixed via #725 (and #667)
