### ISSUE TITLE
Add a Preferences Window (which contains Plugin Manager)

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#355]
Add a `hs.webview` that allows you to select which plugins you want to enable/disable - both the internal plugins (that ship with CommandPost), plus the ability to load custom plugins stored elsewhere on the users system.

**Comment by randomeizer** [comment]
Perhaps a more general 'Preferences' window?

**Comment by latenitefilms** [comment]
Yeah, that's a much better idea!
