### ISSUE TITLE
Enable XML Sharing should Refresh the HUD

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#373]
I'm not sure of the best way to do this @randomeizer in regards to plugin dependancies?

**Comment by randomeizer** [comment]
Probably add a cp.watcher to the XML Sharing plugin which notified
listeners when it is enables or disabled. Then the HUD can register to get
notified and refresh itself.

**Comment by latenitefilms** [comment]
Sweet - will have a play tonight. Do we already have a `cp.watcher` interface setup?

**Comment by randomeizer** [comment]
Yep. Have a look at cp.command as an example - I'm pretty sure it's using
one already.

**Comment by latenitefilms** [comment]
I couldn't see anything obvious, but I'll have a better look tonight.

**Comment by latenitefilms** [comment]
Ah right, I see what you mean - will give it a bash!
