### ISSUE TITLE
Move Proxy Icon Code from cp.plugins.menu.manager

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#384]
Currently the Proxy Icon Code is located in the `cp.plugins.menu.manager` plugin.

Once #383 is complete, this Proxy Icon Code should be moved into it's own Final Cut Pro plugin, to keep things seperate, for a time when we eventually add support for more applications to CommandPost.

**Comment by randomeizer** [comment]
I'm actually not sure if it makes sense to have one we move to supporting
multiple applications. If at all, I guess it could activate when FCPX is
the active application?

**Comment by latenitefilms** [comment]
Yeah, it's tricky. I know a lot of people love this feature, so we definitely can't remove it - maybe you're right, and we just change the menubar icon if Final Cut Pro is active.

**Comment by latenitefilms** [comment]
I'm not sure the best way to do this - or if it's even worth it. Thoughts?

**Comment by randomeizer** [comment]
What if we make it an actual separate menu?

**Comment by latenitefilms** [comment]
As in, we add a "Final Cut Pro" preferences panel? Fine by me!

We could potentially move "Control CommandPost Shortcuts within Final Cut Pro" in there as well?

**Comment by randomeizer** [comment]
Well, yes, we having a Final Cut Pro panel would be useful, but not what I was suggesting exactly. Rather, could we have the proxy icon show up by adding a new menubar with that icon? Along-side the standard menu.

**Comment by latenitefilms** [comment]
Owww... just saw this. That's a cool idea, but I've come up with something simpler anyway.
