### ISSUE TITLE
Timeline Clip Height Increase/Decrease No Longer Works

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#390]
The appearance inspector pops up when you press **CONTROL+OPTION+COMMAND+PLUS/MINUS**, however keeping the shortcuts keys held down doesn't change the zoom controls for some reason. No error messages.

**Comment by randomeizer** [comment]
This seems to be working for me @latenitefilms. Can you confirm?

**Comment by latenitefilms** [comment]
Nope, still not working here on latest `develop`. No errors messages. The appearance inspector pops up, the the value bar doesn't change.

**Comment by randomeizer** [comment]
Weird

**Comment by randomeizer** [comment]
This still works fine for me. Maybe an El Capitan vs Sierra issue?

**Comment by latenitefilms** [comment]
Possibly - although it's definitely worked fine for me in the past.

Basically, `appearance:clipHeight():increment()` and `appearance:clipHeight():decrement()` is doing nothing for me currently. Will try and debug.

**Comment by randomeizer** [comment]
Ok. Hard for me to test from here...

**Comment by latenitefilms** [comment]
Seems to be working fine now. Bizarre! Will close for now.
