### ISSUE TITLE
Add Better Error Messages for when Plugin has Duplicate ID

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#393]

**Comment by randomeizer** [comment]
Fixed.

**Comment by latenitefilms** [comment]
Awesome work!

However, the debug message only shows the ORIGINAL plugin path - not the duplicate plugin path. Any chance we could show both paths?

`2017-03-26 14:30:54:                          Duplicate plugin for 'core.quit': /Users/latenitechris/Documents/Github/CommandPost/src/plugins/core/quit/quit.lua`

**Comment by latenitefilms** [comment]
Also, error'ed plugins don't seem to appear in the Preferences Panel?

**Comment by randomeizer** [comment]
I've only been storing the path for complex plugins, not simple ones. Could possibly make an adjustment...

And yes, duplicate plugins don't appear in the preferences panel because they are not valid plugins. We don't load them. Don't do nothing with them. There's nowhere to store them safely. They are a land mine :P

**Comment by latenitefilms** [comment]
I'm not specifically talking about duplicate plugins appearing in the plugins panel - but more so, any plugins that fail to load (because of a typo).

**Comment by randomeizer** [comment]
If there is a typo in the .lua, we can't get an ID for the plugin, since it doesn't compile, and we get the ID from the returned plugin table. Thus, no ID, nowhere to store it or identify it. It will get logged in the Error Log however.

**Comment by latenitefilms** [comment]
Ah right, no worries.

**Comment by randomeizer** [comment]
It's now listing the 'existing' plugin and 'duplicate' plugin script files in the Error Log when a duplicate occurs.
