### ISSUE TITLE
selectClipAtLane() needs to be rewritten for Final Cut Pro 10.3

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#40]

**Comment by randomeizer** [comment]
Results from the updated selectClipAtLane():

* Old: 27.024ms
* New: 9.231ms

**Comment by randomeizer** [comment]
I created a new pull request for my work here:

https://github.com/fcpxhacks/fcpxhacks/pull/106

Check it out when you get a chance. I'm happy to merge it when you are.

**Comment by latenitefilms** [comment]
Awesome work! I changed it so that it worked in the same direction as the previous version (i.e. Lane 1 refer to the Primary Storyline) - but apart from that, seems way faster, and also seems to work fine in multiple languages. Nicely done! Thank you!

**Comment by randomeizer** [comment]
So it goes from the bottom up? What happens if there is audio underneath?

**Comment by latenitefilms** [comment]
My original intention was that it would ignore the primary storyline and everything under it - however, as it currently works, "Lane 1" is the bottommost clip (even if under the primary storyline), which I think works fine, so maybe we just leave it as is.

**Comment by randomeizer** [comment]
I wonder if it's possible to determine which clip is on the primary
storyline...

**Comment by latenitefilms** [comment]
You can just calculate it based on location. Things on the primary storyline will be vertically centre to the AXLayoutArea.

**Comment by randomeizer** [comment]
Ok. If I get time I'll see if I can tweak it.
