### ISSUE TITLE
Add Watcher for User Plugins?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#401]
Should CommandPost Automatically Reload if new Plugins are added to the user plugins directory?

Thoughts @randomeizer ?

**Comment by randomeizer** [comment]
Yeah, was thinking about that. Probably so.

**Comment by latenitefilms** [comment]
Should this happen in a standalone plugin, or in the plugin module?

**Comment by randomeizer** [comment]
Hmm, good question. The plugin module currently doesn't interact with the
CP app directly, but I guess it could. That being the case, it should do
the watching for /src/plugins instead of the main cp.init.

**Comment by randomeizer** [comment]
I'll sort this one.
