### ISSUE TITLE
Make cp.template not require single '{' characters to be escaped

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#404]
Currently, the `cp.template` extension requires any single `{` characters to be escaped as `\{`, which is annoying, particularly in code with CSS or JavaScript.

Since `{{` and `{%` are the standard characters for inserting LUA output, it should be possible to have single `{` characters work as usual.

Also, consider making the `{%` markup into `{{%`, which would be less annoying to work with for text editors which automatically create matching brackets...

**Comment by latenitefilms** [comment]
Great idea!

**Comment by randomeizer** [comment]
This just needs to be merged.

**Comment by latenitefilms** [comment]
Looks good to me!
