### ISSUE TITLE
Half the 'proxy' icon is cut off

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#406]
When enabling the 'Proxy/Optimised' icon in the menubar, it looks like this:

<img width="249" alt="screenshot_26_03_17__6_53_pm" src="https://cloud.githubusercontent.com/assets/3589315/24329860/b348ee1a-1255-11e7-8355-d3d3b466538e.png">

This may be an El Capitan issue, not sure. Can you replicate?

**Comment by latenitefilms** [comment]
Strange - works fine here!

<img width="308" alt="screen shot 2017-03-26 at 8 00 06 pm" src="https://cloud.githubusercontent.com/assets/22286696/24329903/f1a7b0d4-125e-11e7-89c1-fedf5ffa4937.png">

**Comment by randomeizer** [comment]
As an alternative, what if we made the 'proxy' icon the actual CP icon, but gave it a different colour when a) FCPX is active and b) proxy or optimised is active?

**Comment by randomeizer** [comment]
Interesting that your icon looks a lot 'duller' than mine. Something changed in the font between El Capitan and Sierra I guess...

**Comment by latenitefilms** [comment]
> As an alternative, what if we made the 'proxy' icon the actual CP icon, but gave it a different colour when a) FCPX is active and b) proxy or optimised is active?

That's a cool idea! I like it.

> Interesting that your icon looks a lot 'duller' than mine. Something changed in the font between El Capitan and Sierra I guess...

Yeah, I think all the Emoji's were revamped for a "flatter" look in Sierra.

**Comment by latenitefilms** [comment]
You could also try adding another " " after the Emoji on your system to see if that fixes things?

**Comment by randomeizer** [comment]
You want to take on the 'alternate logo' idea? I can check if an extra space helps with the current implementation.

**Comment by latenitefilms** [comment]
I think I prefer the dots, and it makes it VERY obvious, and I'm also not sure what happens with coloured icons if you use dark mode, but will have a play.

**Comment by randomeizer** [comment]
Hmm. It helps a bit...

<img width="253" alt="screenshot_26_03_17__7_11_pm" src="https://cloud.githubusercontent.com/assets/3589315/24329979/1b244dac-1258-11e7-873e-98bc9718854f.png">

I'm a bit reluctant to use this as a fix, since the number of spaces could be variable depending on the system, and I'm not sure what it will do in Sierra...

**Comment by randomeizer** [comment]
I've pushed a workaround to issue-406 if you want to test it in Sierra. I'm not convinced it's a good solution...

**Comment by latenitefilms** [comment]
What's the icon next to it with the red line?

Does moving the CommandPost icon to a different position fix things?

FCPX Hacks has always had this feature, and I've never noticed it on our El Capitan systems - so I'm wondering if it's just a quirky one-off thing. I'll test out on our other machines when back at the office tomorrow.

#406 looks like this on my laptop:
<img width="377" alt="screen shot 2017-03-26 at 8 16 53 pm" src="https://cloud.githubusercontent.com/assets/22286696/24330014/37f2dc56-1261-11e7-9049-30dcddb7f127.png">

**Comment by randomeizer** [comment]
Yeah, I know it's been around - I never used it.

It is a CPU usage graph from the MemMeters app. It doesn't seem to make any difference what icon it's next to, it's always cut off on my system.

**Comment by latenitefilms** [comment]
No worries. Have you tried a restart? I wonder if it's just macOS being a pain?

**Comment by randomeizer** [comment]
Hmm, interestingly, if I switch 'Display Menubar as Icon' off in Preferences, it looks fine, and if I turn it back on again, it also looks fine with the icon. But as soon as I restart, it cuts off again. Restarting with 'CommandPost' text always looks fine.

Weird.

**Comment by randomeizer** [comment]
I found a workaround by setting the text to " " immediately before applying the proxy icon. No idea why this is necessary.

**Comment by latenitefilms** [comment]
Bizarre! Do you still need the trailing whitespace too?

**Comment by randomeizer** [comment]
Nope. I removed that. Just seeing it to something other than the emoji
seemed to work.

**Comment by latenitefilms** [comment]
Thinking about it, I wonder if [this](https://github.com/Hammerspoon/hammerspoon/issues/1015) is related?

**Comment by randomeizer** [comment]
Yeah, could be.
