### ISSUE TITLE
Switch to major.minor.point version number

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#409]
Currently, we're on 0.79. I'm thinking that for the initial beta release we either make it `0.9.0` or `1.0.0-beta.1`. Or do you want to just go for the jugular and make it `1.0.0`? ;)

**Comment by latenitefilms** [comment]
Definitely not `1.0.0` - that's way too much pressure! I want to have copying and pasting between FCPX & AE done for the big `1.0.0` release - still a looooong way to go.

I was thinking we'd just go `0.79.0`, and do the next bug fix as `0.79.1`, and the next feature update as `0.80.0`.

**Comment by randomeizer** [comment]
Really? A 1.0 release means it's usable right now. I think we're pretty close for that. You'll get a lot more people willing to take a crack at using it that way.

I think we should get our current feature set (pretty) stable, and do a 1.0 release ASAP. A couple of betas to get some testing in a broader range of environments would be useful.

Don't make 1.0 an unreachable target. Let's get it out there and start working towards 1.1 (or 2.0).

**Comment by latenitefilms** [comment]
But... https://9to5mac.com/2016/12/27/handbrake-version-1-0-0-download/

**Comment by latenitefilms** [comment]
Although, you do make a good point. Well, given we're changing the name, hell, maybe you're right, maybe we should just go `1.0.0`.

**Comment by randomeizer** [comment]
And? Chrome is on version 56.xxx...

**Comment by randomeizer** [comment]
We're not just changing the name. We're releasing an actual application, rather than a bunch of scripts. It's worth a noteworthy version number.

**Comment by latenitefilms** [comment]
Haha, sold!

**Comment by randomeizer** [comment]
I've pushed an update that lets us compare versions using the `semver` library instead of 'tonumber', along with renaming a couple of the variables and i18n values related to the app name and version. The actual version number comes from the App build, for which I have created an issue [here](https://github.com/CommandPost/CommandPost-App/issues/10).
