### ISSUE TITLE
Redesign HUD to use Panels System (HUD v2)

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#414]
@randomeizer - I wonder if it's worthwhile rebuilding the HUD prior to release to use the same kind of "panels" system as we're using for the welcome screen and preferences? That would make it heaps easier to add HUD features in the future?

**Comment by latenitefilms** [comment]
I think this issue was incorrectly closed. The point of this issue to to re-work the HUD so that each individual panel is essentially its own plugin.

**Comment by randomeizer** [comment]
Yeah, I put an incorrect issue number in one of my comments :P

**Comment by latenitefilms** [comment]
We should also probably move the HUD Preferences from the menubar to a Preferences tab.

**Comment by latenitefilms** [comment]
Note to self: we should add something to the HUD which tells you when the library was last backed up.

**Comment by latenitefilms** [comment]
I think for HUD v2 I'm going to add:

- Add window snapping to HUD (originally issue #1619)
- More customisable buttons
- A "notepad" panel similar to what you're building. Will have to see if I can work out a clever way to save the notes within the library bundle - the tricky part is working out which library is currently selected.
- A FCPXML editor. Basically a drop zone where you can drag projects/clips from the FCPX Browser to the drop zone, it loads up the FCPXML into a text box with a "search and replace" feature and a "Send back to FCPX" button.
- Some more informational stuff - like when the FCPX library was last backed up.

Here's some ideas for rich text editors in HTML:

https://draftjs.org
https://quilljs.com

This one has find & replace:

https://github.com/DiemenDesign/summernote-text-findnreplace
https://github.com/summernote/summernote/

**Comment by latenitefilms** [comment]
A curated list of awesome WYSIWYG editors:
https://github.com/JefMari/awesome-wysiwyg

**Comment by latenitefilms** [comment]
Krzysztof Szychowski [suggests](url
https://www.facebook.com/groups/commandpost/permalink/2205231916399174/?comment_id=2212921675630198&comment_tracking=%7B%22tn%22%3A%22R%22%7D):

> Hi. Not sure how possible this is, but it would be helpful if the HUD window could be collapsed (disclosure triangle?). This would open up lost real estate taken up by the HUD gui when not in use. Laptop work come to mind. Thx Krzysztof
