### ISSUE TITLE
Adobe Premiere - Change all clip Default Scales to Frame Size

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#417]

**Comment by latenitefilms** [comment]
@randomeizer - FYI: this was just thrown together very quickly to help someone out. Could be a really handy feature for Premiere users - but I'm not exactly sure where it fits in currently with CommandPost. You'll also hate the fact that it's all in a single function.

**Comment by randomeizer** [comment]
Maybe we should create a separate project in GitHub for 'experimental' plugins, where we can put stuff that we are testing out, or isn't quite ready for prime time? People can install them in their 'Custom Plugins' folder until we mainline them.

**Comment by latenitefilms** [comment]
Yeah, that's a good idea. However, I think for now, I'm just happy to leave this here. It's actually quite useful for Premiere users, so I'd like to include it in CommandPost as soon as we have a proper game plan for multi-app support.

**Comment by randomeizer** [comment]
Sure, but we're not preventing people using it. It just doesn't really have
anywhere it belongs yet.

Isn't that kind of the point of having a custom plugins directory?

**Comment by latenitefilms** [comment]
Yeah, you're completely right - that's the whole point of the custom plugins directory.

Let me ponder this some more...

**Comment by latenitefilms** [comment]
Ignore this issue! I overlooked the fact that Premiere already has the ability built in!

<img width="573" alt="screen shot 2017-03-29 at 12 50 53 am" src="https://cloud.githubusercontent.com/assets/22286696/24425210/0de2fcbc-144f-11e7-9bef-2e3dca60fae5.png">

**Comment by randomeizer** [comment]
Haha, nice.
