### ISSUE TITLE
Replace AppleScript Dialog's with Webviews?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#418]
For whatever reason the AppleScript dialog boxes are always a pain. They're very unreliable - at least on Sierra. I'm wondering if we should replace them all with webview's prior to release?

Related: https://github.com/Hammerspoon/hammerspoon/issues/337#issuecomment-289763801

**Comment by randomeizer** [comment]
Hmm. Perhaps? The non-responsiveness send related to the click/release
problem we've seen in Sierra with other things too.

**Comment by latenitefilms** [comment]
Do you have ANY issues with the AppleScript UI's on your machine or is it just Sierra causing problems? It could also just be my laptop for whatever reason. I need to do some proper testing on our iMac's.

**Comment by randomeizer** [comment]
I haven't noticed anything in particular with the dialog boxes or other
AppleScript stuff.

Testing on some other machines with Sierra would be helpful.

**Comment by latenitefilms** [comment]
@randomeizer - Looks like it's definitely a Sierra bug/issue.

For example, if I click **Advanced Features > Enable Moving Markers** on my MacBook Pro (Retina, 15-inch, Early 2013) running 10.12.3, the "CommandPost wants to make changes" will popup. However, if I want to press the **Cancel** button, it will take at least three click attempts before it actually clicks.

The same thing happens on our iMac (Retina 5K, 27-inch, Late 2014) running 10.12.3.

However, I can't reproduce this bug on our iMac (Retina 5K, 27-inch, Late 2014) running 10.11.6.

At some point along the lines, I changed the way we make AppleScript dialog boxes appear frontmost, so I might go back and have a look at `cp.dialog` to see if something I've done in there is causing the weirdness.

**Comment by latenitefilms** [comment]
Ummm... changing the AppleScript in `cp.dialog` & `cp.tools` didn't make a difference. Doh!

The other thing we could try is putting all the menu functions in a `hs.timer`?

**Comment by randomeizer** [comment]
The root of the problem is the issue with mouse clicks not working
correctly for you. Everything else is just a work around, webview included.

**Comment by latenitefilms** [comment]
It has to be something in our code though, as if I type the below into the Hammerspoon Console, it works fine:

`hs.osascript.applescript('display dialog "test"')`

Very odd!

**Comment by randomeizer** [comment]
Huh...

**Comment by latenitefilms** [comment]
Do you have access to a Sierra machine to do some testing (or could you temporarily install Sierra on an external hard drive)? Be interested to see if you can reproduce as well.

I'm not really sure of the best way to resolve this? Any ideas on how we can better test it? I'm sure the Hammerspoon community would be happy to help fix, if we could actually determine what's going on?

**Comment by randomeizer** [comment]
Nothing currently. I'll see if I can come up with something...

**Comment by latenitefilms** [comment]
Interestingly...

If I add:

```
hs.osascript.applescript('display dialog "test"')
dialog.displayMessage("test")
```

...directly after `function mod.toggleMovingMarkers()` in the Moving Markers plugin, the first two dialog boxes work fine, and when I click the 'OK' buttons on these two dialog boxes, they close instantly. However, the third "CommandPost wants to make changes" dialog boxes takes a few clicks before it's actually registered that a button has been clicked.

If I execute the following line in the Hammerspoon Console, it also takes me a few goes (i.e. three clicks) before the click actually registers:

`require("cp.tools").executeWithAdministratorPrivileges("echo test")`

No idea what this means yet...

**Comment by latenitefilms** [comment]
I'm going to close this out for now, as I don't think using a `hs.webview` for dialog messages is the way to go.
