### ISSUE TITLE
Add support for Plugin Bundles?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#426]
Now that "spoons" are [actually a thing](https://github.com/Hammerspoon/hammerspoon/issues/1182#issuecomment-292265458), maybe we should consider supporting CommandPost "plugin" bundles? Basically, all I'm thinking is that if you have a bundle with the `.cpPlugins` extension, then CommandPost will load it's contents (i.e. any Lua files) as a normal plugin. Thinking about it - it might already do this anyway, in which case, we'd just need to give the `.cpPlugins` a nice icon, and adjust the code for when you drag a `.cpPlugins` into the CommandPost dock icon.

Thoughts?

**Comment by randomeizer** [comment]
Spoons are different to plugins at this point. But we can think about how
we can bundle them into a package or something similar.

**Comment by latenitefilms** [comment]
Yeah, I'm definitely not saying we need to duplicate the "spoon" functionality - but I do really like the idea of a plugin bundle. However, doing a quick test, because a bundle is really just a folder anyway - it looks like the functionality is already "built in". For example, if I put a "spoon" in `~/Library/Application Support/CommandPost/Plugins` folder, it will read the contents of the "spoon" as a plugin anyway. So basically, all I'm thinking is we just add a new bundle type and icon to CommandPost and away we go!

![screen shot 2017-04-07 at 1 16 33 pm](https://cloud.githubusercontent.com/assets/22286696/24784236/81fc83ba-1b94-11e7-9863-0903b82ce49d.png)

**Comment by randomeizer** [comment]
I think the main functionality we might add is having CP automatically copy
the bundle into the 'Plugins' directory when it's executed, then reload the
app.

**Comment by latenitefilms** [comment]
Yes, correct. Currently if you drag a "spoon" into the Hammerspoon Dock item it automatically moves that spoon into the `~/.hammerspoon/Spoons/` directory - so I guess we just need to duplicate something similar in that if you drag a "cpPlugin" into the CommandPost Dock item it automatically moves that plugin into the `~/Library/Application Support/CommandPost/Plugins` directory.

FYI: This functionality can be found in `Hammerspoon/MJAppDelegate.m`.

I'll have a go at implementing this over the weekend.
