### ISSUE TITLE
Use plist module instead of PlistBuddy/Defaults

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#45]
Currently `bindKeyboardShortcuts()` uses Command Line tools to read the Command Set values, which works great, but is really slow - especially when `bindKeyboardShortcuts()` needs to get the values of so many different shortcut keys. It would be much better if we only had to read the Command Set file once, put it's data into a table, then do all the "reading" in native Lua.

**Comment by randomeizer** [comment]
Should be possible using the plaster.lua module that clipboard.lua is
using.

**Comment by latenitefilms** [comment]
Completed (incorrectly) in #60.
