### ISSUE TITLE
Move all _NS values into new file for cp.finalcutpro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#474]

**Comment by randomeizer** [comment]
Want me to take on this one? I think getting 10.3.3 compatibility is the main priority now right?

**Comment by latenitefilms** [comment]
If you have time, that would be amazing.

Yes, once we get everything playing nicely on both 10.3.2 and 10.3.3, I think we're pretty much all good to release 1.0.0-beta.1?

**Comment by randomeizer** [comment]
I'll get started on it tonight. I'll let you know if I don't get time to
finish.
