### ISSUE TITLE
Improve Feedback Form UI Feedback

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#480]
After hitting submit, the form stays visible for a couple of seconds then disappears. Some kind of confirmation that it was successful could be nice.

**Comment by latenitefilms** [comment]
Agreed. I was planning to eventually do this in #347.

Ideally, when you press "submit" it would be great if it closed the `webview` (or at the very least hid it) and did the uploading in the background, then displayed a dialog message when complete (or failed).

Do you want to tackle or shall I?
