### ISSUE TITLE
fcp:selectMenu() is unreliable

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#485]
For example, the following code will select "Color & Effects" instead of "Default":

`fcp:selectMenu("Window", "Workspaces", "Default")`

Screenshot:

<img width="576" alt="screen shot 2017-04-18 at 11 17 24 pm" src="https://cloud.githubusercontent.com/assets/22286696/25133394/e9980482-248f-11e7-85d6-bd35792f9594.png">

**Comment by randomeizer** [comment]
This is essentially an issue caused by us currently caching the menu item values so that we can work across different languages. The only good solution is to see if we can dig into FCPX's Menu .nib files and figure out what the alternate text for different languages is automatically. I'm not certain it's actually going to be possible, but its worth looking into.

**Comment by latenitefilms** [comment]
What about if we manually created a new `menumap.json` for each language and Final Cut Pro version - then used that to get around the language translation (i.e. to translate between our hard coded menu selection, and what actually appears in FCPX)?

For example, if the below is triggered:

`fcp:selectMenu("Window", "Workspaces", "Default")`

...but the language is Japanese, we use the menumap.json files to translate the hardcoded English to Japanese, then use GUI Scripting to actually select the menu item based on this translation on the fly?

This would mean it wouldn't matter if menu items move around in position.

Thoughts?

**Comment by randomeizer** [comment]
Digging around in the MainMenu.nib files, I think it should be possible to pull it from the app, which is a better long term option. Leave it with me for now.

**Comment by latenitefilms** [comment]
Nice one! Let me know if you find anything useful in the "debug" menu items too!

**Comment by randomeizer** [comment]
Do you know how to activate the Debug menu? There were some interesting
menu title I noticed. I'll dig them out tomorrow.

**Comment by latenitefilms** [comment]
Nope - I've only ever got the Prefeneces panel working:

https://latenitefilms.com/blog/fcpxs-hidden-debug-preferences/

You might be able to trigger the Objective-C call through Scripting Bridge:

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ScriptingBridgeConcepts/Introduction/Introduction.html

...or just temporarily swap a menu item around, so that "About Final Cut Pro" actually just triggers a debug command?
