### ISSUE TITLE
Welcome Screen Fails due to JavaScript Errors

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#487]
It looks like something has gone funky with the welcome screen after you did the tweaks to `cp.web`?

None of the buttons are working due to a JavaScript error: `SyntaxError: Unexpected token '&'`

I think it's because the code is replacing the quotes in the JavaScript with `&quot;`?

```
(function(){
		var button = document.getElementById(&quot;buttonobxyspjdzzryofyxjved&quot;);
		button.onclick = function (){
			try {
				var result = [&quot;introContinue&quot;];
				webkit.messageHandlers.welcome.postMessage(result);
			} catch(err) {
				alert(&#39;An error has occurred. Does the controller exist yet?&#39;);
			}
		}
	
})();
```

**Comment by latenitefilms** [comment]
The problem's in `cp.web.generate` in the `mod.javascript` function, but I'm not sure of the best way to fix, so might leave with you @randomeizer.

**Comment by randomeizer** [comment]
I need to write better documentation in the `cp.web.html` module...

**Comment by latenitefilms** [comment]
Haha... Shouldn't you be sleeping?

**Comment by randomeizer** [comment]
Yes 😜

I did that fix via the website on my iPad. Hehe...
