### ISSUE TITLE
Prevent Disabling Vital Plugins?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#499]
@randomeizer - Is it worth adding a plugin variable (for example, something called `allowDisable`?), which if set to `true`, disables the "Disable" link in the Plugins Preferences Panel, to prevent users from accidentally turning off something really important? Either that or we just add a very strong warning message, when a user disables "core" plugins?

**Comment by randomeizer** [comment]
Yeah, I was thinking about this. We could have an optional 'required' field for critical plugins. Another thing would be to check for dependencies and warn if the particular plugin will have a wide-reaching effect...

**Comment by latenitefilms** [comment]
Haha, yes, `required` is a much better label than `allowDisable`.

A dependencies check would also be a good addition I think.
