### ISSUE TITLE
Add textbox to cp.web.ui

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#504]

**Comment by randomeizer** [comment]
Easy enough to do. What's it being used for exactly?

**Comment by latenitefilms** [comment]
I was going to use it for the WebApp password. However, maybe a button and popup alert is better?

**Comment by randomeizer** [comment]
Well, I'm sure it will get used. Should there be a 'password' option as
well?

**Comment by latenitefilms** [comment]
Yep, great idea!
