### ISSUE TITLE
Shortcut Panel should not display Keys already in use

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#509]
Currently you can apply multiple actions to the same shortcut.

I think if CONTROL+SPACEBAR is already assigned to something (for example), then it should not be available in the key list (as it's already in use).

It would require a bit more code (although I think we've already done all the hard bits) - but it might also be worth checking the active Final Cut Pro command set as well for FCPX shortcuts to avoid conflicts?

**Comment by randomeizer** [comment]
Yeah, I'm aware it's an issue. I'm not exactly sure what the solution is.
Filtering out individual key combos in the drop-down boxes is impractical
(we don't have JavaScript code to check every possible key combo that
exists available to us. It's more likely to be something where messages go
back and forward between the webview and the backend LUA code saying
'duplicate key combinate'. The question then is, what is the correct way to
handle the situation? Does the new one override the old one? Do we prevent
the new combo from being applied? In which case do we clear the drop-down
boxes for the new key combo, or leave them there?

**Comment by latenitefilms** [comment]
Well, all the "logic" should definitely be done in Lua land - not JavaScript.

I like the idea of each key dropdown only containing AVAILABLE keys. So for example, the interface won't even allow you to select CMD+C, because it's already used by Final Cut Pro. Assuming the user hasn't changed the default shortcuts, then the user won't be able to assign CONTROL+OPTION+COMMAND+H, as it's already used by the Highlight Playhead command.

Maybe what we need to do is, when the panel first loads, it injects an array of all the used shortcuts into the panel. Then we have a JavaScript function that removes all used shortcuts from each of the drop-downs. Then when a user changes a shortcut, we simply just need to re-inject the array of used shortcuts, and everything will update.

Thoughts?

**Comment by randomeizer** [comment]
Well, we can't just remove 'C', because CMD+SHIFT+C is still fine even if 'CMD+C' is not. The list of letters available is on a per-modifier combo basis. Every single combo would have a different set of characters available. So, there are about 20 key combos times about 35 keycode options times however many commands are available. And a soon as someone changes a shortcut combo, the list is invalidated.

Not saying its impossible, it's just going to take some thinking about.

**Comment by latenitefilms** [comment]
Yes, the Keys list would be different depending on what the Modifier value is set to.

As this would all be done in the JavaScript-land, I'm assuming this would be pretty quick to update.

We basically work out in Lua-land, an array of shortcuts that are already in use (and therefore shouldn't be listed in the Shortcuts Panel), pass this array to JavaScript via injection, then the JavaScript calculates the Key list on the fly.

**Comment by latenitefilms** [comment]
Essentially... when the Panel HTML first loads, all the keys will be listed, then we use JavaScript to remove items already in use.

**Comment by latenitefilms** [comment]
FYI: This will be addressed in #709
