### ISSUE TITLE
Replace cp.uuid with hs.host.uuid?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#515]
Thoughts @randomeizer ?

**Comment by randomeizer** [comment]
I guess? Any particular reason?

**Comment by latenitefilms** [comment]
Nope, no real reason - I just figured you probably just didn't know about `hs.host.uuid`, and it makes sense to make use of Hammerspoon's built-in extensions when possible.

**Comment by randomeizer** [comment]
I was aware of it. Not sure why I chose not to use it exactly.
