### ISSUE TITLE
Prevent all the wfilter error messages in Error Log

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#516]
It would be good to stop `wfilter` filling the Error Log with irrelevant errors like:

```
2017-04-23 14:09:04: ********
2017-04-23 14:09:04: 14:09:04 ERROR:   wfilter: app Brother HL-1110 series @ Iain’… is not registered!
2017-04-23 14:09:04: ********
```

**Comment by randomeizer** [comment]
Yeah, I'm not exactly sure what triggers these. It's from inside the
hs.window.filter library

**Comment by latenitefilms** [comment]
Basically, we just need to filter things a bit better.

**Comment by latenitefilms** [comment]
`hs.window.filter` is used in:

* [cp.apple.finalcutpro](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/apple/finalcutpro/init.lua#L1311)
* [cp.apple.finalcutpro.ui.WindowWatcher](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/apple/finalcutpro/ui/WindowWatcher.lua#L71)

I've added a `logname` value to these two instances, to help work out which one is causing the most errors. We can then work out how to "refine" the filters a bit better to avoid these errors. Or we could just adjust the `loglevel` - but I'd prefer not to do this unless we have to.

**Comment by latenitefilms** [comment]
Ummm... I'm still seeing this:

```
2017-04-25 12:12:53: ********
2017-04-25 12:12:53: 12:12:53 ERROR:   wfilter: app Final Cut Pro is not registered!
2017-04-25 12:12:53: ********
```

**Comment by randomeizer** [comment]
Yeah, it would be good to know what the actual problem it's reporting about
is. Registered with what?

**Comment by latenitefilms** [comment]
I think it's just because of the way we've set up the filters. When I first started playing with window filters I have no idea what I was doing - so the filters are probably way too broad.

I'll have a proper read of this sometime:
http://www.hammerspoon.org/docs/hs.window.filter.html

**Comment by latenitefilms** [comment]
This could also be related to the reason why SOMETIMES CommandPost doesn't think Final Cut Pro is active when it really is.
