### ISSUE TITLE
Create Final Cut Pro Version Module

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#531]
Currently `cp.apple.finalcutpro.ids` is using it's own `currentVersion()` function - however, it should really just get the version from `cp.apple.finalcutpro:getVersion()`. I'm not sure of the best way to do this?

Also, the Final Cut Pro IDs should be "refreshed" when you load a different version of Final Cut Pro. Maybe this should be added to `plugins.finalcutpro.watchers.version`?

Thoughts @randomeizer ?

**Comment by randomeizer** [comment]
Yeah, ideally. The reason it doesn't right now is because 'requiring' the
main `cp.apple.finalcutpro` directly into `ids` creates a circular
reference.

And yeah, it's about 70% the for allowing it to be updated if the version
changes, but doesn't actively check the version yet.

**Comment by latenitefilms** [comment]
> Yeah, ideally. The reason it doesn't right now is because 'requiring' the main `cp.apple.finalcutpro` directly into `ids` creates a circular reference.

How do we get around this? Do we just put the version code in it's own Lua file, so both `finalcutpro/init.lua` and `finalcutpro/ids/init.lua` can access it?

> And yeah, it's about 70% the for allowing it to be updated if the version changes, but doesn't actively check the version yet.

No worries - will be good to add this, as I'm currently mainly using 10.3.2 at the moment for actual jobs, but am still using 10.3.3 for CommandPost testing.

Feel free to assign the issue to me if you want me to tackle?

**Comment by randomeizer** [comment]
That's one option. I'm wondering if we actually make 'ids' into a 'version' module, since it is basically all about version handling. I'll think about it.

**Comment by latenitefilms** [comment]
Yeah, that sounds good to me!

**Comment by latenitefilms** [comment]
I'm going to close this issue, as it will be addressed in #1156.
