### ISSUE TITLE
LibrariesList tests fail if no Library is selected

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#539]
Currently, if no library is highlighted in the browser sidebar, the LibrariesList tests fill fail. The fix is to ensure that a library is highlighted before running the test (or as part of initialising the tests).

This may be an opportunity to set up a 'Test Library' to help create a standard environment we can test in.

**Comment by latenitefilms** [comment]
Has this been addressed in #636 ?

**Comment by randomeizer** [comment]
Yes
