### ISSUE TITLE
Improve support for boolean 'is' properties

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#542]
We have a lot of 'isXXX' true/false properties, and they get toggled a lot. That means we usually have to create three methods for each property - a get, set, and toggle - along with handling what toggling those properties actually does.

I'm proposing a `cp.is` module which basically creates a callable table that will handle getting, setting, toggling as well as 'watching' for boolean properties. In addition, we can 'AND' or 'OR' them together to make it easy to combine different boolean properties to test if something should be enabled or disabled, for example.

A typical case is enabling or disabling feature such as 'Scrolling Timeline'. An addition is made to the `cp.config` to support creating a `cp.is` value that gets/sets a particular preference. It would go from this:

```lua
function mod.isEnabled()
    return config.get("myPluginEnabled", true)
end

function mod.setEnabled(value)
    config.set("myPluginEnabled", value)
    -- This actually triggers the change to activate/deactivate the functionality
    mod.update(value)
end

function mod.toggleEnabled()
   mod.setEnabled(not mod.isEnabled())
end
```

...to this:

```lua
mod.isEnabled = config.is("myPluginEnabled", true):watch(mod.update)
```

You then get/set/toggle the value like so:

```lua
-- get
local value = mod.isEnabled()
-- set
mod.isEnabled(false)
-- toggle
mod.isEnabled:toggle()
```

Let's say you have a plugin that requires authentication to work. You could do something like this:

```lua
mod.isEnabled = config.is("myPluginEnabled", true):watch(mod.update)
mod.isAuthenticated = config.is("myPluginAuthenticated", false)
mod.isActive = mod.isEnabled:AND(mod.isAuthenticated):watch(mod.activate)
```

The `mod.activate` method would get notified whenever either `isEnabled` or `isAuthenticated` changed, and the value of `isActive` will only be true when both `isEnabled` and `isAuthenticated` is true.

**Comment by latenitefilms** [comment]
Sounds good to me! However, rather than having multiple functions, I'd just combine them into one.

So for example, rather than `isEnabled` and `setEnabled`, just have `enabled(value)`.

**Comment by randomeizer** [comment]
Yep, that's exactly how it is. To 'get', you call `isEnabled()` (no parameters) and 'set' you call `isEnabled(false)`.

**Comment by latenitefilms** [comment]
Ah, right - perfect! Do you need the "is" though? Is it better to just have `enabled()`?

**Comment by randomeizer** [comment]
For the moment I've kept them as `isEnabled` as opposed to `enabled`, to minimise changes else where. Plus, it makes it simpler to find them later.

We should probably pick a convention with 'is', 'get' and 'set' for functions, but right now it's all over the place :P

**Comment by latenitefilms** [comment]
No worries. I think we drop the is/get/set if it's a single function. Keep it consistent with things like, for example [hs.dockIcon([state])](http://www.hammerspoon.org/docs/hs.html#dockIcon). However, if for whatever reason it's spread over multiple functions, then it's fine to use set/get.

Thoughts?

**Comment by randomeizer** [comment]
I've also considered a similar system for other values. But booleans were the priority and are a bit different in that you can combine them. But something similar for, say:

```lua
mod.email = config.value("myPluginEmail"):watch(function(newValue) verifyEmail(newValue) end)
```

...could definitely be useful. At that point, switching to 'enabled' vs 'isEnabled' probably makes sense.

**Comment by latenitefilms** [comment]
Ah right - sounds good! Thanks mate!
