### ISSUE TITLE
Webview's don't centre properly on dual screens

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#551]
@randomeizer - What's wrong with this code?

```
local screenFrame = screen.mainScreen():frame()
local defaultRect = {x = (screenFrame['w']/2) - (mod.defaultWidth/2), y = (screenFrame['h']/2) - (mod.defaultHeight/2), w = mod.defaultWidth, h = mod.defaultHeight}
```

**Comment by latenitefilms** [comment]
I think this has been fixed in the Preferences window - it now just need to be fixed in the Welcome Manger, Watch Folder Manager, and Feedback Form Manager.

**Comment by randomeizer** [comment]
Yeah, I fixed it in Preferences. We can use that as a reference.
