### ISSUE TITLE
Regex for cp.apple.finalcutpro:menuBar()?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#556]
I wonder if it's also worth looking at the [hs.application:selectMenuItem(menuitem)](http://www.hammerspoon.org/docs/hs.application.html#selectMenuItem) code, and implementing the ability to use regex in `cp.apple.finalcutpro:menuBar()`? This could be handy for things like the menu items that also contain a "(Default)" suffix, etc. Thoughts?

**Comment by randomeizer** [comment]
Yeah, I've thought about it a bit. Maybe a simpler format that uses */? for
multiple/single character replacements?

**Comment by latenitefilms** [comment]
Regex confuses me at the best of times, so I'm happy to trust your judgement and knowledge on this! I was just thinking it might allow us to remove some of the workarounds we've already built into the Batch Export plugin.

**Comment by latenitefilms** [comment]
I'm just going to close this issue for now, as it doesn't seem that important.
