### ISSUE TITLE
Remove cp.commands.englishKeyCodes?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#557]
I'm not sure we need `cp.commands.englishKeyCodes` anymore as Hammerspoon 0.9.53 includes a fallback to ANSI US keyboard values for `hs.keycodes.map`?

**Comment by randomeizer** [comment]
Yeah, I'm not sure either.

**Comment by latenitefilms** [comment]
I'm just going to close this issue for now, as it doesn't seem that important.
