### ISSUE TITLE
Add "Commands" to all Plugin features that don't currently have them

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#582]

**Comment by randomeizer** [comment]
what does  this mean exactly?

**Comment by latenitefilms** [comment]
Currently, some features like the new "Text to Speech" tool, and even some basic features (like "Open Error Log") don't have Command's yet (i.e they can't be added to Final Cut Pro's Command Editor).

I just want to go through and make sure every "feature" has a "command".

**Comment by randomeizer** [comment]
Ah, got it.
