### ISSUE TITLE
Zoom to Selection Shortcut

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#592]
Paul Murray [writes](https://www.facebook.com/groups/commandpost/permalink/1857240574531645/):

> Very excited to be part of this and hope that I can make some kind of contribution. Apologies if this has already been covered. Possibly the short cut that I miss the most from FCP Legacy is/was the “Fit Selection” option which used to be ALT + Shift Z or Y depending where you were on the planet. I do not see this function in FCPX and [this](http://www.fcp.co/forum/4-final-cut-pro-x-fcpx/20783-is-there-fit-selection-command-in-fcpx-timeline-as-in-fcp6-7) is the closest I can find to reproducing it.

**Comment by latenitefilms** [comment]
@randomeizer - Although I think what you've done is really awesome, I wonder if there's a way to make it automatically "snap to" the correct zoom/position, rather than "find it"?

I'm pretty bad at maths - but I feel like we could use some of the similar logic to the scrolling timeline to work out what the zoom factor should be to "fit" a selection, then we just need to move the timeline position bar to wherever the start of the first selection is located?

Thoughts?

**Comment by randomeizer** [comment]
The short answer is, not really. It's not a linear equation. If we knew
what the algorithm was, then maybe, but without it, or would just be
guessing.

The value of the slider goes from 0 to 10. The Shift-Z shortcut fits the
whole timeline into the width of the Timeline view area, and is somewhere
around 5.34, up to 5.42. 0 zooms out and fits it into about 1/5 of the
timeline view area. 10 is the same on every timeline - about 1/2 a frame.

So, every timeline is a different length, every timeline scales in and out
slightly differently and going from say 8 to 9 has a much different effect
than going from 9 to 10.

**Comment by latenitefilms** [comment]
I wonder if we could just run "Zoom to Selection" on a whole bunch of test clips, store the results, throw them in a spreadsheet, and reverse engineer the formula required?

**Comment by randomeizer** [comment]
Sure, it would have to be something along those lines. Things we would need
to test/record include:

* total length in time and frames (will vary depending on the frame rate)
* selection length in time and frames
* the ratio of the length relative to the amount visible on screen at
various zoom levels between 0 and 10.
