### ISSUE TITLE
fcp:selectMenu("Edit", "Undo Paste") Unreliable

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#593]
FYI: Trying to trigger the Undo menubar item seem unreliable - probably because the label changes depending on what's on the Undo queue.

`fcp:selectMenu("Edit", "Undo Paste")`

**Comment by latenitefilms** [comment]
It could also be that the Undo label isn't actually updated UNTIL you click the "Edit" button?

**Comment by latenitefilms** [comment]
Using UI Browser confirms that the AXMenuItem doesn't seem to update it's AXTitle tag until AFTER the "Edit" button has been clicked.

However, interestingly, the below doesn't seem to work either:

```
local fcpAx = axuielement.applicationElement(fcp:application())
local whichMenuBar = nil
for i=1, fcpAx:attributeValueCount("AXChildren") do
	if fcpAx:attributeValue("AXChildren")[i]:attributeValue("AXRole") == "AXMenuBar" then
		whichMenuBar = i
	end
end
if whichMenuBar then
	fcpAx[whichMenuBar][4][1][1]:performAction("AXPress")
end
```

...nor does trying to trigger the Undo action from UI Browser, which is very odd.

**Comment by randomeizer** [comment]
Could you try triggering the Undo command directly instead of using the
menu?

**Comment by latenitefilms** [comment]
I'm currently just using `fcp:performShortcut("UndoChanges")` - which works fine, but I feel it's a bit slower than the menubar for some reason.

**Comment by latenitefilms** [comment]
@randomeizer - Is this still relevant, or have the changes you've made recently resolved this?

**Comment by randomeizer** [comment]
I don't think I've resolved this one. The main trick is that "Undo" is
followed by the thing that was done, so it changes constantly. In English
it starts with Undo, but in other languages, not sure.

**Comment by latenitefilms** [comment]
@randomeizer - Not sure if this is a fixable problem - so maybe we just close this issue?

**Comment by randomeizer** [comment]
I think it should be fixable. Worst case, we manually click 'Edit' on the way through in this case, and/or use a function that matches "Undo .*"
