### ISSUE TITLE
Watch Folders shouldn't trigger if file is still copying

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#598]
We might have to do something simliar to Telestream Episode?

<img width="435" alt="screen shot 2017-05-08 at 9 28 09 pm" src="https://cloud.githubusercontent.com/assets/22286696/25802497/05f5695c-3436-11e7-9520-f2afcb2eee22.png">

**Comment by randomeizer** [comment]
Yeah, I was wondering how we might handle this...

Can we check the file size a few times and only trigger an import when it
has been the same a few checks in a row?

**Comment by latenitefilms** [comment]
Yeah, that's what I'm thinking. Maybe make the time customisable, like the "File Safety Delay" in Episode.

**Comment by latenitefilms** [comment]
Note to self:

**Adaptive Safety Threshold.** Select the threshold setting to adapt to the update behavior of the file system. Off: the Safe delay is strictly used. Normal and Double: Episode dynamically adapts the delay to the detected intervals between file updates. Use Double if the watch folder often submits unfinished files.

**Watch Folder Poll Interval.** Specify in seconds how often to check for new files in the watch folder.

**File Safety Delay.** Specify in seconds how long a file has to remain unchanged (file transfer is complete) before being submitted.

**Recursion Depth.** Set how many folder levels directly below the monitored directory to poll when searching for files to encode.

**Retry Max Attempts.** Set how many times to try to monitor the watch folder before failing. For example, your computer might be monitoring a Windows share, or an SMB folder, but your computer is disconnected from the network.
