### ISSUE TITLE
Remember Last Project & Layout when restarting FCPX

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#6]

**Comment by latenitefilms** [comment]
@randomeizer - I'm not sure this is still needed with FCPX 10.3?

**Comment by randomeizer** [comment]
Yeah, I was wondering that too. Workspaces basically does this for us.

**Comment by latenitefilms** [comment]
I'm going to close this issue, as I think Apple's fixed most of my complaints in 10.3.
