### ISSUE TITLE
finalcutpro.selectMenuItem() needs to be re-written

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#62]
`finalcutpro.selectMenuItem()` is currently used to get around the fact that users might be using Final Cut Pro in languages other than English. Currently I've only "hardcoded" menu items we're currently using - however, this should be updated to include ALL menu items. We should probably write a little script that generates this code, so that we can just copy and paste.

**Comment by randomeizer** [comment]
So, we will need to a) determine what language is in use, b) load the appropriate plist of menu labels from the target language and c) match that to the menu in the app.

Am I on the right track?

I see there are some language files in the `/hs/fcpxhacks/plist/10-3` folder. Are they used to augment FCPX with the FCPX Hacks menu items? Do they also contain the standard UI text fields?

**Comment by latenitefilms** [comment]
@randomeizer - That's certainly one way to do it, however, I think it's probably just faster/easier to write a LUA script that "reads" all the English menus, then writes some code that we can literally paste in that "translates" these English values into menu item numbers. Basically exactly the same way as it's currently done, but rather than typing everything by hand, we just script it.

**Comment by latenitefilms** [comment]
> I see there are some language files in the /hs/fcpxhacks/plist/10-3 folder. Are they used to augment FCPX with the FCPX Hacks menu items? Do they also contain the standard UI text fields?

No, these are just related to Command Sets.

I believe that MOST (if not all) of the Final Cut Pro menu items are located in `/Applications/Final\ Cut\ Pro.app/Contents/Resources/en.lproj/PELocalizable.strings`, but it's hard to know for certain without doing some serious testing, as, lots of the other frameworks have their own "strings" files as well. For example, a lot of the timeline functions that are shared between iMovie & FCPX are located in the `Flexo.framework`.

**Comment by randomeizer** [comment]
What happens if the UI is not in English, but our code is?

**Comment by randomeizer** [comment]
That's the hard-coding you're referring to? It takes our English labels and figures out a menu number for them? Hmm...

**Comment by latenitefilms** [comment]
Yes, exactly. We basically "hard code" the menu IDs for all the English menus, then that way, we can just use the standard English names for coding, and this function translates everything back into ID codes, that work on any language.

**Comment by randomeizer** [comment]
For reference:

https://github.com/asmagill/hs._asm.axuielement/issues/1#issuecomment-252420401

**Comment by latenitefilms** [comment]
This is looking awesome! Thanks so much @randomeizer!

Thinking about it... I wonder if it's worthwhile instead of saving the JSON data to file, we just save it to `hs.settings` as a 'cache'. For example, the first time the user triggers `hs.finalcutpro.selectMenuItem()`, the cache would be empty, so it would build the menu structure and save it via `hs.settings` for easy access, and will just read off the 'cache' next time round? I'm assuming reading off `hs.settings` would be faster (albeit, in micro seconds) than reading from file? We could then add something to `hs.finalcutpro` that actually builds the menu list on load if Final Cut Pro is already open, so the end-user doesn't get a slight delay the first time they trigger `hs.finalcutpro.selectMenuItem()`. Thoughts?

**Comment by randomeizer** [comment]
Well, we need to save it to file so that people who are not using English
will still function. I don't know if saving to settings would be any faster
- I would like to benchmark it before making any assumptions.

It only loads the menu from file the first time Hammerspoon loads, so I
don't think it will be a big deal. It's pretty much instantaneous already.

**Comment by latenitefilms** [comment]
> Well, we need to save it to file so that people who are not using English
> will still function.

It looks like you're just doing a better implementation of what was originally there... in which case, it should work with any language? If someone triggers `finalcutpro.selectMenuItem({"Final Cut Pro", "About Final Cut Pro"})`, this should lookup "Final Cut Pro" on your funky JSON data file (or `hs.settings` entry for example), then work out the ID of the entry, do the same for "About Final Cut Pro", then trigger the menu item based on IDs - hence it SHOULD work regardless of what language the UI is set to?

> It only loads the menu from file the first time Hammerspoon loads, so I
> don't think it will be a big deal. It's pretty much instantaneous already.

Sweet! Well, that works for me then!

Love the idea of `hs.finalcutpro.ui` too - nice work!!

**Comment by randomeizer** [comment]
Correct. We can manually call the '_generateMenuMap' function when a change
happens in a future version of FCPX, but it isn't called automatically.

**Comment by latenitefilms** [comment]
Well, given that Apple will most likely not remove the menu items we're currently triggering, how about we automatically activate `_generateMenuMap` on a version update, so this happens auto-magically for end-users? That way if Apple adds a menu item or changes around the menu layout slightly in a 10.3.2, then FCPX Hacks will keep working without us having to release an update?

I've just added `settings.get("fcpxHacks.lastFinalCutProVersion")` to the latest `develop` branch, so you could just add a call to `generateMenuMap` when FCPX is updated. I'm currently doing this for the FCPX Hacks console.

**Comment by randomeizer** [comment]
If we run it automatically, and they are in Spanish, the map will be in
Spanish and our links won't work.

**Comment by latenitefilms** [comment]
Ah, right. I see what you mean. Good point.

Well, I assume that MOST FCPX Hacks users are using it in English, so we could put in some language detection, and if FCPX is updated on a system not running in English mode, we can just throw up a dialog box asking the user to restart FCPX in English to rebuild the menu?

Long term, we should probably go back to your original idea and to out a way to determine the menu structure off Final Cut Pro's internal files - but that does seem like a lot of work and experimentation.

**Comment by randomeizer** [comment]
Yeah, if we can detect the language we could do it automatically for English speakers.

I'm not sure how simple restarting FCPX in English is in practice. I have a feeling they would have to change the system language, run FCPX, then change it back again.

I spent a fair bit of time trawling through the `MainMenu.nib` contents yesterday. The menu names are definitely in there, but I haven't been able to find a way of pulling that information out in a way that is useful as yet.

**Comment by latenitefilms** [comment]
> Yeah, if we can detect the language we could do it automatically for English speakers.

You can use the following Terminal command to work out the "system" language:

`defaults read NSGlobalDomain AppleLanguages`

For example, it returns:

```
(
    "en-AU",
    en
)
```

If you have multiple languages set up, the "current" language will be first in the array.

If I set Final Cut Pro to always open in German, you can detect this using:

`defaults read com.apple.FinalCut AppleLanguages`

For example, it returns: 

```
(
    de
)
```

> I'm not sure how simple restarting FCPX in English is in practice. I have a feeling they would have to change the system language, run FCPX, then change it back again.

This can be achieved by changes the AppleLanguages preference, as explained above. Either that or we could just ask the user to do the change themselves (most people working with systems other than English are pretty good at switching languages - as it's fairly common practise).

**Comment by randomeizer** [comment]
So I guess we could offer to do the restart in English for them then, in that case, then revert to the previous language once it's done.

One thing that occurs to me with the 'Menu Map' is that it won't store menus that change when you click them, eg from "Enable X" to "Disable X". Not sure how many of those menus there are - most seem to use checkboxes.

**Comment by randomeizer** [comment]
A couple of examples of this are "Show/Hide Keyword Editor", "Rate/Unrate"

**Comment by latenitefilms** [comment]
> So I guess we could offer to do the restart in English for them then, in that case, then revert to the previous language once it's done.

Yes, exactly. To switch to English you can just to run the following command:

`defaults write com.apple.FinalCut AppleLanguages -array 'en'`

...then if you delete the `AppleLanguages` after you're done, it will default back to whatever the system language is.

> One thing that occurs to me with the 'Menu Map' is that it won't store menus that change when you click them, eg from "Enable X" to "Disable X". Not sure how many of those menus there are - most seem to use checkboxes.

Yeah, this is something we might just have to manually band-aid, if we end up wanting to trigger a function that has two states. Either that, or we build that in now and just "detect" if a menu item has the words "Show" in there, and automatically creates a "Hide" item too?

**Comment by randomeizer** [comment]
The short-term solution is just to always use 'Show X', even if it's
currently 'Hide X'. If it's the same menu item, the lookup should still
work.

**Comment by latenitefilms** [comment]
Ha! Yes, that makes WAY more sense!

**Comment by randomeizer** [comment]
We just have to make sure our FCPX is in a consistent state when we
generate the menu map 😜

**Comment by latenitefilms** [comment]
> We just have to make sure our FCPX is in a consistent state when we
> generate the menu map 😜

Ah, yes, of course. Well, that complicates my idea of letting the end-user's machine generate the menu map when a new Final Cut Pro version is detected. Maybe we do need to write in a solution for solving show/hide if we decide to go down this path.

**Comment by randomeizer** [comment]
I'm thinking it's simplest for us to manage it ourselves for now and just
do a manual update when things change.

**Comment by randomeizer** [comment]
This has been merged with develop.
