### ISSUE TITLE
Globally deactivate all audio waveforms

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#625]

**Comment by randomeizer** [comment]
Globally? What does this mean exactly?

**Comment by latenitefilms** [comment]
I think someone just wanted an option to turn off audio waveforms all together. I don't think this would be very useful personally, but there is a hidden preference for this, so we might as well add it.

**Comment by randomeizer** [comment]
Ah, ok. Hidden preferences are our speciality ;)
