### ISSUE TITLE
Allow loading of localization strings for FCP and Flexo

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#632]
Currently, we are hard-coding some string values used for identifying parts of FCPX. There are a couple of files which contain common strings, such as:

* `<FCP App>/Contents/Resources/<lang>.lproj/PELocalizable.strings`
* `<FCP App>/Contents/Frameworks/Flexo.framework/Resources/<lang>.lproj/FFLocalizable.strings`

One in particular that we're using at the moment is "Range Selection" (in English). This is stored as `FFTimelineRangeSelectionAccessibilityDescription` in the `Flexo.framework` file above.

We need to keep in mind FCP's current language when loading the content. We also need to decide if it's worth keeping the whole contents of these files in memory once used, or if we should load it on demand, or something in-between, such as caching specifically-requested key values, but not everything.

**Comment by latenitefilms** [comment]
Yeah, I was going to implement your above suggestion this morning but ran out of time to properly test it - so just hard coded for the short term. I definitely think this is the best way to do it.

**Comment by latenitefilms** [comment]
I think we should cache it, but it needs to be refreshed on FCPX startup in case the user has changed the FCPX Language.

**Comment by randomeizer** [comment]
I'd rather just cache the requested keys individually, but yes, I agree it
needs to be updated when the language changes.

**Comment by latenitefilms** [comment]
Maybe we just cache the individual keys - but we cache them for all languages in an array, so we don't have to re-read the plists when we change languages?

We could even cache stuff like this using `hs.settings` or even our own SQLite database to improve CommandPost startup times?

**Comment by randomeizer** [comment]
Well, I want to investigate what's showing down start up times - it seems
to have gotten lately. But I would prefer to benchmark it and pin down the
actual causes.

With regards to these values, I don't think we will actually have many that
we actually use, and loading all languages at once seems wasteful.

I have a couple of ideas on how to implement it. I'll have a go after #546
is wrapped.

**Comment by latenitefilms** [comment]
> Well, I want to investigate what's showing down start up times - it seems
> to have gotten lately. But I would prefer to benchmark it and pin down the
> actual causes.

Agreed. Lucky for me, someone's built some awesome benchmarking tools!

> With regards to these values, I don't think we will actually have many that
> we actually use, and loading all languages at once seems wasteful.

Although... _NS values are a bit annoying, as they change between versions, and also seem to change depending on language you're using in Final Cut Pro - so maybe it's better/safer to use Descriptions in future anyway?

> I have a couple of ideas on how to implement it. I'll have a go after #546
> is wrapped.

Sweet! Sounds good. Thanks mate!

**Comment by randomeizer** [comment]
Yeah, it's true about _NS values.

**Comment by latenitefilms** [comment]
It looks like `cp.strings` has already made it's way into `develop`? Does this mean I can close this issue @randomeizer ?

**Comment by randomeizer** [comment]
Yeah, I think so
