### ISSUE TITLE
Shortcut to Add Stabilisation to Selected Clip in Timeline

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#637]

**Comment by latenitefilms** [comment]
This would be REALLY handy.

**Comment by randomeizer** [comment]
This has to be done via the inspector, right?

**Comment by latenitefilms** [comment]
Currently, yep.

**Comment by randomeizer** [comment]
Pasteboard special? 😉

**Comment by latenitefilms** [comment]
That would be ideal if we can work it out!

**Comment by randomeizer** [comment]
Guess we should figure out how to modify them...

**Comment by latenitefilms** [comment]
FYI: Until we master the Pasteboard, I'm just going to tackle this one with GUI scripting.
