### ISSUE TITLE
Tell user to update "Hacks Shortcuts" if they've changed between CP Versions

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#644]
I'm going to assign this to you @randomeizer - as you're messing around with "hacks shortcuts" at the moment anyway.

**Comment by randomeizer** [comment]
This is actually (almost) implemented in #546

**Comment by latenitefilms** [comment]
Awesome, thanks!

**Comment by randomeizer** [comment]
This has been implemented in #546.
