### ISSUE TITLE
Send bug report link from the app to github issue creator

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#65]
Aka, here: https://github.com/fcpxhacks/fcpxhacks/issues/new

**Comment by randomeizer** [comment]
Seem reasonable @latenitefilms?

**Comment by latenitefilms** [comment]
Sorry, but I'd prefer to keep the bug reports going to my email for the time being. This gives me a really good opportunity to chat to end-users about what they like/dislike about FCPX Hacks - and I think forcing end-users to sign-up to Github to report a bug is a bit too annoying.

**Comment by randomeizer** [comment]
Fair enough.
