### ISSUE TITLE
Customised Shortcuts don't save across CommandPost Restarts

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#660]
Could have something to do with this?

`2017-05-21 16:55:24: 16:55:24   commands:     Unable to load shortcuts: '/Users/latenitechris/Library/Application Support/CommandPost/Shortcuts/Default Shortcuts.cpShortcuts'`

**Comment by randomeizer** [comment]
It would seem to be related, but I can't replicate it. I get this:

```
Loading shortcuts: '/Users/david/Library/Application Support/CommandPost/Shortcuts/Default Shortcuts.cpShortcuts'
```

Could you rename your .cpShortcuts file and see what happens? Maybe attach it to this issue?

**Comment by latenitefilms** [comment]
I don't have a `Shortcuts` folder (or a `Default Shortcuts.cpShortcuts` file obviously) - maybe that's the issue?

**Comment by randomeizer** [comment]
Hmm, perhaps. I thought it was creating the directory automatically, but
perhaps not
