### ISSUE TITLE
Scan Final Cut Pro Programatically instead of using GUI Scripting

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#667]
As discussed [here](https://github.com/CommandPost/CommandPost/issues/247#issuecomment-279197450).

I'm thinking maybe we just manually build the list of "built-in" effects, generators, titles and transitions for each version, then the only thing we need to programatically "find" is 3rd party items?

**Comment by randomeizer** [comment]
We should make a list of all known locations for effects/plugins/etc here.

**Comment by latenitefilms** [comment]
# Transitions
**Extension:**  `.motr`
**Locations:**
`~/Movies/Motion Templates.localized/Transitions.localized`
`/Library/Application Support/Final Cut Pro/Templates.localized/Transitions.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/PETemplates.localized/Transitions.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/Templates.localized/Transitions.localized`
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.motr` filename.

---

# Audio Effects
**Extension:**  `.component`
**Locations:**
`/Library/Audio/Plug-Ins/Components`
`~/Library/Audio/Plug-Ins/Components`
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.moef ` filename.
**Notes:**
Final Cut Pro only accepts "validated" Audio Unit's. You can use the [auval](https://developer.apple.com/library/content/technotes/tn2204/_index.html) command line tool to check whether or not an Audio Unit is "valid".

**Extension:**  `.effectBundle`
**Locations:**
`/Applications/Final Cut Pro.app/Contents/Frameworks/Flexo.framework/Versions/A/Resources/Effect Bundles`
**Naming:**
The `Category` and `Template Name` can be determined from the file name. For example:

`Alien.Voice.audio.effectBundle`

In the above example, the `Template Name` is `Alien` and the `Category` is `Voice`.

Even though the XML file does have a `name` value inside, Final Cut Pro only seems to care about the filename.
**Notes:**
The `.effectBundle` files are just an XML file.

---

# Effects
**Extension:**  `.moef`
**Locations:**
`~/Movies/Motion Templates.localized/Effects.localized`
`/Library/Application Support/Final Cut Pro/Templates.localized/Effects.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/PETemplates.localized/Effects `
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/Templates.localized/Effects `
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.moef ` filename.

**Extension:**  `.effectsPreset`
**Locations:**
`~/Library/Application Support/ProApps/Effects Presets/`
**Naming:**
`Category` is embedded within the file itself (it's a binary plist).
`Template Name` is taken from the `.effectsPreset ` filename.


**NOTE:** It looks as if every FxPlug plugin has a `.moef ` file anyway, so this might be irrelevant:

**Extension:**  `.fxplug`
**Locations:**
`/Library/Plug-Ins/FxPlug`
**Naming:**
Metadata stored within `Contents/Info.plist`.
`Category` is taking from plist value: `ProPlugPlugInGroupList > groupName`.
`Template Name` is taken from plist value `ProPlugPlugInList > displayName`.

**Extension:**  `.bundle`
**Locations:**
`/Library/Plug-Ins/FxPlug`
**Naming:**
The `Contents/Info.plist` file doesn't really contain anything useful. 

---

# Generators
**Extension:**  `.motn`
**Locations:**
`~/Movies/Motion Templates.localized/Generators.localized`
`/Library/Application Support/Final Cut Pro/Templates.localized/Generators.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/PETemplates.localized/Generators`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/Templates.localized/Generators`
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.motn` filename.

---

# Titles
**Extension:**  `.moti`
**Locations:**
`~/Movies/Motion Templates.localized/Titles.localized`
`/Library/Application Support/Final Cut Pro/Templates.localized/Titles.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/PETemplates.localized/Titles.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/Templates.localized/Titles.localized`
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.moti` filename.

---

# Compositions
**Extension:**  `.motn`
**Locations:**
`~/Movies/Motion Templates.localized/Compositions.localized`
`/Library/Application Support/Final Cut Pro/Templates.localized/Compositions.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/PETemplates.localized/Compositions.localized`
`/Applications/Final Cut Pro.app/Contents/Plugins/MediaProviders/MotionEffect.fxp/Contents/Resources/Templates.localized/Compositions.localized`
**Naming:**
`Category` is taken from the root folder name.
`Template Name` is taken from the `.motn` filename.

**Comment by latenitefilms** [comment]
Some Effects (like "Keying > Keyer", "Keying > Luma Keyer", and "Color > Color Correction") don't seem to have a Motion file, and are essentially built-in to Final Cut Pro and/or Motion.

There's references to he "Color Correction" tool in `Flexo.framework` and `Ozone.framework`.

This MIGHT be relevant:

`/Applications/Final Cut Pro.app/PlugIns/FxPlug/FiltersLegacyPath.bundle/Contents/Info.plist`
`/Applications/Final Cut Pro.app/PlugIns/FxPlug/InternalFiltersXPC.pluginkit/Contents/PlugIns/Filters.bundle/Contents/Info.plist`

...however, I still think our best option is probably just to use GUI Scripting to build our own "database" of built-in effects for each version/language of Final Cut Pro (similar to the way we used to handle the Final Cut Pro menu items), and then we just programatically add 3rd Party Effects.

It looks like when you click on an internal effect, it doesn't given you the option to "Open a copy in Motion" - so maybe we can just write up a Lua script that generates a list of all effects that don't have this right-click option?

Thoughts @randomeizer ? Is this something you want to tackle, or should I have a bash?

**Comment by latenitefilms** [comment]
FYI: The English scan seems to match the GUI Scripting scans. There still seems to be a few mis-matches for other languages. For example, with German:

```
Missing Generator: Box - Konvergieren
Missing Title: Box - Anzeigen
Missing Title: Box - Drop-Down
Missing Title: Box - Links
Missing Title: Box - Logo
Missing Title: Box - Oben
Missing Title: Box - Überlagern
Missing Transition: Fließen
Missing Transition: Kubik
Missing Transition: Umblättern
Missing Transition: Box - Hineingleiten
Missing Transition: Box - Zentrum erscheinen
Missing Transition: Dokumentation - Schließen & Öffnen
```

Will do some more testing later in the week.

**Comment by randomeizer** [comment]
I'll take a look one I get #626 sorted. Close now.

**Comment by latenitefilms** [comment]
FYI: When adding a Blur Title via the Console, in the Default Layout (with the Libraries panel open), after the title has been added, it doesn't go back to the Libraries panel - it just closes the whole Browser all together.
