### ISSUE TITLE
Add filter media by offline

### ISSUE THREAD

**Issue by waxfingers** [fcpxhacks/fcpxhacks#671]
First of all BIG thank you guys for the massive work on FH and now CP =)  

Would it be possible to add an offline filter (search category) so that we can browse all offline/disconnected media at once? Ideally something similar to rejected, favorites, etc. drop-down menu. (If not/or) additionally, maybe a way of selecting and marking the offline clips on the TL.

Thank you 🍄

**Comment by latenitefilms** [comment]
Thanks for testing CommandPost!

If you just create a new Smart Collection which searches for "missing" this will achieve what you want.
