### ISSUE TITLE
Preferences window doesn't always appear frontmost when opening

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#674]
But it works every time after that.

**Comment by latenitefilms** [comment]
That's weird - working fine for me?

**Comment by latenitefilms** [comment]
@randomeizer - Is this still an issue for you?

**Comment by randomeizer** [comment]
Haven't had a chance to test it yet, but I suspect so

**Comment by latenitefilms** [comment]
@randomeizer says:

> Actually, it looks like the Prefs panel is opened, but not always brought to the front.
