### ISSUE TITLE
CommandPost error after installation

### ISSUE THREAD

**Issue by AlanMacRN** [fcpxhacks/fcpxhacks#684]
I downloaded and installed Commandpost, FCPX 10.3.3 is installed but I get the the error (see attached). I have restarted MBP, opened up FCPX and tried to open CP several times and get the same error screen
![commandpost problem](https://user-images.githubusercontent.com/29248973/26869718-5cd62202-4b65-11e7-9e82-fac89ba95ece.jpg)

**Comment by latenitefilms** [comment]
Apologies @AlanMacRN - that's annoying and strange!

Do you have multiple copies or older versions of Final Cut Pro installed? Have you moved the `Final Cut Pro.app` outside of the `/Applications` directory? Is there anything else that's unusual about your setup (i.e. are you running macOS on an external hard drive or something)?

The next beta of CommandPost will work even if a valid version of Final Cut Pro isn't installed, and we have also tweaked the way these welcome/setup screens work - but I'm not sure that this will solve your specific problem - as it's a bit strange that CommandPost isn't detecting FCPX 10.3.3 if that's what you have installed.

If you press `Command+R` with this screen open does it open the Error Log? If so, can you share the contents of the Error Log here?

**Comment by AlanMacRN** [comment]
Hi, I have just had a notification an hour ago of an update to Commandpost (from the program I suppose??).

I downloaded and installed as per instructions, it sorted through my FX etc and is running AOK now.

I now have Version 1.0.0-beta.8 (1.0.0-beta.8)

Will be going through the features in the next few days/week and will let you know how it goes.

I cannot seem to get command post to open so I can do the Cmd+R to get the error log but everything else seems OK now.

Looking great so far, many thanks to all your team and your quick response.

Regards

Alan McCormick

01634  566567
07815 138915

**Comment by latenitefilms** [comment]
Great news - thanks Alan!

If you do spot any bugs, feel free to use the Issues system here on GitHub, or you can always use the **Help & Support > Provide Feedback...** button from within the CommandPost menubar, as this allows you to attach screenshots and logs which is handy.

Happy cutting!
