### ISSUE TITLE
OPTION+Scroll doesn't work well with non-mechanical scrolling mice

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#691]
Maybe this is something you could tackle @randomeizer - as I feel like it will require some "maths" to get right.

**Comment by randomeizer** [comment]
Why is "maths" in "quotes"? :p

**Comment by latenitefilms** [comment]
Haha, for emphasis?

**Comment by latenitefilms** [comment]
Related: https://github.com/Hammerspoon/hammerspoon/issues/1434

**Comment by latenitefilms** [comment]
FYI - Brian Elliott Tate writes:

> Having a great mouse can really speed up your workflow in FCPX. The best mouse I've ever used (and use today) is the Logitec MX Master, but... it's not perfect to edit with in FCPX out of the box.
> Two essential apps to make it absolutely perfect are Smart Scroll and SteerMouse. Smart Scroll adds the ability to flick through your timeline by clicking and flicking it just as if you were flicking through an iPhone or using a two finger flick with the trackpad. You'll never touch the scrollbars again. You can also do things like easily zoom in and out, etc. with the mouse wheel. It works so well that it feels like Apple originally built it this way.
> The other program, SteerMouse, is like a super powerful version of the included logitec drivers. You can customize every imaginable button and - most of all for me - perfect the mouse Acceleration and Sensitivity so that you can move around with a new level of control.
> Hope this helps anyone else looking for better control while editing!
> https://www.marcmoini.com/sx_en.html
> http://plentycom.jp/en/steermouse/

**Comment by latenitefilms** [comment]
@randomeizer - Do you own a Magic Mouse by any chance?

**Comment by randomeizer** [comment]
I do not.
