### ISSUE TITLE
Add Right-Click Menu Options to hs.chooser

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#70]
Once added to the Hammerspoon core, this will be really helpful for improving the FCPX Hacks "console" (CONTROL + SPACEBAR) - by adding the ability to "hide" or "favourite" items.

Discussed [here](https://github.com/Hammerspoon/hammerspoon/issues/1058).

**Comment by randomeizer** [comment]
That specific issue seems to be closed. It's it with creating a new one
specifically about the Right-click option.

**Comment by latenitefilms** [comment]
Note to self: test [this](https://github.com/Hammerspoon/hammerspoon/pull/1140).
