### ISSUE TITLE
Global & FCPX Shortcut Conflicts

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#713]
Currently you can have the same shortcut key applied to both a Global Shortcut key and a FCPX Shortcut key. Currently the FCPX shortcut key seems to take priority.

This shouldn't be allowed.

**Comment by latenitefilms** [comment]
This might also be helpful:

https://github.com/Hammerspoon/hammerspoon/pull/1444#issuecomment-315874852

**Comment by latenitefilms** [comment]
Related: Shortcut Panel should not display Key's already in use #509

**Comment by latenitefilms** [comment]
FYI: This will be addressed in #709

**Comment by randomeizer** [comment]
Again, not sure what #709 has to do with this issue?

**Comment by latenitefilms** [comment]
@randomeizer - I just did the code tweaks in the #709 branch. I believe all the shortcut issues are now addressed.

**Comment by randomeizer** [comment]
Ok...
