### ISSUE TITLE
Add Option to Freeze & Unfreeze Final Cut Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#716]
Related: https://github.com/Hammerspoon/hammerspoon/issues/1512

**Comment by randomeizer** [comment]
What the use case for this?

**Comment by latenitefilms** [comment]
> What the use case for this?

It seems lots of people use this "freezing" functionality to do stuff without FCPX knowing.

For example, if you need to disconnect a drive quickly to grab some stuff, but don't want to exit your library, you can just quickly freeze FCPX, do your thing, connect the drive back, unfreeze, and away you go. People have also been using it to help with force re-linking of files.

Unfortunately freezing FCPX seems to also freeze CommandPost - so I'm not sure if there'll be a way around this without serious re-coding, as I assume all our watchers, etc. are what's causing Hammerspoon to freak out when FCPX is frozen.

**Comment by randomeizer** [comment]
Huh, ok. Weird concept to me...

**Comment by latenitefilms** [comment]
Interesting idea, but probably not worth pursuing.
