### ISSUE TITLE
HUD Assign Buttons Broken after #667

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#725]

**Comment by randomeizer** [comment]
Ah yeah, I knew there was another thing that used that :p

**Comment by latenitefilms** [comment]
While you're at it, should we remove the HUD options and assign features from the menubar, and add them as right-click contextual menus to the HUD itself (i.e. to assign a function to a button you just right click on the button instead)? Save ourselves some menubar space?

Thoughts?

**Comment by latenitefilms** [comment]
Hell, if you're rewriting a lot of the HUD code anyway, maybe this is a good time to do #414?

**Comment by randomeizer** [comment]
Perhaps. It's not super intuitive though...

**Comment by randomeizer** [comment]
Maybe on #414, but I think we should leave it to beta 11. Beta 10 has taken
long enough already...

**Comment by latenitefilms** [comment]
> Perhaps. It's not super intuitive though...

Maybe we just have both options then? Keep it in the menubar, and have a right click option?

Other possibly related issues:

- "Assign Choosers" should have ability to Show/Hide Sections via Right Click #354
- Ability to Customise HUD Buttons Labels #122

**Comment by latenitefilms** [comment]
> Maybe on #414, but I think we should leave it to beta 11. Beta 10 has taken
> long enough already...

Haha, no worries. Shall we just fix the original HUD assign bug in this issue then, and tackle the rest of the HUD reconstruction in Beta 11?

**Comment by randomeizer** [comment]
Yep. I'm just going to fix bugs in this issue

**Comment by randomeizer** [comment]
That said, #354 should be automatically done thanks to the changes in #667, once it's working again.
