### ISSUE TITLE
Move Scan Final Cut Pro Button in Preferences to Help & Support Menubar

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#731]

**Comment by randomeizer** [comment]
Might want to also email the results.

**Comment by latenitefilms** [comment]
Agreed. Do you have time to tackle, or should I try later tonight?

**Comment by randomeizer** [comment]
I'll take this one, will see if I have time for #732 (emailing the results)

**Comment by randomeizer** [comment]
This should be sorted. It's been moved, and I'm outputting the results even when not in 'developer mode'.
