### ISSUE TITLE
Email the results of the "Scan FCPX" checker.

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#732]
Currently it just gets output on the error log. Would be more useful for remote problem diagnosis if it's emailed automatically.

**Comment by latenitefilms** [comment]
Does it only get added to the Error Log if in debug mode currently?

**Comment by latenitefilms** [comment]
I reckon this should still just open up the CommandPost Feedback Form - as there's a possibility CommandPost won't know the users name and email, so we'll need to prompt for this anyway.

An another option is we just add a "Gather information about Final Cut Pro" option INSIDE the Feedback Form (as opposed to making it a menubar item), which does the GUI scan (that's off by default)?

**Comment by randomeizer** [comment]
Yeah, currently just displays if in debug mode.

Integrating it as an option for the feedback form, sure. I just think we'll get a lot of other noise if we just dump the error log...
