### ISSUE TITLE
Add an uninstall script that removes Preferences, Caches & Saved Keyboard Shortcuts

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#733]

**Comment by randomeizer** [comment]
I got this one

**Comment by randomeizer** [comment]
I've added code that will trigger when trashing prefs to clear any plugin scanner and custom keyboard shortcuts.

For future reference, the recommended way is to add a 'watch' event for 'reset' to `cp.config`. Eg:

```lua
config.watch({ reset = deleteStuffFunction })
```

See `cp.apple.finalcutpro.plugins` for an example.
