### ISSUE TITLE
Add Seal to CommandPost are Core Plugin?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#745]
Is this worth bringing across to CommandPost?

http://www.hammerspoon.org/Spoons/Seal.html

**Comment by randomeizer** [comment]
What is it exactly?

**Comment by latenitefilms** [comment]
It's like our Console, but more for general macOS usage, as opposed to inside Final Cut Pro.

Basically an [Alfred](https://www.alfredapp.com) alternative I guess?

**Comment by randomeizer** [comment]
Well, I think we will just generalise the Console eventually.

**Comment by latenitefilms** [comment]
Interesting idea, but closing for now.
