### ISSUE TITLE
Plugin Shortcuts labels look dodgy in Final Cut Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#764]
<img width="1111" alt="screen shot 2017-09-21 at 1 45 20 am" src="https://user-images.githubusercontent.com/22286696/30653503-9728946a-9e6e-11e7-9664-4819a3a468a3.png">

**Comment by randomeizer** [comment]
I believe this is just some missing i18n keys for the new Audio Effect shortcuts.

**Comment by latenitefilms** [comment]
@randomeizer - No, because unless you've done something magic without me noticing, we still need to manually create the Command Set files for each language?

**Comment by randomeizer** [comment]
No Magic has happened as yet 😜
