### ISSUE TITLE
Change Plugins to Save Default Shortcuts to somewhere restorable

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#768]
Currently when you click "Reset to Default Shortcuts" in the Shortcuts Preferences in CommandPost, it requires CommandPost to restart, as that's currently the only way to "reset" the shortcuts (as the default shortcut values are only "visible" when each plugin is first loaded). Ideally, you shouldn't have to restart, so I propose that we add a function in commands for setting a "Default" shortcut, so that it can be retrieved later.

**Comment by latenitefilms** [comment]
FYI: This will be addressed in #709

**Comment by randomeizer** [comment]
This is kind of a separate issue to #709 really. It's about how command are
configured internally, not in the UI.

**Comment by latenitefilms** [comment]
How do you mean?

**Comment by randomeizer** [comment]
Actually, I'm not sure how #709 has anything to do with this issue, since that one is about dialog boxes. I thought you might have meant #713, but that is also closed.

Is there still an open issue for improving the Shortcut Key issues?
