### ISSUE TITLE
Various Console Bugs

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#777]
Even after 10 seconds of CommandPost starting, the Console still takes a really long time on my machine to open for the first time. Maybe something is happening on the console's first load that's not being handled already by `preloadChoices()`?

**Comment by latenitefilms** [comment]
FYI: I'm just going to change the idle time to 5sec in #757

**Comment by randomeizer** [comment]
I think there is a caching issue, which is why the Console loads slowly the
first time. Haven't had time to track it down yet.

**Comment by latenitefilms** [comment]
No worries, I'll re-open this issue then. It works great after the preloading is done. The preloading just takes a while to do.

**Comment by latenitefilms** [comment]
@randomeizer - Also, if you open the Console before the preloading has completed, the Console won't function correctly, so you need to close it and reopen.

**Comment by latenitefilms** [comment]
Also, changing sections via right clicking on the Console, doesn't automatically update the Console's content.

**Comment by latenitefilms** [comment]
```
2017-09-29 16:28:49: ********
2017-09-29 16:28:49: 16:28:49 ERROR:      idle: Error while processing idle queue:
attempt to index a nil value
stack traceback:
	[C]: in for iterator 'for iterator'
	...mandPost/src/extensions/cp/apple/finalcutpro/MenuBar.lua:316: in function 'cp.apple.finalcutpro.MenuBar._visitMenuItems'
	...mandPost/src/extensions/cp/apple/finalcutpro/MenuBar.lua:325: in function 'cp.apple.finalcutpro.MenuBar._visitMenuItems'
	...mandPost/src/extensions/cp/apple/finalcutpro/MenuBar.lua:317: in function 'cp.apple.finalcutpro.MenuBar._visitMenuItems'
	...mandPost/src/extensions/cp/apple/finalcutpro/MenuBar.lua:307: in function 'cp.apple.finalcutpro.MenuBar.visitMenuItems'
	.../CommandPost/src/plugins/finalcutpro/menu/menuaction.lua:82: in field '_onChoices'
	...dPost/src/plugins/finalcutpro/action/manager/handler.lua:132: in field '_get'
	...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:424: in function <...cking/Github/CommandPost/src/extensions/cp/prop/init.lua:423>
	(...tail calls...)
	...ost/src/plugins/finalcutpro/action/manager/activator.lua:600: in method '_findChoices'
	...ost/src/plugins/finalcutpro/action/manager/activator.lua:200: in function <...ost/src/plugins/finalcutpro/action/manager/activator.lua:198>
	[C]: in function 'xpcall'
	...cking/Github/CommandPost/src/extensions/cp/idle/init.lua:35: in function <...cking/Github/CommandPost/src/extensions/cp/idle/init.lua:24>
2017-09-29 16:28:49: ********
```

**Comment by latenitefilms** [comment]
@randomeizer - I've had a quick look, but I'm not exactly sure why the Console is so slow and sometimes buggy. Will leave you to have a play when you get a chance.

**Comment by randomeizer** [comment]
I've checked in some improvements into the 777 branch. There is still a 2- to 3-second delay initially (on my machine), due to the FCPX plugin scanner, but it's generally much better for me. Can you have a test and let me know your results.

I may try to add some additional caching for the plugin scanner, but I haven't had a chance yet.

**Comment by latenitefilms** [comment]
Sweet - that's heaps better. Maybe we just need to change the "loaded" alert to "loading"?

**Comment by latenitefilms** [comment]
Or add some checks in there so that we only re-scan things if the folder file size has changed between reloads?

**Comment by randomeizer** [comment]
Not sure that checking folder size will speed anything up. My guess is it
would more likely slow it down.

I think the main thing that would speed up the check would be native
Unicode reading support. Not sure how far away that is.

**Comment by latenitefilms** [comment]
You're on Sierra now - so you shouldn't need the Unicode stuff, right? My original plugin code worked fine, so all my plugins are in the standard/modern format - so I'm ASSUMING that my machine doesn't need to use any of the special Unicode processing?

**Comment by latenitefilms** [comment]
Did you want me to merge in this issue, then we can improve the FCPX plugin scanner in a new issue?

**Comment by latenitefilms** [comment]
FYI: I'm just gonna merge for now, and do the FCPX Plugin Scanner tweaks as a new issue.

**Comment by randomeizer** [comment]
I don't think that Sierra is the source or solution for the Unicode requirement. It's just part of how it works. I suspect that plugins which do support multiple languages will do so using Unicode, so I don't think we can just remove it. But there is definitely room for improving performance.

**Comment by latenitefilms** [comment]
I'm more saying, that my original attempt at the Final Cut Pro scanner, didn't take into account any of the Unicode stuff, and I still got a 100% match for all my plugins and effects (in English). It was only your machine that needed the Unicode processing (which we ASSUMED was because you did lots of upgrades in the past, so some effects/plugins might be really old).

**Comment by randomeizer** [comment]
And I still have those plugins. And others probably will too.

**Comment by latenitefilms** [comment]
Yeah, I completely get that - and we definitely NEED the fancy Unicode support stuff you've done - you've done an incredible job. My point was that, at least on my machine, the Unicode stuff shouldn't be what's slowing things down (as I don't have any plugins that require special Unicode processing). So ignoring the Unicode performance, we probably still should try and improve the scanning functionality overall. That said... on your machine, and any other machines that have been upgraded from older versions of macOS, it probably means the scanning process will even be slower.

I wonder if Apple "upgrades" all of these localisation files when you upgrade to High Sierra - given they're already changing the file system?

**Comment by randomeizer** [comment]
It assumes everything is Unicode. The stuff on your machine is actually in
Unicode, just in UTF-8, which is a variation that Lua has some native super
for. But I'm order to support other variations such as UTF-16, it's all
using my Unicode library, regardless.

**Comment by latenitefilms** [comment]
Ah, ha. Gottcha. Is there a way to only use your library if it's UTF-16?

**Comment by randomeizer** [comment]
Not easily.
