### ISSUE TITLE
Add all Final Cut Pro menu items to the FCPX Hacks Console

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#78]
Using the "Help > Search" menu, you're able to search for any item that's in the Final Cut Pro menus. It would be awesome if we could also do this with the FCPX Hacks Console, so that if you forget a shortcut key, you can just quickly search for the command you want, without having to leave the keyboard.

**Comment by randomeizer** [comment]
Which release was this in? 0.70?

**Comment by latenitefilms** [comment]
v0.69 I think?
