### ISSUE TITLE
Action Handler Bug

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#797]
```
2017-10-04 01:28:30: ********
2017-10-04 01:28:30: 01:28:30 ERROR:   LuaSkin: hs.chooser:completionCallback error - ...ommandPost/src/plugins/core/action/manager/activator.lua:820: No action handler with an ID of "global_cmds" is registered.
stack traceback:
	[C]: in function 'error'
	...ommandPost/src/plugins/core/action/manager/activator.lua:820: in method 'activate'
	...ommandPost/src/plugins/core/action/manager/activator.lua:673: in function <...ommandPost/src/plugins/core/action/manager/activator.lua:673>
2017-10-04 01:28:30: ********
```

**Comment by latenitefilms** [comment]
Ah crap, I think this is the same issue as #787 and #789 - as it's now working fine. I think all our `hs.chooser` callbacks just take too long.

**Comment by latenitefilms** [comment]
FYI: I've posted this:

https://github.com/Hammerspoon/hammerspoon/issues/1566

**Comment by latenitefilms** [comment]
FYI: I've done some experiments in the #797 branch.

This definitely takes a long time to execute:

```
	error, result = pcall(executeFn)
	error, result = pcall(rightClickFn)
	error, result = pcall(choicesFn)
	error, result = pcall(searchSubText)
```

I wondering if it's worth doing an experiment with just presenting a simple `hs.chooser` without any of the fancy sorting/menubar, and see if that works fine as is?

**Comment by randomeizer** [comment]
Can you define 'long time to execute'? I have no idea why `searchSubText` would be slow, for example.

**Comment by latenitefilms** [comment]
I'm not sure about the individual functions, but inserting this in-line:

```
error, result = pcall(executeFn)
error, result = pcall(rightClickFn)
error, result = pcall(choicesFn)
error, result = pcall(searchSubText)
```

...causes a spinning wheel of doom for at least 4 or 5 seconds.
