### ISSUE TITLE
Write script to detect unused variables in en.lua

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#823]
I'm sure there's lots of stuff in `en.lua` that we no longer actually use. It would be cool to write a little script that generates a list of any unused variables so we can clean up `en.lua`.

**Comment by cailyoung** [comment]
I just linted the file and just internally you've got a lot of variables declared and then re-defined a few lines later. Would it be worth me trying to fix that?

**Comment by latenitefilms** [comment]
@cailyoung - I have no idea what linting is, but absolutely - go for it!

#155 might be another fun Cail project too?

Another thing I've been pondering for ages (but I don't think has an issue) is setting up a macOS server somewhere on the Interwebs, installing FCP7 & Hammerspoon, then building a cloud-based service that does FCP7 to FCPXML conversions via CommandPost. Might be another fun little Cail project?

**Comment by latenitefilms** [comment]
Googling "lint" - this might also be relevant/helpful?

http://lua-users.org/wiki/LuaLint
https://github.com/mpeterv/luacheck

**Comment by cailyoung** [comment]
Yeah, I ran luacheck on it in Atom. I’m guessing that as new pieces of UI have been added that this file has grown but there’s no mechanism to ensure the variable names are unique. In most cases I could see that (at least in English) the string value was the same but for a few it’s different, which means I will need to find the function that uses the string and rename the variable to fix the conflict. 

When I’m back in front of a computer I’ll open another issue for the duplicate variable names and self assign. This issue is about figuring out which ones are unused in the project. Have you removed much UI through the development history?

There might be a better way to handle string localisation going forward but that will be a larger piece of refactoring.

**Comment by latenitefilms** [comment]
>  I’m guessing that as new pieces of UI have been added that this file has grown but there’s no mechanism to ensure the variable names are unique.

Correct. To be honest, it's never even crossed my mind to check for duplicates before I add something new to `en.lua`.

I just realised there's a "Find Duplicates" feature in BBEdit, so I've just quickly gone and removed the duplicates that this tool found. However, you mind want to double check I haven't missed any (or come up with a way to automate it - maybe using [Travis](https://travis-ci.org)?).

> This issue is about figuring out which ones are unused in the project. Have you removed much UI through the development history?

Yeah, I'd say so. I'm pretty sure we implemented `i18n` back in the FCPX Hacks days, so we've moved things around and changed things dramatically since then. I'm sure there's lots of cases where we've removed a variable in the code, but forgot to update `en.lua`.

> There might be a better way to handle string localisation going forward but that will be a larger piece of refactoring.

Definitely open to suggestions here. Someone actually went to the trouble of creating a Dutch translation of FCPX Hacks - however, because we change around things almost constantly, it was going to be a giant pain to constantly have to keep the Dutch version in sync with the English version. If we could automate translations though (and do manual fixes as required as people submit issues), that would be ideal.

**Comment by randomeizer** [comment]
I had thoughts about building a UI to let people provide their own translations for the various keys, but it's Yet Another Task that would take a while to build.

Cleaning it up is definitely worth doing. Not sure the best system for that though.

**Comment by latenitefilms** [comment]
@randomeizer - Owwwwww... an interface for building/managing translations is a great idea! But yeah, would be pretty low on the priority list.

**Comment by cailyoung** [comment]
@latenitefilms still two left in the file: `cpChangeBackupInterval_title` and `cpAllowTasksDuringPlayback_title` - when I search across all files I don't see them used anywhere...

**Comment by cailyoung** [comment]
I would think a more lightweight way to encourage localisation would be to expose this `en.lua` file more easily and encourage pull requests to add translated versions to the project, along with some documentation on where else changes need to be made to enable those strings to be used. Is there a user facing language selector (for the CommandPost UI, that is) that pulls a list of values from somewhere?

Do users have a way to select distinct languages for the CommandPost UI versus the FCPX language on the system?

**Comment by latenitefilms** [comment]
> @latenitefilms still two left in the file: cpChangeBackupInterval_title and cpAllowTasksDuringPlayback_title - 

Fixed - thanks!

> when I search across all files I don't see them used anywhere...

If you search for the text `cpChangeBackupInterval_title` across all the files in `src`, you'll only find them in `en.lua` - because we programatically combine `cpChangeBackupInterval` and `_title`.

If you look in `backupinterval.lua` at [line 103](https://github.com/CommandPost/CommandPost/blob/develop/src/plugins/finalcutpro/hacks/backupinterval.lua#L103), you'll see `deps.fcpxCmds:add("cpChangeBackupInterval")` - with another script, we take this `cpChangeBackupInterval` value and if `cpChangeBackupInterval_title` exists in `en.lua` then we'll use this value for various things.

Same goes for things like `compressor_watchfolders_panels_media_label`, `plugin_group_compressor`, `shortcut_group_global`, `timeline_group` etc.

So yeah... thinking about it... this will make things slightly more difficult.

> Is there a user facing language selector (for the CommandPost UI, that is) that pulls a list of values from somewhere?

Yes, there's a language selection dropdown in the General Preferences tab. Currently there's only English, but if you duplicated it, and changed the first three lines, it would automatically detect the "new" language.

![screen shot 2017-10-29 at 10 44 07 pm](https://user-images.githubusercontent.com/22286696/32143252-bca3816e-bcfa-11e7-9790-d4aa6f1a6ec6.png)

> Do users have a way to select distinct languages for the CommandPost UI versus the FCPX language on the system?

Yes, you can select the Final Cut Pro language from the menubar (see below screenshot), which is independent from the CommandPost language, as shown in the above screenshot.

![screen shot 2017-10-29 at 10 46 35 pm](https://user-images.githubusercontent.com/22286696/32143277-0ab49d7a-bcfb-11e7-8be5-14af0630bb76.png)

> I would think a more lightweight way to encourage localisation would be to expose this en.lua file more easily and encourage pull requests to add translated versions to the project, along with some documentation on where else changes need to be made to enable those strings to be used.

Well, it's not exactly SIMPLE - but we do have basic instructions on the developers guide:

https://dev.commandpost.io/internationalisation/translate/
