### ISSUE TITLE
Virtual Touch Bar Bug

### ISSUE THREAD

**Issue by louisbastin** [fcpxhacks/fcpxhacks#824]
The VIRTUAL TOUCHBAR (my cmd post prefered function)has disappeared ! Impossible to reactive it in the menubar, on FCPx 10.3.4. And no way to communicate through command post feedback in menu, it doesn't work either… Should I reinstall cmd post ?
Thank you.

**Comment by latenitefilms** [comment]
I assume you've tried restarting your computer, etc.?

Maybe try trashing the CommandPost preferences?

We have a new beta NEARLY ready to release, which HOPEFULLY fixes a lot of issues.

**Comment by latenitefilms** [comment]
@louisbastin - This SHOULD be fixed in beta 11, which I'm hoping to release later today. If it doesn't fix your problem, please re-open this issue.

**Comment by louisbastin** [comment]
Thanks for the answer, Chris, I’m sure you’ll find solutions.
