### ISSUE TITLE
Preferences window is slow to open

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#866]

**Comment by latenitefilms** [comment]
@randomeizer - Not sure there's much we can do to improve this issue without completely re-thinking the way we do the interface?

**Comment by randomeizer** [comment]
Yeah, it will be a big job. Maybe next beta?

**Comment by latenitefilms** [comment]
I reckon maybe rather than us doing a major re-write, we wait until `hs._asm.guik` is ready for prime time, as this should give us a big performance boost, and make callbacks waaaaaaaay easier to manage.

**Comment by latenitefilms** [comment]
This will probably happen after we release v1.0.0 - depending on when @asmagill resurfaces - but I'll leave this issue floating around Beta 30-32 until then.

**Comment by randomeizer** [comment]
It's definitely worth doing, but I don't think it will happen in beta 30.

**Comment by latenitefilms** [comment]
Closed in favour of #1419.
