### ISSUE TITLE
Add support for Final Cut Pro 10.4's new Color Inspector

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#884]

**Comment by latenitefilms** [comment]
Iain Anderson writes:

> They're missing "next wheel" or "next curve" — call it "next block"? You can press Tab, but it's easy to leave the inspector completely if you press one too many times. Also there's no way to move between curves by key. If you show a single curve at once, it should behave like "Next/Prev Pane" (and could apply to moving between curves too) but it doesn't work.
> 
> There's also no way to add a curve point by key, but I don't see how that could work.

**Comment by latenitefilms** [comment]
Here's a bit of a check list @randomeizer:

**Color Inspector**
- [ ] Add API for "Add Shape Mask", "Add Color Mask" and "Invert Masks".
- [ ] Add API for "Save Effects Preset".
- [ ] Add API for "Mask Inside/Output".
- [ ] Add API for "View Masks".

**Color Board**
- [x] Work out whether or not we should "link to" what we already have in the `cp.apple.finalcutpro.main.ColorBoard` module?
- [ ] Add Actions to reset individual Color Board Pucks via CommandPost

**Color Wheels**
- [x] `cp.apple.finalcutpro.main.Inspector.ColorInspector.ColorWheels:nudgeControl` should use GUI Scripting instead of shortcuts
- [x] `cp.apple.finalcutpro.main.Inspector.ColorInspector.ColorWheels:color` should use GUI Scripting on AXColorWell instead of the RGB text boxes
- [ ] Replace the map in `cp.apple.finalcutpro.main.Inspector.ColorInspector.ColorWheels:brightness` with a mathematical formula

**Color Curves**
- [ ] `preserveLuma` currently only gets, not sets, because the checkbox is read only. Might have to use ninja mouse click?
- [ ] Add API to Reset Individual Curves
- [ ] Add API to trigger Color Picker for Individual Curves

**Hue/Saturation Curves**
- [ ] Add API to Reset Individual Curves
- [ ] Add API to trigger Color Picker for Individual Curves
- [ ] Add API to adjust entire curve for each curve
- [ ] Add API for "Preserve Luma" Checkbox

**Comment by cailyoung** [comment]
![screen shot 2018-01-20 at 9 32 46 am](https://user-images.githubusercontent.com/3939499/35174841-eecabf08-fdc4-11e7-950d-939b044ec184.png)
`FCP = -0.0238*AX*AX + 2.0188*AX - 1.0063`

According to this regression analysis. But the curve is *weird*. Very steppy. Are you sure of the source data?

**Comment by cailyoung** [comment]
Linear version would be `FCP = 2.0066*AX - 1.0053`

**Comment by latenitefilms** [comment]
No idea. David’s done a bunch of stuff on this that hasn’t been pushed yet.

**Comment by randomeizer** [comment]
I think it is just a straight 2AX - 1 formula.
