### ISSUE TITLE
Unify the Global Console and FCPX Console

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#908]
Currently, there are two consoles, with separate keyboard commands, each with different options available.

I would prefer that there was one Console, and it would only show actions that are available in the current context. If it's in FCPX, the FCPX options show, if not, only the global ones. This would make it more scalable to when we add support for more apps over time.

Chris has noted that he likes to have different shortcuts for each because of potential key-combo clashes in FCPX. I think a better way to manage that is to allow 'app-specific overrides' to keyboard combos. But this is a big change and I'll create a separate issue to tackle it.

**Comment by randomeizer** [comment]
#909 is handling the shortcut override improvement.

**Comment by latenitefilms** [comment]
Sweet, sounds good to me.

If you are making tweaks to the Console code, one other thing to keep in mind is that eventually I'd like to add Spotlight-style functionality to the Console too - for example #868. I think we discussed this more on Facebook Messenger.
