### ISSUE TITLE
Conflict with FxFactory

### ISSUE THREAD

**Issue by louisbastin** [fcpxhacks/fcpxhacks#914]
Some FxFactory plugins seem not to be compatible with Command Post: I had a big issue with "Rolling Credits" on all my computers (FCPx10.3 or 10.4), the rolling text generator was no more working at all and I had lost all my text inside this plugin, and it finally appeared that uninstalling command post resolved the problem immediatly (it worked again and I recovered my text).
Is there a way to use both Command Post and external plugins from FxFactory ?
Thanks

**Comment by latenitefilms** [comment]
@louisbastin - Ummm... this seems VERY odd, as I have no idea how CommandPost could have any affect on Title effects. We also have FxFactory on all our machines, and I can't say I've ever run into any issues.

Are you able to reinstall CommandPost and take a video of the issue you're having?

**Comment by latenitefilms** [comment]
@louisbastin - I've tried installing the FxFactory SUGARfx Rolling Credits plugin on a couple of machines, and it seems to work fine with CommandPost installed. I haven't been able to reproduce your issue.

CommandPost is essentially isolated from Final Cut Pro - so in theory, problems like this should never happen, as Final Cut Pro has no knowledge or awareness of CommandPost. The way CommandPost controls Final Cut Pro for the most part is via macOS's Accessibility API - so when we do things like the scrolling timeline, etc. it's actually CommandPost telling macOS to tell Final Cut Pro what to do.

Also, you don't need to "uninstall" CommandPost. If CommandPost is not running, then it will definitely have no impact on Final Cut Pro - so you can happily open/quit CommandPost with Final Cut Pro is running.

I'm going to close this issue for now, as I think it must have been a coincidence that closing CommandPost fixed your issue. However, if you can reproduce, feel free to open the issue again and post a comment.
