### ISSUE TITLE
CommandPost doesn't work with Final Cut Pro Trial

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#931]

**Comment by cailyoung** [comment]
https://github.com/cailyoung/CommandPost/tree/fix-fcpx-trial-detection

I begun working on this before telling @latenitefilms - Chris, I'm happy to keep hacking away at it if you like.

What would be good is to establish the preferred fix:

- Check on startup if there is a trial version of FCPX installed, and if so replace the relevant constants so that CommandPost-App is looking for that application and not the usual FCPX.
  - Problem with this would be if users run both (to test a new release) and want to continue to use CommandPost with the App Store version of FCPX.
- Add a user preference to select whether to use the trial version or the App Store version.
  - This will require a bit more refactoring but retains end-user control.

**Comment by randomeizer** [comment]
What is the key difference with it? A different Bundle ID? Version Number?

**Comment by cailyoung** [comment]
@randomeizer 

https://github.com/cailyoung/CommandPost/commit/5decbdc073b64aab1b19403c1f224139a2b319a7

The bundle ID and plist file name are different. The .app file name is different too, if that's relevant.

The trial is version 10.4 (I don't know if the full release is ahead of that).

**Comment by randomeizer** [comment]
The version number matches the full version at the moment.

I think the key issue would be the Bundle ID. I don't think we make any
assumptions about the App name at the moment (will have to do a search to
see if we hard-code it anywhere, but I believe not).

I think the simplest option would be to add it to the function that
searches for the running/available app (in
`cp.apple.finalcutpro:application()` from memory) and add as search for the
trial app as a second-priority option. Would also have to check anywhere
that issues the hard-coded Bundle ID and ensure its getting it from the
actual running app instead.

**Comment by latenitefilms** [comment]
Agreed, it would be good if this was all handled automatically and seamlessly so that the end-users can easily and instantly switch between the trial and full version without having to do anything.

We might as well tick off "Create Final Cut Pro Version Module" #531 whilst we're at it, as this issue covers the cases where we have multiple instances of the Bundle ID hardcoded.

**Comment by cailyoung** [comment]
Do you care what happens if a user is running both simultaneously? i.e. if I write the change so that the App Store version is selected first, and trial only if that fails, it means that any user running both versions simultaneously (i.e. actually running them, not just installed) will get the App Store version driven by CommandPost.

Seems reasonable to me, but wanted to check w you both.

**Comment by latenitefilms** [comment]
I’ve never checked myself - are you sure you can actually run them simultaneously? Given they share so many resources I would ASSUME they both wouldn’t run at the same time?

**Comment by cailyoung** [comment]
Apple specifically calls out what to do when installing the trial alongside an existing install - it’s a way to test a new build before updating.

**Comment by randomeizer** [comment]
Where are apple's instructions for that?

**Comment by cailyoung** [comment]
https://www.apple.com/au/final-cut-pro/trial/thankyou/

> If you’re already using a licensed copy of a prior version of Final Cut Pro X, you will be prompted to upgrade your library when the trial application is first launched. We recommend you keep a backup version of your libraries before upgrading. Once your library is upgraded, you must update your licensed copy of Final Cut Pro to access your upgraded libraries after the 30-day trial period expires.

**Comment by randomeizer** [comment]
Hmm, ok. That's just taking about the upgrade process. It would be
interesting to know if you can run two instances of final cut at the same
time. I know that it blocks FCPX and FCP7 from running at the same time.

**Comment by cailyoung** [comment]
I don't see why not, they're seperate .app files. I don't have a license for FCPX so can't check it out at my end.

**Comment by randomeizer** [comment]
It would be a manual check by Apple. I'll try test it out in the next
couple of days.

**Comment by cailyoung** [comment]
Opened a PR which just gets CP to launch against the trial version - I have no way to tell if the other branch of the if statement works against the App Store build, so please do test before merging.

**Comment by randomeizer** [comment]
Cool, I'll have a look at it tomorrow.

**Comment by randomeizer** [comment]
So, to answer one question, you can have FCPX and FCPX Trial both running simultaneously.

**Comment by latenitefilms** [comment]
@randomeizer - Now that we have `cp.app` we should probably rethink this. It could be as simple as just adding the ability to provide `cp.app` with a table of bundle ID's, and it just tries one after the other based on their order?

This branch is probably way too hard to merge back into `develop` now, so maybe we just manually merge across anything that's still relevant? It looks like you added a whole bunch of documentation, that would be good to merge across.

**Comment by latenitefilms** [comment]
I think for this issue we simply see if the main FCPX app exists on the system, and if it doesn’t we check to see if the trial exists. If the trial exists then we use the trial bundle ID. Obviously this will have issues for the few that have both the trial and full version installed, but really, the only time I’ve personally run into this is when I’ve had to do work on a machine that doesn’t have FCPX installed, so have just quickly installed the trial.
