### ISSUE TITLE
Should hs.finalcutpro be using 'select'?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#94]
In LUA, the `select` function, selects a specific return from a function.

I wonder if we should change, this (for example):

`fcp:app():menuBar():select("Window", "Go To", "Color Board")`

to:

`fcp:app():menuBar():selectMenu("Window", "Go To", "Color Board")`

...to avoid confusion? @randomeizer ?

**Comment by randomeizer** [comment]
Or we just call it `push`, since that's what it's doing.

**Comment by latenitefilms** [comment]
I think maybe `push` is also a bit too generic as well? I think `selectMenu` makes sense?

**Comment by randomeizer** [comment]
Sure, can do. It is in the 'MenuBar' object though ;)

**Comment by latenitefilms** [comment]
Ummm... I think it still works. This "looks" fine to me?

`hs.finalcutpro:app():menuBar():selectMenu("Window", "Go To", "Color Board")`

**Comment by latenitefilms** [comment]
Although, this could be better?

`hs.finalcutpro:menuBar():selectMenu("Window", "Go To", "Color Board")`

**Comment by randomeizer** [comment]
Eventually. I need to migrate more stuff to App first.

**Comment by randomeizer** [comment]
I've created a separate issue to track that as #100. I'm going to make this simple change here and merge it.

**Comment by randomeizer** [comment]
Merged.
