### ISSUE TITLE
commandEditorWatcher() needs to be reviewed

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#95]
Currently `commandEditorWatcher()` is making use of hard-coded values for the Command Editor Window Title. We should probably work out a better way of doing this, in case Apple releases more languages for FCPX in the future. Maybe we should detect the language then read the title from a plist?

**Comment by randomeizer** [comment]
If we can figure out what plist to pull from...

**Comment by randomeizer** [comment]
I've found a way to check it without using anything language-specific. Also created the basic CommandEditor class in the hs.finalcutpro API.

**Comment by latenitefilms** [comment]
Awesome work!
