### ISSUE TITLE
Watch Folders fail with After Effects Renders

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#964]
Nash writes:

> Hello Chris,
> 
> I was just playing with watch folders in CP. It seems it does not work with After Effects. 
> Here is what I did. My FCPX and AE are opened. I point watch folders to a "location".
> 
> I switch over to AE and create a test comp to render to the "location". When I click render, I get incoming file notification (I also get multiple notifications of the same file). 
> After my AE render is complete, I get the import notification. When I click import from the notification, I get spinning rainbow wheel.
> It seems very buggy and unstable. FCPX becomes unresponsive. Hope you can fix this problem. 
> 
> It will be great if you can prioritise.  https://github.com/CommandPost/CommandPost/issues/90
> Maybe not in the next build but at least the following. :) I can help you to beta test the build to find all the issues and bugs. :)
> 
> Thank you Chris.

**Comment by randomeizer** [comment]
This should be fixed in #1282.

**Comment by latenitefilms** [comment]
I think with this issue, we need add in a timer delay to make sure the file size isn't still increasing.

**Comment by latenitefilms** [comment]
I can't reproduce this, so I'm going to close this issue. We can test this in #1282.
