### ISSUE TITLE
Clean up code to reduce the amount of init.lua files

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#965]

**Comment by latenitefilms** [comment]
We might as well do this before releasing Beta 30 to the wild.

**Comment by randomeizer** [comment]
Sure

**Comment by latenitefilms** [comment]
@randomeizer - Do we still actually want to do this? Having lots of `init.lua` files has never really bothered me too much as it's pretty easy to navigate through folders?

**Comment by randomeizer** [comment]
Yeah, I still want to do it.

**Comment by latenitefilms** [comment]
I think we just gradually do this as we're going along, so I'm going to close this issue for now.
