### ISSUE TITLE
Keywords Plugin Broken - Add Keywords to Final Cut Pro API

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#974]
We're currently using hardcoded `_NS` values in ` plugins.finalcutpro.browser.keywords`.

@randomeizer - We should probably add the Keyword Editor to the Final Cut Pro API, and rewrite this plugin to use the API - as all the code in this plugin looks pretty much like original FCPX Hacks code. Lots of loops within loops!

**Comment by randomeizer** [comment]
Yep, probably :p
