### ISSUE TITLE
Force FCPX preferences update after modification

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#98]
It might be possible to force a preferences cache update:

http://hints.macworld.com/article.php?story=20130908042828630

**Comment by randomeizer** [comment]
This would allow us to modify FCPX settings such as 'Created Optimized Media' without clicking through the GUI.

**Comment by latenitefilms** [comment]
I THINK that article is only relevant for when you're CHANGING plist settings, and the OS isn't recognising that the plist file itself has been changed. I THINK our problem is not so much that, it's more that Final Cut Pro is not actually WRITING to the plist file instantly.

**Comment by randomeizer** [comment]
I'm suggesting we might be able to simply update the plist file and force FCPX to read it without rebooting. That would mean we can set the value off-screen and not have to navigate the menus/preferences window to change the settings.

**Comment by randomeizer** [comment]
Ok, so I've pushed a small change into features/issue-98 which forces the cache to update, as well as just using that to update the 'Create Optimized Media' setting. It has the following effect:

* The change is reflected in the FCPX Hacks menu
* No change in the Preferences window for 'Create Optimized Media' in the 'Import' tab
* Change is reflected in the Media Import window.

So, the actual effect is correct - it will tweak the checkbox in the Media Import window - but it doesn't reflect correctly in the Preferences window.

Not sure if there's any way to fix that though.

**Comment by randomeizer** [comment]
I tested it on 'Moving Markers' as well, but that one definitely needs a restart unfortunately.

Probably not much point pursuing it at this stage.

**Comment by randomeizer** [comment]
For the record, this is the command which will force the cache to update:

```lua
executeResult, executeStatus = hs.execute("killall cfprefsd")
```

**Comment by randomeizer** [comment]
There are two separate issues. The delay after FCPX changes something, and
the fact that FCPX won't recognise changes made directly to the plist until
you restart it. I was looking for a solution to the latter issue.

**Comment by latenitefilms** [comment]
Unfortunately, unless there's some kind of magical way of tricky Final Cut Pro to trigger one of its own internal functions ([code injection?](http://soundly.me/osx-injection-override-tutorial-hello-world/)), I don't think there's anyway to solve this.

**Comment by randomeizer** [comment]
Yeah, agreed. I was hoping it would automatically pick up the changes if
the cache was flushed. Unfortunately it only seems to do it in a partial
fashion.
