### ISSUE TITLE
Replace all tabs with spaces and remove empty spaces at end of lines

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#980]
...to keep @stickler-ci happy.

**Comment by latenitefilms** [comment]
@randomeizer - I'd suggest we do this once you've finished off the Color Inspector code.

**Comment by randomeizer** [comment]
Sounds good

**Comment by latenitefilms** [comment]
@randomeizer - We might as well do this for Beta 22?
