### ISSUE TITLE
Scrolling Timeline Interferes with Typing in Timeline

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#988]
Dean Sherwood writes:

> **What went wrong?**
> In Multicam Angle when changing the angle name space bar makes the playhead move rather than adding a space to the rename window.
> 
> **What did you expect to happen?**
> a space to be added in the rename window
> 
> **What are the steps to recreate the problem?**
> enable scrolling timeline. go into a multicam angle, change the name by clicking on the down arrow of the angle, hit spacebar and the playhead starts playing.

**Comment by latenitefilms** [comment]
@randomeizer - Is this now fixed with the new `isPlaying` callback?

**Comment by randomeizer** [comment]
I haven't changed how the scrolling timeline is triggered at this point. Once the bugs with detecting 'isPlaying' are fixed, we could drop the need to have the mouse over/presssing spacebar as the trigger, but I haven't implemented that yet.

**Comment by latenitefilms** [comment]
This specific problem (i.e. renaming clips in the Angle Editor with spaces) looks like it's fixed, so closing this issue.
