### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#99]
It would be good to have some automated testing. This could be unit/functional testing, or GUI testing.

Some possibly-useful links:

* https://codecov.io/#languages
* https://github.com/codecov/example-lua
* http://keplerproject.github.io/luacov/
* https://olivinelabs.com/busted/

**Comment by latenitefilms** [comment]
Sounds like a great idea! I'll leave this in your very capable hands though, as it all sounds a bit too fancy for a simple mind like me!

**Comment by latenitefilms** [comment]
This might also be relevant: travis-ci.org

**Comment by latenitefilms** [comment]
I feel like we've already solved this, so closing this issue.
